package com.fi.crm.campaigns.persistence.mappers;

import com.fi.crm.campaigns.persistence.model.Argetid;
import com.fi.crm.campaigns.persistence.model.ArgetidExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ArgetidMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NAF6.ARGETID
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    int countByExample(ArgetidExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NAF6.ARGETID
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    int deleteByExample(ArgetidExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NAF6.ARGETID
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    int deleteByPrimaryKey(String codigo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NAF6.ARGETID
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    int insert(Argetid record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NAF6.ARGETID
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    int insertSelective(Argetid record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NAF6.ARGETID
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    List<Argetid> selectByExample(ArgetidExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NAF6.ARGETID
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    Argetid selectByPrimaryKey(String codigo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NAF6.ARGETID
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    int updateByExampleSelective(@Param("record") Argetid record, @Param("example") ArgetidExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NAF6.ARGETID
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    int updateByExample(@Param("record") Argetid record, @Param("example") ArgetidExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NAF6.ARGETID
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    int updateByPrimaryKeySelective(Argetid record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NAF6.ARGETID
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    int updateByPrimaryKey(Argetid record);
}