package com.fi.crm.campaigns.persistence.mappers;

import com.fi.crm.campaigns.persistence.model.Argecan;
import com.fi.crm.campaigns.persistence.model.ArgecanExample;
import com.fi.crm.campaigns.persistence.model.ArgecanKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ArgecanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NAF6.ARGECAN
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    int countByExample(ArgecanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NAF6.ARGECAN
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    int deleteByExample(ArgecanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NAF6.ARGECAN
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    int deleteByPrimaryKey(ArgecanKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NAF6.ARGECAN
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    int insert(Argecan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NAF6.ARGECAN
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    int insertSelective(Argecan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NAF6.ARGECAN
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    List<Argecan> selectByExample(ArgecanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NAF6.ARGECAN
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    Argecan selectByPrimaryKey(ArgecanKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NAF6.ARGECAN
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    int updateByExampleSelective(@Param("record") Argecan record, @Param("example") ArgecanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NAF6.ARGECAN
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    int updateByExample(@Param("record") Argecan record, @Param("example") ArgecanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NAF6.ARGECAN
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    int updateByPrimaryKeySelective(Argecan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NAF6.ARGECAN
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    int updateByPrimaryKey(Argecan record);
}