package com.fi.crm.campaigns.persistence.mappers;

import com.fi.crm.campaigns.persistence.model.Argepro;
import com.fi.crm.campaigns.persistence.model.ArgeproExample;
import com.fi.crm.campaigns.persistence.model.ArgeproKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ArgeproMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NAF6.ARGEPRO
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    int countByExample(ArgeproExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NAF6.ARGEPRO
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    int deleteByExample(ArgeproExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NAF6.ARGEPRO
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    int deleteByPrimaryKey(ArgeproKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NAF6.ARGEPRO
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    int insert(Argepro record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NAF6.ARGEPRO
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    int insertSelective(Argepro record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NAF6.ARGEPRO
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    List<Argepro> selectByExample(ArgeproExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NAF6.ARGEPRO
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    Argepro selectByPrimaryKey(ArgeproKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NAF6.ARGEPRO
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    int updateByExampleSelective(@Param("record") Argepro record, @Param("example") ArgeproExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NAF6.ARGEPRO
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    int updateByExample(@Param("record") Argepro record, @Param("example") ArgeproExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NAF6.ARGEPRO
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    int updateByPrimaryKeySelective(Argepro record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NAF6.ARGEPRO
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    int updateByPrimaryKey(Argepro record);
}