package com.fi.crm.campaigns.persistence.mappers;

import com.fi.crm.campaigns.persistence.model.Arinda;
import com.fi.crm.campaigns.persistence.model.ArindaExample;
import com.fi.crm.campaigns.persistence.model.ArindaKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ArindaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NAF6.ARINDA
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    int countByExample(ArindaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NAF6.ARINDA
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    int deleteByExample(ArindaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NAF6.ARINDA
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    int deleteByPrimaryKey(ArindaKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NAF6.ARINDA
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    int insert(Arinda record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NAF6.ARINDA
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    int insertSelective(Arinda record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NAF6.ARINDA
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    List<Arinda> selectByExample(ArindaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NAF6.ARINDA
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    Arinda selectByPrimaryKey(ArindaKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NAF6.ARINDA
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    int updateByExampleSelective(@Param("record") Arinda record, @Param("example") ArindaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NAF6.ARINDA
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    int updateByExample(@Param("record") Arinda record, @Param("example") ArindaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NAF6.ARINDA
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    int updateByPrimaryKeySelective(Arinda record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NAF6.ARINDA
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    int updateByPrimaryKey(Arinda record);
}