package com.fi.crm.campaigns.persistence.mappers;

import com.fi.crm.campaigns.persistence.model.Arincd;
import com.fi.crm.campaigns.persistence.model.ArincdExample;
import com.fi.crm.campaigns.persistence.model.ArincdKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ArincdMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NAF6.ARINCD
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    int countByExample(ArincdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NAF6.ARINCD
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    int deleteByExample(ArincdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NAF6.ARINCD
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    int deleteByPrimaryKey(ArincdKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NAF6.ARINCD
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    int insert(Arincd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NAF6.ARINCD
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    int insertSelective(Arincd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NAF6.ARINCD
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    List<Arincd> selectByExample(ArincdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NAF6.ARINCD
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    Arincd selectByPrimaryKey(ArincdKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NAF6.ARINCD
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    int updateByExampleSelective(@Param("record") Arincd record, @Param("example") ArincdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NAF6.ARINCD
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    int updateByExample(@Param("record") Arincd record, @Param("example") ArincdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NAF6.ARINCD
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    int updateByPrimaryKeySelective(Arincd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NAF6.ARINCD
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    int updateByPrimaryKey(Arincd record);
}