package com.fi.crm.campaigns.persistence.mappers;

import com.fi.crm.campaigns.persistence.model.Arunneg;
import com.fi.crm.campaigns.persistence.model.ArunnegExample;
import com.fi.crm.campaigns.persistence.model.ArunnegKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ArunnegMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NAF6.ARUNNEG
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    int countByExample(ArunnegExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NAF6.ARUNNEG
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    int deleteByExample(ArunnegExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NAF6.ARUNNEG
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    int deleteByPrimaryKey(ArunnegKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NAF6.ARUNNEG
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    int insert(Arunneg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NAF6.ARUNNEG
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    int insertSelective(Arunneg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NAF6.ARUNNEG
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    List<Arunneg> selectByExample(ArunnegExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NAF6.ARUNNEG
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    Arunneg selectByPrimaryKey(ArunnegKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NAF6.ARUNNEG
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    int updateByExampleSelective(@Param("record") Arunneg record, @Param("example") ArunnegExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NAF6.ARUNNEG
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    int updateByExample(@Param("record") Arunneg record, @Param("example") ArunnegExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NAF6.ARUNNEG
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    int updateByPrimaryKeySelective(Arunneg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NAF6.ARUNNEG
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    int updateByPrimaryKey(Arunneg record);
}