package com.fi.crm.campaigns.persistence.mappers;

import com.fi.crm.campaigns.persistence.model.CpConstante;
import com.fi.crm.campaigns.persistence.model.CpConstanteExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CpConstanteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAMPAIGNS.CP_CONSTANTE
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    int countByExample(CpConstanteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAMPAIGNS.CP_CONSTANTE
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    int deleteByExample(CpConstanteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAMPAIGNS.CP_CONSTANTE
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    int deleteByPrimaryKey(String constanteId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAMPAIGNS.CP_CONSTANTE
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    int insert(CpConstante record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAMPAIGNS.CP_CONSTANTE
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    int insertSelective(CpConstante record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAMPAIGNS.CP_CONSTANTE
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    List<CpConstante> selectByExample(CpConstanteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAMPAIGNS.CP_CONSTANTE
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    CpConstante selectByPrimaryKey(String constanteId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAMPAIGNS.CP_CONSTANTE
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    int updateByExampleSelective(@Param("record") CpConstante record, @Param("example") CpConstanteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAMPAIGNS.CP_CONSTANTE
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    int updateByExample(@Param("record") CpConstante record, @Param("example") CpConstanteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAMPAIGNS.CP_CONSTANTE
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    int updateByPrimaryKeySelective(CpConstante record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAMPAIGNS.CP_CONSTANTE
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    int updateByPrimaryKey(CpConstante record);
}