package com.fi.crm.campaigns.persistence.mappers;

import com.fi.crm.campaigns.persistence.model.CpEstadoSeguimiento;
import com.fi.crm.campaigns.persistence.model.CpEstadoSeguimientoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CpEstadoSeguimientoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAMPAIGNS.CP_ESTADO_SEGUIMIENTO
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    int countByExample(CpEstadoSeguimientoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAMPAIGNS.CP_ESTADO_SEGUIMIENTO
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    int deleteByExample(CpEstadoSeguimientoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAMPAIGNS.CP_ESTADO_SEGUIMIENTO
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    int deleteByPrimaryKey(Integer estadoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAMPAIGNS.CP_ESTADO_SEGUIMIENTO
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    int insert(CpEstadoSeguimiento record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAMPAIGNS.CP_ESTADO_SEGUIMIENTO
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    int insertSelective(CpEstadoSeguimiento record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAMPAIGNS.CP_ESTADO_SEGUIMIENTO
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    List<CpEstadoSeguimiento> selectByExample(CpEstadoSeguimientoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAMPAIGNS.CP_ESTADO_SEGUIMIENTO
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    CpEstadoSeguimiento selectByPrimaryKey(Integer estadoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAMPAIGNS.CP_ESTADO_SEGUIMIENTO
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    int updateByExampleSelective(@Param("record") CpEstadoSeguimiento record, @Param("example") CpEstadoSeguimientoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAMPAIGNS.CP_ESTADO_SEGUIMIENTO
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    int updateByExample(@Param("record") CpEstadoSeguimiento record, @Param("example") CpEstadoSeguimientoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAMPAIGNS.CP_ESTADO_SEGUIMIENTO
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    int updateByPrimaryKeySelective(CpEstadoSeguimiento record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAMPAIGNS.CP_ESTADO_SEGUIMIENTO
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    int updateByPrimaryKey(CpEstadoSeguimiento record);
}