package com.fi.crm.campaigns.persistence.mappers;

import com.fi.crm.campaigns.persistence.model.CpPermisoPerfilExample;
import com.fi.crm.campaigns.persistence.model.CpPermisoPerfilKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CpPermisoPerfilMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAMPAIGNS.CP_PERMISO_PERFIL
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    int countByExample(CpPermisoPerfilExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAMPAIGNS.CP_PERMISO_PERFIL
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    int deleteByExample(CpPermisoPerfilExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAMPAIGNS.CP_PERMISO_PERFIL
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    int deleteByPrimaryKey(CpPermisoPerfilKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAMPAIGNS.CP_PERMISO_PERFIL
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    int insert(CpPermisoPerfilKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAMPAIGNS.CP_PERMISO_PERFIL
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    int insertSelective(CpPermisoPerfilKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAMPAIGNS.CP_PERMISO_PERFIL
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    List<CpPermisoPerfilKey> selectByExample(CpPermisoPerfilExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAMPAIGNS.CP_PERMISO_PERFIL
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    int updateByExampleSelective(@Param("record") CpPermisoPerfilKey record, @Param("example") CpPermisoPerfilExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAMPAIGNS.CP_PERMISO_PERFIL
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    int updateByExample(@Param("record") CpPermisoPerfilKey record, @Param("example") CpPermisoPerfilExample example);
}