package com.fi.crm.campaigns.persistence.mappers;

import com.fi.crm.campaigns.persistence.model.CpSeguimientoMensaje;
import com.fi.crm.campaigns.persistence.model.CpSeguimientoMensajeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CpSeguimientoMensajeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAMPAIGNS.CP_SEGUIMIENTO_MENSAJE
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    int countByExample(CpSeguimientoMensajeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAMPAIGNS.CP_SEGUIMIENTO_MENSAJE
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    int deleteByExample(CpSeguimientoMensajeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAMPAIGNS.CP_SEGUIMIENTO_MENSAJE
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    int deleteByPrimaryKey(Integer segMensajeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAMPAIGNS.CP_SEGUIMIENTO_MENSAJE
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    int insert(CpSeguimientoMensaje record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAMPAIGNS.CP_SEGUIMIENTO_MENSAJE
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    int insertSelective(CpSeguimientoMensaje record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAMPAIGNS.CP_SEGUIMIENTO_MENSAJE
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    List<CpSeguimientoMensaje> selectByExample(CpSeguimientoMensajeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAMPAIGNS.CP_SEGUIMIENTO_MENSAJE
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    CpSeguimientoMensaje selectByPrimaryKey(Integer segMensajeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAMPAIGNS.CP_SEGUIMIENTO_MENSAJE
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    int updateByExampleSelective(@Param("record") CpSeguimientoMensaje record, @Param("example") CpSeguimientoMensajeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAMPAIGNS.CP_SEGUIMIENTO_MENSAJE
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    int updateByExample(@Param("record") CpSeguimientoMensaje record, @Param("example") CpSeguimientoMensajeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAMPAIGNS.CP_SEGUIMIENTO_MENSAJE
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    int updateByPrimaryKeySelective(CpSeguimientoMensaje record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAMPAIGNS.CP_SEGUIMIENTO_MENSAJE
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    int updateByPrimaryKey(CpSeguimientoMensaje record);
}