package com.fi.crm.campaigns.persistence.mappers;

import com.fi.crm.campaigns.persistence.model.CpSeguimiento;
import com.fi.crm.campaigns.persistence.model.CpSeguimientoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CpSeguimientoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAMPAIGNS.CP_SEGUIMIENTO
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    int countByExample(CpSeguimientoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAMPAIGNS.CP_SEGUIMIENTO
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    int deleteByExample(CpSeguimientoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAMPAIGNS.CP_SEGUIMIENTO
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    int deleteByPrimaryKey(Integer seguimientoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAMPAIGNS.CP_SEGUIMIENTO
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    int insert(CpSeguimiento record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAMPAIGNS.CP_SEGUIMIENTO
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    int insertSelective(CpSeguimiento record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAMPAIGNS.CP_SEGUIMIENTO
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    List<CpSeguimiento> selectByExample(CpSeguimientoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAMPAIGNS.CP_SEGUIMIENTO
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    CpSeguimiento selectByPrimaryKey(Integer seguimientoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAMPAIGNS.CP_SEGUIMIENTO
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    int updateByExampleSelective(@Param("record") CpSeguimiento record, @Param("example") CpSeguimientoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAMPAIGNS.CP_SEGUIMIENTO
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    int updateByExample(@Param("record") CpSeguimiento record, @Param("example") CpSeguimientoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAMPAIGNS.CP_SEGUIMIENTO
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    int updateByPrimaryKeySelective(CpSeguimiento record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAMPAIGNS.CP_SEGUIMIENTO
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    int updateByPrimaryKey(CpSeguimiento record);
}