package com.fi.crm.campaigns.persistence.mappers;

import com.fi.crm.campaigns.persistence.model.CpUsuarioPerfil;
import com.fi.crm.campaigns.persistence.model.CpUsuarioPerfilExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CpUsuarioPerfilMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAMPAIGNS.CP_USUARIO_PERFIL
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    int countByExample(CpUsuarioPerfilExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAMPAIGNS.CP_USUARIO_PERFIL
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    int deleteByExample(CpUsuarioPerfilExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAMPAIGNS.CP_USUARIO_PERFIL
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    int deleteByPrimaryKey(Integer usuPerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAMPAIGNS.CP_USUARIO_PERFIL
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    int insert(CpUsuarioPerfil record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAMPAIGNS.CP_USUARIO_PERFIL
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    int insertSelective(CpUsuarioPerfil record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAMPAIGNS.CP_USUARIO_PERFIL
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    List<CpUsuarioPerfil> selectByExample(CpUsuarioPerfilExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAMPAIGNS.CP_USUARIO_PERFIL
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    CpUsuarioPerfil selectByPrimaryKey(Integer usuPerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAMPAIGNS.CP_USUARIO_PERFIL
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    int updateByExampleSelective(@Param("record") CpUsuarioPerfil record, @Param("example") CpUsuarioPerfilExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAMPAIGNS.CP_USUARIO_PERFIL
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    int updateByExample(@Param("record") CpUsuarioPerfil record, @Param("example") CpUsuarioPerfilExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAMPAIGNS.CP_USUARIO_PERFIL
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    int updateByPrimaryKeySelective(CpUsuarioPerfil record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAMPAIGNS.CP_USUARIO_PERFIL
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    int updateByPrimaryKey(CpUsuarioPerfil record);
}