package com.fi.crm.campaigns.persistence.mappers;

import com.fi.crm.campaigns.persistence.model.PdUsuario;
import com.fi.crm.campaigns.persistence.model.PdUsuarioExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PdUsuarioMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NAF6.PD_USUARIO
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    int countByExample(PdUsuarioExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NAF6.PD_USUARIO
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    int deleteByExample(PdUsuarioExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NAF6.PD_USUARIO
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    int deleteByPrimaryKey(String codUsuario);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NAF6.PD_USUARIO
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    int insert(PdUsuario record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NAF6.PD_USUARIO
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    int insertSelective(PdUsuario record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NAF6.PD_USUARIO
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    List<PdUsuario> selectByExample(PdUsuarioExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NAF6.PD_USUARIO
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    PdUsuario selectByPrimaryKey(String codUsuario);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NAF6.PD_USUARIO
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    int updateByExampleSelective(@Param("record") PdUsuario record, @Param("example") PdUsuarioExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NAF6.PD_USUARIO
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    int updateByExample(@Param("record") PdUsuario record, @Param("example") PdUsuarioExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NAF6.PD_USUARIO
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    int updateByPrimaryKeySelective(PdUsuario record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NAF6.PD_USUARIO
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    int updateByPrimaryKey(PdUsuario record);
}