package com.fi.crm.campaigns.persistence.mappers;

import com.fi.crm.campaigns.persistence.model.Pvclientes;
import com.fi.crm.campaigns.persistence.model.PvclientesExample;
import com.fi.crm.campaigns.persistence.model.PvclientesKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PvclientesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NAF6.PVCLIENTES
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    int countByExample(PvclientesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NAF6.PVCLIENTES
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    int deleteByExample(PvclientesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NAF6.PVCLIENTES
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    int deleteByPrimaryKey(PvclientesKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NAF6.PVCLIENTES
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    int insert(Pvclientes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NAF6.PVCLIENTES
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    int insertSelective(Pvclientes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NAF6.PVCLIENTES
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    List<Pvclientes> selectByExample(PvclientesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NAF6.PVCLIENTES
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    Pvclientes selectByPrimaryKey(PvclientesKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NAF6.PVCLIENTES
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    int updateByExampleSelective(@Param("record") Pvclientes record, @Param("example") PvclientesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NAF6.PVCLIENTES
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    int updateByExample(@Param("record") Pvclientes record, @Param("example") PvclientesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NAF6.PVCLIENTES
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    int updateByPrimaryKeySelective(Pvclientes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NAF6.PVCLIENTES
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    int updateByPrimaryKey(Pvclientes record);
}