package com.fi.crm.campaigns.persistence.mappers;

import com.fi.crm.campaigns.persistence.model.Pvusuarios;
import com.fi.crm.campaigns.persistence.model.PvusuariosExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PvusuariosMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NAF6.PVUSUARIOS
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    int countByExample(PvusuariosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NAF6.PVUSUARIOS
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    int deleteByExample(PvusuariosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NAF6.PVUSUARIOS
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    int deleteByPrimaryKey(String codUsuario);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NAF6.PVUSUARIOS
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    int insert(Pvusuarios record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NAF6.PVUSUARIOS
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    int insertSelective(Pvusuarios record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NAF6.PVUSUARIOS
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    List<Pvusuarios> selectByExample(PvusuariosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NAF6.PVUSUARIOS
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    Pvusuarios selectByPrimaryKey(String codUsuario);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NAF6.PVUSUARIOS
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    int updateByExampleSelective(@Param("record") Pvusuarios record, @Param("example") PvusuariosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NAF6.PVUSUARIOS
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    int updateByExample(@Param("record") Pvusuarios record, @Param("example") PvusuariosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NAF6.PVUSUARIOS
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    int updateByPrimaryKeySelective(Pvusuarios record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NAF6.PVUSUARIOS
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    int updateByPrimaryKey(Pvusuarios record);
}