package com.fi.crm.campaigns.persistence.model;

public class Argepro extends ArgeproKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NAF6.ARGEPRO.DESCRIPCION
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    private String descripcion;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NAF6.ARGEPRO.DESCRIPCION
     *
     * @return the value of NAF6.ARGEPRO.DESCRIPCION
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public String getDescripcion() {
        return descripcion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NAF6.ARGEPRO.DESCRIPCION
     *
     * @param descripcion the value for NAF6.ARGEPRO.DESCRIPCION
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
}