package com.fi.crm.campaigns.persistence.model;

public class ArgeproKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NAF6.ARGEPRO.PAIS
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    private String pais;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NAF6.ARGEPRO.PROVINCIA
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    private String provincia;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NAF6.ARGEPRO.PAIS
     *
     * @return the value of NAF6.ARGEPRO.PAIS
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public String getPais() {
        return pais;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NAF6.ARGEPRO.PAIS
     *
     * @param pais the value for NAF6.ARGEPRO.PAIS
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public void setPais(String pais) {
        this.pais = pais;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NAF6.ARGEPRO.PROVINCIA
     *
     * @return the value of NAF6.ARGEPRO.PROVINCIA
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public String getProvincia() {
        return provincia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NAF6.ARGEPRO.PROVINCIA
     *
     * @param provincia the value for NAF6.ARGEPRO.PROVINCIA
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public void setProvincia(String provincia) {
        this.provincia = provincia;
    }
}