package com.fi.crm.campaigns.persistence.model;

import java.util.ArrayList;
import java.util.List;

public class ArgecanExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table NAF6.ARGECAN
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table NAF6.ARGECAN
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table NAF6.ARGECAN
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NAF6.ARGECAN
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public ArgecanExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NAF6.ARGECAN
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NAF6.ARGECAN
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NAF6.ARGECAN
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NAF6.ARGECAN
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NAF6.ARGECAN
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NAF6.ARGECAN
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NAF6.ARGECAN
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NAF6.ARGECAN
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NAF6.ARGECAN
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NAF6.ARGECAN
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table NAF6.ARGECAN
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPaisIsNull() {
            addCriterion("PAIS is null");
            return (Criteria) this;
        }

        public Criteria andPaisIsNotNull() {
            addCriterion("PAIS is not null");
            return (Criteria) this;
        }

        public Criteria andPaisEqualTo(String value) {
            addCriterion("PAIS =", value, "pais");
            return (Criteria) this;
        }

        public Criteria andPaisNotEqualTo(String value) {
            addCriterion("PAIS <>", value, "pais");
            return (Criteria) this;
        }

        public Criteria andPaisGreaterThan(String value) {
            addCriterion("PAIS >", value, "pais");
            return (Criteria) this;
        }

        public Criteria andPaisGreaterThanOrEqualTo(String value) {
            addCriterion("PAIS >=", value, "pais");
            return (Criteria) this;
        }

        public Criteria andPaisLessThan(String value) {
            addCriterion("PAIS <", value, "pais");
            return (Criteria) this;
        }

        public Criteria andPaisLessThanOrEqualTo(String value) {
            addCriterion("PAIS <=", value, "pais");
            return (Criteria) this;
        }

        public Criteria andPaisLike(String value) {
            addCriterion("PAIS like", value, "pais");
            return (Criteria) this;
        }

        public Criteria andPaisNotLike(String value) {
            addCriterion("PAIS not like", value, "pais");
            return (Criteria) this;
        }

        public Criteria andPaisIn(List<String> values) {
            addCriterion("PAIS in", values, "pais");
            return (Criteria) this;
        }

        public Criteria andPaisNotIn(List<String> values) {
            addCriterion("PAIS not in", values, "pais");
            return (Criteria) this;
        }

        public Criteria andPaisBetween(String value1, String value2) {
            addCriterion("PAIS between", value1, value2, "pais");
            return (Criteria) this;
        }

        public Criteria andPaisNotBetween(String value1, String value2) {
            addCriterion("PAIS not between", value1, value2, "pais");
            return (Criteria) this;
        }

        public Criteria andProvinciaIsNull() {
            addCriterion("PROVINCIA is null");
            return (Criteria) this;
        }

        public Criteria andProvinciaIsNotNull() {
            addCriterion("PROVINCIA is not null");
            return (Criteria) this;
        }

        public Criteria andProvinciaEqualTo(String value) {
            addCriterion("PROVINCIA =", value, "provincia");
            return (Criteria) this;
        }

        public Criteria andProvinciaNotEqualTo(String value) {
            addCriterion("PROVINCIA <>", value, "provincia");
            return (Criteria) this;
        }

        public Criteria andProvinciaGreaterThan(String value) {
            addCriterion("PROVINCIA >", value, "provincia");
            return (Criteria) this;
        }

        public Criteria andProvinciaGreaterThanOrEqualTo(String value) {
            addCriterion("PROVINCIA >=", value, "provincia");
            return (Criteria) this;
        }

        public Criteria andProvinciaLessThan(String value) {
            addCriterion("PROVINCIA <", value, "provincia");
            return (Criteria) this;
        }

        public Criteria andProvinciaLessThanOrEqualTo(String value) {
            addCriterion("PROVINCIA <=", value, "provincia");
            return (Criteria) this;
        }

        public Criteria andProvinciaLike(String value) {
            addCriterion("PROVINCIA like", value, "provincia");
            return (Criteria) this;
        }

        public Criteria andProvinciaNotLike(String value) {
            addCriterion("PROVINCIA not like", value, "provincia");
            return (Criteria) this;
        }

        public Criteria andProvinciaIn(List<String> values) {
            addCriterion("PROVINCIA in", values, "provincia");
            return (Criteria) this;
        }

        public Criteria andProvinciaNotIn(List<String> values) {
            addCriterion("PROVINCIA not in", values, "provincia");
            return (Criteria) this;
        }

        public Criteria andProvinciaBetween(String value1, String value2) {
            addCriterion("PROVINCIA between", value1, value2, "provincia");
            return (Criteria) this;
        }

        public Criteria andProvinciaNotBetween(String value1, String value2) {
            addCriterion("PROVINCIA not between", value1, value2, "provincia");
            return (Criteria) this;
        }

        public Criteria andCantonIsNull() {
            addCriterion("CANTON is null");
            return (Criteria) this;
        }

        public Criteria andCantonIsNotNull() {
            addCriterion("CANTON is not null");
            return (Criteria) this;
        }

        public Criteria andCantonEqualTo(String value) {
            addCriterion("CANTON =", value, "canton");
            return (Criteria) this;
        }

        public Criteria andCantonNotEqualTo(String value) {
            addCriterion("CANTON <>", value, "canton");
            return (Criteria) this;
        }

        public Criteria andCantonGreaterThan(String value) {
            addCriterion("CANTON >", value, "canton");
            return (Criteria) this;
        }

        public Criteria andCantonGreaterThanOrEqualTo(String value) {
            addCriterion("CANTON >=", value, "canton");
            return (Criteria) this;
        }

        public Criteria andCantonLessThan(String value) {
            addCriterion("CANTON <", value, "canton");
            return (Criteria) this;
        }

        public Criteria andCantonLessThanOrEqualTo(String value) {
            addCriterion("CANTON <=", value, "canton");
            return (Criteria) this;
        }

        public Criteria andCantonLike(String value) {
            addCriterion("CANTON like", value, "canton");
            return (Criteria) this;
        }

        public Criteria andCantonNotLike(String value) {
            addCriterion("CANTON not like", value, "canton");
            return (Criteria) this;
        }

        public Criteria andCantonIn(List<String> values) {
            addCriterion("CANTON in", values, "canton");
            return (Criteria) this;
        }

        public Criteria andCantonNotIn(List<String> values) {
            addCriterion("CANTON not in", values, "canton");
            return (Criteria) this;
        }

        public Criteria andCantonBetween(String value1, String value2) {
            addCriterion("CANTON between", value1, value2, "canton");
            return (Criteria) this;
        }

        public Criteria andCantonNotBetween(String value1, String value2) {
            addCriterion("CANTON not between", value1, value2, "canton");
            return (Criteria) this;
        }

        public Criteria andDescripcionIsNull() {
            addCriterion("DESCRIPCION is null");
            return (Criteria) this;
        }

        public Criteria andDescripcionIsNotNull() {
            addCriterion("DESCRIPCION is not null");
            return (Criteria) this;
        }

        public Criteria andDescripcionEqualTo(String value) {
            addCriterion("DESCRIPCION =", value, "descripcion");
            return (Criteria) this;
        }

        public Criteria andDescripcionNotEqualTo(String value) {
            addCriterion("DESCRIPCION <>", value, "descripcion");
            return (Criteria) this;
        }

        public Criteria andDescripcionGreaterThan(String value) {
            addCriterion("DESCRIPCION >", value, "descripcion");
            return (Criteria) this;
        }

        public Criteria andDescripcionGreaterThanOrEqualTo(String value) {
            addCriterion("DESCRIPCION >=", value, "descripcion");
            return (Criteria) this;
        }

        public Criteria andDescripcionLessThan(String value) {
            addCriterion("DESCRIPCION <", value, "descripcion");
            return (Criteria) this;
        }

        public Criteria andDescripcionLessThanOrEqualTo(String value) {
            addCriterion("DESCRIPCION <=", value, "descripcion");
            return (Criteria) this;
        }

        public Criteria andDescripcionLike(String value) {
            addCriterion("DESCRIPCION like", value, "descripcion");
            return (Criteria) this;
        }

        public Criteria andDescripcionNotLike(String value) {
            addCriterion("DESCRIPCION not like", value, "descripcion");
            return (Criteria) this;
        }

        public Criteria andDescripcionIn(List<String> values) {
            addCriterion("DESCRIPCION in", values, "descripcion");
            return (Criteria) this;
        }

        public Criteria andDescripcionNotIn(List<String> values) {
            addCriterion("DESCRIPCION not in", values, "descripcion");
            return (Criteria) this;
        }

        public Criteria andDescripcionBetween(String value1, String value2) {
            addCriterion("DESCRIPCION between", value1, value2, "descripcion");
            return (Criteria) this;
        }

        public Criteria andDescripcionNotBetween(String value1, String value2) {
            addCriterion("DESCRIPCION not between", value1, value2, "descripcion");
            return (Criteria) this;
        }

        public Criteria andCodAreaIsNull() {
            addCriterion("COD_AREA is null");
            return (Criteria) this;
        }

        public Criteria andCodAreaIsNotNull() {
            addCriterion("COD_AREA is not null");
            return (Criteria) this;
        }

        public Criteria andCodAreaEqualTo(String value) {
            addCriterion("COD_AREA =", value, "codArea");
            return (Criteria) this;
        }

        public Criteria andCodAreaNotEqualTo(String value) {
            addCriterion("COD_AREA <>", value, "codArea");
            return (Criteria) this;
        }

        public Criteria andCodAreaGreaterThan(String value) {
            addCriterion("COD_AREA >", value, "codArea");
            return (Criteria) this;
        }

        public Criteria andCodAreaGreaterThanOrEqualTo(String value) {
            addCriterion("COD_AREA >=", value, "codArea");
            return (Criteria) this;
        }

        public Criteria andCodAreaLessThan(String value) {
            addCriterion("COD_AREA <", value, "codArea");
            return (Criteria) this;
        }

        public Criteria andCodAreaLessThanOrEqualTo(String value) {
            addCriterion("COD_AREA <=", value, "codArea");
            return (Criteria) this;
        }

        public Criteria andCodAreaLike(String value) {
            addCriterion("COD_AREA like", value, "codArea");
            return (Criteria) this;
        }

        public Criteria andCodAreaNotLike(String value) {
            addCriterion("COD_AREA not like", value, "codArea");
            return (Criteria) this;
        }

        public Criteria andCodAreaIn(List<String> values) {
            addCriterion("COD_AREA in", values, "codArea");
            return (Criteria) this;
        }

        public Criteria andCodAreaNotIn(List<String> values) {
            addCriterion("COD_AREA not in", values, "codArea");
            return (Criteria) this;
        }

        public Criteria andCodAreaBetween(String value1, String value2) {
            addCriterion("COD_AREA between", value1, value2, "codArea");
            return (Criteria) this;
        }

        public Criteria andCodAreaNotBetween(String value1, String value2) {
            addCriterion("COD_AREA not between", value1, value2, "codArea");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table NAF6.ARGECAN
     *
     * @mbggenerated do_not_delete_during_merge Tue Apr 21 12:41:59 COT 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table NAF6.ARGECAN
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}