package com.fi.crm.campaigns.persistence.model;

import java.util.ArrayList;
import java.util.List;

public class ArgetidExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table NAF6.ARGETID
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table NAF6.ARGETID
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table NAF6.ARGETID
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NAF6.ARGETID
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public ArgetidExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NAF6.ARGETID
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NAF6.ARGETID
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NAF6.ARGETID
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NAF6.ARGETID
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NAF6.ARGETID
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NAF6.ARGETID
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NAF6.ARGETID
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NAF6.ARGETID
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NAF6.ARGETID
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NAF6.ARGETID
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table NAF6.ARGETID
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCodigoIsNull() {
            addCriterion("CODIGO is null");
            return (Criteria) this;
        }

        public Criteria andCodigoIsNotNull() {
            addCriterion("CODIGO is not null");
            return (Criteria) this;
        }

        public Criteria andCodigoEqualTo(String value) {
            addCriterion("CODIGO =", value, "codigo");
            return (Criteria) this;
        }

        public Criteria andCodigoNotEqualTo(String value) {
            addCriterion("CODIGO <>", value, "codigo");
            return (Criteria) this;
        }

        public Criteria andCodigoGreaterThan(String value) {
            addCriterion("CODIGO >", value, "codigo");
            return (Criteria) this;
        }

        public Criteria andCodigoGreaterThanOrEqualTo(String value) {
            addCriterion("CODIGO >=", value, "codigo");
            return (Criteria) this;
        }

        public Criteria andCodigoLessThan(String value) {
            addCriterion("CODIGO <", value, "codigo");
            return (Criteria) this;
        }

        public Criteria andCodigoLessThanOrEqualTo(String value) {
            addCriterion("CODIGO <=", value, "codigo");
            return (Criteria) this;
        }

        public Criteria andCodigoLike(String value) {
            addCriterion("CODIGO like", value, "codigo");
            return (Criteria) this;
        }

        public Criteria andCodigoNotLike(String value) {
            addCriterion("CODIGO not like", value, "codigo");
            return (Criteria) this;
        }

        public Criteria andCodigoIn(List<String> values) {
            addCriterion("CODIGO in", values, "codigo");
            return (Criteria) this;
        }

        public Criteria andCodigoNotIn(List<String> values) {
            addCriterion("CODIGO not in", values, "codigo");
            return (Criteria) this;
        }

        public Criteria andCodigoBetween(String value1, String value2) {
            addCriterion("CODIGO between", value1, value2, "codigo");
            return (Criteria) this;
        }

        public Criteria andCodigoNotBetween(String value1, String value2) {
            addCriterion("CODIGO not between", value1, value2, "codigo");
            return (Criteria) this;
        }

        public Criteria andDescripcionIsNull() {
            addCriterion("DESCRIPCION is null");
            return (Criteria) this;
        }

        public Criteria andDescripcionIsNotNull() {
            addCriterion("DESCRIPCION is not null");
            return (Criteria) this;
        }

        public Criteria andDescripcionEqualTo(String value) {
            addCriterion("DESCRIPCION =", value, "descripcion");
            return (Criteria) this;
        }

        public Criteria andDescripcionNotEqualTo(String value) {
            addCriterion("DESCRIPCION <>", value, "descripcion");
            return (Criteria) this;
        }

        public Criteria andDescripcionGreaterThan(String value) {
            addCriterion("DESCRIPCION >", value, "descripcion");
            return (Criteria) this;
        }

        public Criteria andDescripcionGreaterThanOrEqualTo(String value) {
            addCriterion("DESCRIPCION >=", value, "descripcion");
            return (Criteria) this;
        }

        public Criteria andDescripcionLessThan(String value) {
            addCriterion("DESCRIPCION <", value, "descripcion");
            return (Criteria) this;
        }

        public Criteria andDescripcionLessThanOrEqualTo(String value) {
            addCriterion("DESCRIPCION <=", value, "descripcion");
            return (Criteria) this;
        }

        public Criteria andDescripcionLike(String value) {
            addCriterion("DESCRIPCION like", value, "descripcion");
            return (Criteria) this;
        }

        public Criteria andDescripcionNotLike(String value) {
            addCriterion("DESCRIPCION not like", value, "descripcion");
            return (Criteria) this;
        }

        public Criteria andDescripcionIn(List<String> values) {
            addCriterion("DESCRIPCION in", values, "descripcion");
            return (Criteria) this;
        }

        public Criteria andDescripcionNotIn(List<String> values) {
            addCriterion("DESCRIPCION not in", values, "descripcion");
            return (Criteria) this;
        }

        public Criteria andDescripcionBetween(String value1, String value2) {
            addCriterion("DESCRIPCION between", value1, value2, "descripcion");
            return (Criteria) this;
        }

        public Criteria andDescripcionNotBetween(String value1, String value2) {
            addCriterion("DESCRIPCION not between", value1, value2, "descripcion");
            return (Criteria) this;
        }

        public Criteria andEtiquetaIsNull() {
            addCriterion("ETIQUETA is null");
            return (Criteria) this;
        }

        public Criteria andEtiquetaIsNotNull() {
            addCriterion("ETIQUETA is not null");
            return (Criteria) this;
        }

        public Criteria andEtiquetaEqualTo(String value) {
            addCriterion("ETIQUETA =", value, "etiqueta");
            return (Criteria) this;
        }

        public Criteria andEtiquetaNotEqualTo(String value) {
            addCriterion("ETIQUETA <>", value, "etiqueta");
            return (Criteria) this;
        }

        public Criteria andEtiquetaGreaterThan(String value) {
            addCriterion("ETIQUETA >", value, "etiqueta");
            return (Criteria) this;
        }

        public Criteria andEtiquetaGreaterThanOrEqualTo(String value) {
            addCriterion("ETIQUETA >=", value, "etiqueta");
            return (Criteria) this;
        }

        public Criteria andEtiquetaLessThan(String value) {
            addCriterion("ETIQUETA <", value, "etiqueta");
            return (Criteria) this;
        }

        public Criteria andEtiquetaLessThanOrEqualTo(String value) {
            addCriterion("ETIQUETA <=", value, "etiqueta");
            return (Criteria) this;
        }

        public Criteria andEtiquetaLike(String value) {
            addCriterion("ETIQUETA like", value, "etiqueta");
            return (Criteria) this;
        }

        public Criteria andEtiquetaNotLike(String value) {
            addCriterion("ETIQUETA not like", value, "etiqueta");
            return (Criteria) this;
        }

        public Criteria andEtiquetaIn(List<String> values) {
            addCriterion("ETIQUETA in", values, "etiqueta");
            return (Criteria) this;
        }

        public Criteria andEtiquetaNotIn(List<String> values) {
            addCriterion("ETIQUETA not in", values, "etiqueta");
            return (Criteria) this;
        }

        public Criteria andEtiquetaBetween(String value1, String value2) {
            addCriterion("ETIQUETA between", value1, value2, "etiqueta");
            return (Criteria) this;
        }

        public Criteria andEtiquetaNotBetween(String value1, String value2) {
            addCriterion("ETIQUETA not between", value1, value2, "etiqueta");
            return (Criteria) this;
        }

        public Criteria andFormatoIsNull() {
            addCriterion("FORMATO is null");
            return (Criteria) this;
        }

        public Criteria andFormatoIsNotNull() {
            addCriterion("FORMATO is not null");
            return (Criteria) this;
        }

        public Criteria andFormatoEqualTo(String value) {
            addCriterion("FORMATO =", value, "formato");
            return (Criteria) this;
        }

        public Criteria andFormatoNotEqualTo(String value) {
            addCriterion("FORMATO <>", value, "formato");
            return (Criteria) this;
        }

        public Criteria andFormatoGreaterThan(String value) {
            addCriterion("FORMATO >", value, "formato");
            return (Criteria) this;
        }

        public Criteria andFormatoGreaterThanOrEqualTo(String value) {
            addCriterion("FORMATO >=", value, "formato");
            return (Criteria) this;
        }

        public Criteria andFormatoLessThan(String value) {
            addCriterion("FORMATO <", value, "formato");
            return (Criteria) this;
        }

        public Criteria andFormatoLessThanOrEqualTo(String value) {
            addCriterion("FORMATO <=", value, "formato");
            return (Criteria) this;
        }

        public Criteria andFormatoLike(String value) {
            addCriterion("FORMATO like", value, "formato");
            return (Criteria) this;
        }

        public Criteria andFormatoNotLike(String value) {
            addCriterion("FORMATO not like", value, "formato");
            return (Criteria) this;
        }

        public Criteria andFormatoIn(List<String> values) {
            addCriterion("FORMATO in", values, "formato");
            return (Criteria) this;
        }

        public Criteria andFormatoNotIn(List<String> values) {
            addCriterion("FORMATO not in", values, "formato");
            return (Criteria) this;
        }

        public Criteria andFormatoBetween(String value1, String value2) {
            addCriterion("FORMATO between", value1, value2, "formato");
            return (Criteria) this;
        }

        public Criteria andFormatoNotBetween(String value1, String value2) {
            addCriterion("FORMATO not between", value1, value2, "formato");
            return (Criteria) this;
        }

        public Criteria andDigitoVerifIsNull() {
            addCriterion("DIGITO_VERIF is null");
            return (Criteria) this;
        }

        public Criteria andDigitoVerifIsNotNull() {
            addCriterion("DIGITO_VERIF is not null");
            return (Criteria) this;
        }

        public Criteria andDigitoVerifEqualTo(Short value) {
            addCriterion("DIGITO_VERIF =", value, "digitoVerif");
            return (Criteria) this;
        }

        public Criteria andDigitoVerifNotEqualTo(Short value) {
            addCriterion("DIGITO_VERIF <>", value, "digitoVerif");
            return (Criteria) this;
        }

        public Criteria andDigitoVerifGreaterThan(Short value) {
            addCriterion("DIGITO_VERIF >", value, "digitoVerif");
            return (Criteria) this;
        }

        public Criteria andDigitoVerifGreaterThanOrEqualTo(Short value) {
            addCriterion("DIGITO_VERIF >=", value, "digitoVerif");
            return (Criteria) this;
        }

        public Criteria andDigitoVerifLessThan(Short value) {
            addCriterion("DIGITO_VERIF <", value, "digitoVerif");
            return (Criteria) this;
        }

        public Criteria andDigitoVerifLessThanOrEqualTo(Short value) {
            addCriterion("DIGITO_VERIF <=", value, "digitoVerif");
            return (Criteria) this;
        }

        public Criteria andDigitoVerifIn(List<Short> values) {
            addCriterion("DIGITO_VERIF in", values, "digitoVerif");
            return (Criteria) this;
        }

        public Criteria andDigitoVerifNotIn(List<Short> values) {
            addCriterion("DIGITO_VERIF not in", values, "digitoVerif");
            return (Criteria) this;
        }

        public Criteria andDigitoVerifBetween(Short value1, Short value2) {
            addCriterion("DIGITO_VERIF between", value1, value2, "digitoVerif");
            return (Criteria) this;
        }

        public Criteria andDigitoVerifNotBetween(Short value1, Short value2) {
            addCriterion("DIGITO_VERIF not between", value1, value2, "digitoVerif");
            return (Criteria) this;
        }

        public Criteria andPrefijoIdInsIsNull() {
            addCriterion("PREFIJO_ID_INS is null");
            return (Criteria) this;
        }

        public Criteria andPrefijoIdInsIsNotNull() {
            addCriterion("PREFIJO_ID_INS is not null");
            return (Criteria) this;
        }

        public Criteria andPrefijoIdInsEqualTo(String value) {
            addCriterion("PREFIJO_ID_INS =", value, "prefijoIdIns");
            return (Criteria) this;
        }

        public Criteria andPrefijoIdInsNotEqualTo(String value) {
            addCriterion("PREFIJO_ID_INS <>", value, "prefijoIdIns");
            return (Criteria) this;
        }

        public Criteria andPrefijoIdInsGreaterThan(String value) {
            addCriterion("PREFIJO_ID_INS >", value, "prefijoIdIns");
            return (Criteria) this;
        }

        public Criteria andPrefijoIdInsGreaterThanOrEqualTo(String value) {
            addCriterion("PREFIJO_ID_INS >=", value, "prefijoIdIns");
            return (Criteria) this;
        }

        public Criteria andPrefijoIdInsLessThan(String value) {
            addCriterion("PREFIJO_ID_INS <", value, "prefijoIdIns");
            return (Criteria) this;
        }

        public Criteria andPrefijoIdInsLessThanOrEqualTo(String value) {
            addCriterion("PREFIJO_ID_INS <=", value, "prefijoIdIns");
            return (Criteria) this;
        }

        public Criteria andPrefijoIdInsLike(String value) {
            addCriterion("PREFIJO_ID_INS like", value, "prefijoIdIns");
            return (Criteria) this;
        }

        public Criteria andPrefijoIdInsNotLike(String value) {
            addCriterion("PREFIJO_ID_INS not like", value, "prefijoIdIns");
            return (Criteria) this;
        }

        public Criteria andPrefijoIdInsIn(List<String> values) {
            addCriterion("PREFIJO_ID_INS in", values, "prefijoIdIns");
            return (Criteria) this;
        }

        public Criteria andPrefijoIdInsNotIn(List<String> values) {
            addCriterion("PREFIJO_ID_INS not in", values, "prefijoIdIns");
            return (Criteria) this;
        }

        public Criteria andPrefijoIdInsBetween(String value1, String value2) {
            addCriterion("PREFIJO_ID_INS between", value1, value2, "prefijoIdIns");
            return (Criteria) this;
        }

        public Criteria andPrefijoIdInsNotBetween(String value1, String value2) {
            addCriterion("PREFIJO_ID_INS not between", value1, value2, "prefijoIdIns");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table NAF6.ARGETID
     *
     * @mbggenerated do_not_delete_during_merge Tue Apr 21 12:41:59 COT 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table NAF6.ARGETID
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}