package com.fi.crm.campaigns.persistence.model;

public class ArindaKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NAF6.ARINDA.NO_CIA
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    private String noCia;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NAF6.ARINDA.NO_ARTI
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    private String noArti;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NAF6.ARINDA.NO_CIA
     *
     * @return the value of NAF6.ARINDA.NO_CIA
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public String getNoCia() {
        return noCia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NAF6.ARINDA.NO_CIA
     *
     * @param noCia the value for NAF6.ARINDA.NO_CIA
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public void setNoCia(String noCia) {
        this.noCia = noCia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NAF6.ARINDA.NO_ARTI
     *
     * @return the value of NAF6.ARINDA.NO_ARTI
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public String getNoArti() {
        return noArti;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NAF6.ARINDA.NO_ARTI
     *
     * @param noArti the value for NAF6.ARINDA.NO_ARTI
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public void setNoArti(String noArti) {
        this.noArti = noArti;
    }
}