package com.fi.crm.campaigns.persistence.model;

public class Arunneg extends ArunnegKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NAF6.ARUNNEG.NOMBRE
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    private String nombre;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NAF6.ARUNNEG.ACTIVO
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    private String activo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NAF6.ARUNNEG.NOMBRE
     *
     * @return the value of NAF6.ARUNNEG.NOMBRE
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public String getNombre() {
        return nombre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NAF6.ARUNNEG.NOMBRE
     *
     * @param nombre the value for NAF6.ARUNNEG.NOMBRE
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NAF6.ARUNNEG.ACTIVO
     *
     * @return the value of NAF6.ARUNNEG.ACTIVO
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public String getActivo() {
        return activo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NAF6.ARUNNEG.ACTIVO
     *
     * @param activo the value for NAF6.ARUNNEG.ACTIVO
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public void setActivo(String activo) {
        this.activo = activo;
    }
}