package com.fi.crm.campaigns.persistence.model;

public class CpAutor {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CAMPAIGNS.CP_AUTOR.AUTOR_ID
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    private Integer autorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CAMPAIGNS.CP_AUTOR.NOMBRES
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    private String nombres;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CAMPAIGNS.CP_AUTOR.APELLIDO1
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    private String apellido1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CAMPAIGNS.CP_AUTOR.APELLIDO2
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    private String apellido2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CAMPAIGNS.CP_AUTOR.CORREO
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    private String correo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CAMPAIGNS.CP_AUTOR.STATUS
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CAMPAIGNS.CP_AUTOR.COD_USUARIO
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    private String codUsuario;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CAMPAIGNS.CP_AUTOR.AUTOR_ID
     *
     * @return the value of CAMPAIGNS.CP_AUTOR.AUTOR_ID
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public Integer getAutorId() {
        return autorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CAMPAIGNS.CP_AUTOR.AUTOR_ID
     *
     * @param autorId the value for CAMPAIGNS.CP_AUTOR.AUTOR_ID
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public void setAutorId(Integer autorId) {
        this.autorId = autorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CAMPAIGNS.CP_AUTOR.NOMBRES
     *
     * @return the value of CAMPAIGNS.CP_AUTOR.NOMBRES
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public String getNombres() {
        return nombres;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CAMPAIGNS.CP_AUTOR.NOMBRES
     *
     * @param nombres the value for CAMPAIGNS.CP_AUTOR.NOMBRES
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CAMPAIGNS.CP_AUTOR.APELLIDO1
     *
     * @return the value of CAMPAIGNS.CP_AUTOR.APELLIDO1
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public String getApellido1() {
        return apellido1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CAMPAIGNS.CP_AUTOR.APELLIDO1
     *
     * @param apellido1 the value for CAMPAIGNS.CP_AUTOR.APELLIDO1
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public void setApellido1(String apellido1) {
        this.apellido1 = apellido1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CAMPAIGNS.CP_AUTOR.APELLIDO2
     *
     * @return the value of CAMPAIGNS.CP_AUTOR.APELLIDO2
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public String getApellido2() {
        return apellido2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CAMPAIGNS.CP_AUTOR.APELLIDO2
     *
     * @param apellido2 the value for CAMPAIGNS.CP_AUTOR.APELLIDO2
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public void setApellido2(String apellido2) {
        this.apellido2 = apellido2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CAMPAIGNS.CP_AUTOR.CORREO
     *
     * @return the value of CAMPAIGNS.CP_AUTOR.CORREO
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public String getCorreo() {
        return correo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CAMPAIGNS.CP_AUTOR.CORREO
     *
     * @param correo the value for CAMPAIGNS.CP_AUTOR.CORREO
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public void setCorreo(String correo) {
        this.correo = correo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CAMPAIGNS.CP_AUTOR.STATUS
     *
     * @return the value of CAMPAIGNS.CP_AUTOR.STATUS
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CAMPAIGNS.CP_AUTOR.STATUS
     *
     * @param status the value for CAMPAIGNS.CP_AUTOR.STATUS
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CAMPAIGNS.CP_AUTOR.COD_USUARIO
     *
     * @return the value of CAMPAIGNS.CP_AUTOR.COD_USUARIO
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public String getCodUsuario() {
        return codUsuario;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CAMPAIGNS.CP_AUTOR.COD_USUARIO
     *
     * @param codUsuario the value for CAMPAIGNS.CP_AUTOR.COD_USUARIO
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public void setCodUsuario(String codUsuario) {
        this.codUsuario = codUsuario;
    }
}