package com.fi.crm.campaigns.persistence.model;

import java.util.Date;

public class CpAudit {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CAMPAIGNS.CP_AUDIT.AUDIT_ID
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    private Integer auditId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CAMPAIGNS.CP_AUDIT.FECHA
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    private Date fecha;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CAMPAIGNS.CP_AUDIT.TIPO_EVENTO
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    private String tipoEvento;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CAMPAIGNS.CP_AUDIT.COD_USUARIO
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    private String codUsuario;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CAMPAIGNS.CP_AUDIT.TERMINAL
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    private String terminal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CAMPAIGNS.CP_AUDIT.ESTADO
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    private String estado;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CAMPAIGNS.CP_AUDIT.ENTIDAD_ID
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    private Integer entidadId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CAMPAIGNS.CP_AUDIT.AUDIT_ID
     *
     * @return the value of CAMPAIGNS.CP_AUDIT.AUDIT_ID
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public Integer getAuditId() {
        return auditId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CAMPAIGNS.CP_AUDIT.AUDIT_ID
     *
     * @param auditId the value for CAMPAIGNS.CP_AUDIT.AUDIT_ID
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public void setAuditId(Integer auditId) {
        this.auditId = auditId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CAMPAIGNS.CP_AUDIT.FECHA
     *
     * @return the value of CAMPAIGNS.CP_AUDIT.FECHA
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public Date getFecha() {
        return fecha;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CAMPAIGNS.CP_AUDIT.FECHA
     *
     * @param fecha the value for CAMPAIGNS.CP_AUDIT.FECHA
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CAMPAIGNS.CP_AUDIT.TIPO_EVENTO
     *
     * @return the value of CAMPAIGNS.CP_AUDIT.TIPO_EVENTO
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public String getTipoEvento() {
        return tipoEvento;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CAMPAIGNS.CP_AUDIT.TIPO_EVENTO
     *
     * @param tipoEvento the value for CAMPAIGNS.CP_AUDIT.TIPO_EVENTO
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public void setTipoEvento(String tipoEvento) {
        this.tipoEvento = tipoEvento;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CAMPAIGNS.CP_AUDIT.COD_USUARIO
     *
     * @return the value of CAMPAIGNS.CP_AUDIT.COD_USUARIO
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public String getCodUsuario() {
        return codUsuario;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CAMPAIGNS.CP_AUDIT.COD_USUARIO
     *
     * @param codUsuario the value for CAMPAIGNS.CP_AUDIT.COD_USUARIO
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public void setCodUsuario(String codUsuario) {
        this.codUsuario = codUsuario;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CAMPAIGNS.CP_AUDIT.TERMINAL
     *
     * @return the value of CAMPAIGNS.CP_AUDIT.TERMINAL
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public String getTerminal() {
        return terminal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CAMPAIGNS.CP_AUDIT.TERMINAL
     *
     * @param terminal the value for CAMPAIGNS.CP_AUDIT.TERMINAL
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public void setTerminal(String terminal) {
        this.terminal = terminal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CAMPAIGNS.CP_AUDIT.ESTADO
     *
     * @return the value of CAMPAIGNS.CP_AUDIT.ESTADO
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public String getEstado() {
        return estado;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CAMPAIGNS.CP_AUDIT.ESTADO
     *
     * @param estado the value for CAMPAIGNS.CP_AUDIT.ESTADO
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public void setEstado(String estado) {
        this.estado = estado;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CAMPAIGNS.CP_AUDIT.ENTIDAD_ID
     *
     * @return the value of CAMPAIGNS.CP_AUDIT.ENTIDAD_ID
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public Integer getEntidadId() {
        return entidadId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CAMPAIGNS.CP_AUDIT.ENTIDAD_ID
     *
     * @param entidadId the value for CAMPAIGNS.CP_AUDIT.ENTIDAD_ID
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public void setEntidadId(Integer entidadId) {
        this.entidadId = entidadId;
    }
}