package com.fi.crm.campaigns.persistence.model;

import java.util.Date;

public class CpCampania {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CAMPAIGNS.CP_CAMPANIA.CAMPANIA_ID
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    private Integer campaniaId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CAMPAIGNS.CP_CAMPANIA.NOMBRE
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    private String nombre;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CAMPAIGNS.CP_CAMPANIA.DESCRIPCION
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    private String descripcion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CAMPAIGNS.CP_CAMPANIA.AUTOR_ID
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    private Integer autorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CAMPAIGNS.CP_CAMPANIA.TIPO
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    private String tipo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CAMPAIGNS.CP_CAMPANIA.ESTADO
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    private String estado;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CAMPAIGNS.CP_CAMPANIA.INICIO_CAMPANIA
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    private Date inicioCampania;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CAMPAIGNS.CP_CAMPANIA.FIN_CAMPANIA
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    private Date finCampania;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CAMPAIGNS.CP_CAMPANIA.INICIO_EVENTO
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    private Date inicioEvento;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CAMPAIGNS.CP_CAMPANIA.FIN_EVENTO
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    private Date finEvento;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CAMPAIGNS.CP_CAMPANIA.ASUNTO
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    private String asunto;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CAMPAIGNS.CP_CAMPANIA.MENSAJE
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    private String mensaje;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CAMPAIGNS.CP_CAMPANIA.MARCACION_AUTOMATICA
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    private String marcacionAutomatica;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CAMPAIGNS.CP_CAMPANIA.APROBADOR
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    private String aprobador;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CAMPAIGNS.CP_CAMPANIA.CREADOR
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    private String creador;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CAMPAIGNS.CP_CAMPANIA.NO_CIA
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    private String noCia;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CAMPAIGNS.CP_CAMPANIA.CENTRO
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    private String centro;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CAMPAIGNS.CP_CAMPANIA.NO_CIA_UNID_NEG
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    private String noCiaUnidNeg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CAMPAIGNS.CP_CAMPANIA.UNIDAD_NEGOCIO
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    private String unidadNegocio;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CAMPAIGNS.CP_CAMPANIA.DOMINIO
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    private String dominio;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CAMPAIGNS.CP_CAMPANIA.MARCA_CODIGO
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    private String marcaCodigo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CAMPAIGNS.CP_CAMPANIA.NO_ARTI
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    private String noArti;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CAMPAIGNS.CP_CAMPANIA.JAMES_ANTERIOR
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    private Integer jamesAnterior;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CAMPAIGNS.CP_CAMPANIA.CAMPANIA_ID
     *
     * @return the value of CAMPAIGNS.CP_CAMPANIA.CAMPANIA_ID
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public Integer getCampaniaId() {
        return campaniaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CAMPAIGNS.CP_CAMPANIA.CAMPANIA_ID
     *
     * @param campaniaId the value for CAMPAIGNS.CP_CAMPANIA.CAMPANIA_ID
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public void setCampaniaId(Integer campaniaId) {
        this.campaniaId = campaniaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CAMPAIGNS.CP_CAMPANIA.NOMBRE
     *
     * @return the value of CAMPAIGNS.CP_CAMPANIA.NOMBRE
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public String getNombre() {
        return nombre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CAMPAIGNS.CP_CAMPANIA.NOMBRE
     *
     * @param nombre the value for CAMPAIGNS.CP_CAMPANIA.NOMBRE
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CAMPAIGNS.CP_CAMPANIA.DESCRIPCION
     *
     * @return the value of CAMPAIGNS.CP_CAMPANIA.DESCRIPCION
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public String getDescripcion() {
        return descripcion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CAMPAIGNS.CP_CAMPANIA.DESCRIPCION
     *
     * @param descripcion the value for CAMPAIGNS.CP_CAMPANIA.DESCRIPCION
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CAMPAIGNS.CP_CAMPANIA.AUTOR_ID
     *
     * @return the value of CAMPAIGNS.CP_CAMPANIA.AUTOR_ID
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public Integer getAutorId() {
        return autorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CAMPAIGNS.CP_CAMPANIA.AUTOR_ID
     *
     * @param autorId the value for CAMPAIGNS.CP_CAMPANIA.AUTOR_ID
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public void setAutorId(Integer autorId) {
        this.autorId = autorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CAMPAIGNS.CP_CAMPANIA.TIPO
     *
     * @return the value of CAMPAIGNS.CP_CAMPANIA.TIPO
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public String getTipo() {
        return tipo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CAMPAIGNS.CP_CAMPANIA.TIPO
     *
     * @param tipo the value for CAMPAIGNS.CP_CAMPANIA.TIPO
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CAMPAIGNS.CP_CAMPANIA.ESTADO
     *
     * @return the value of CAMPAIGNS.CP_CAMPANIA.ESTADO
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public String getEstado() {
        return estado;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CAMPAIGNS.CP_CAMPANIA.ESTADO
     *
     * @param estado the value for CAMPAIGNS.CP_CAMPANIA.ESTADO
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public void setEstado(String estado) {
        this.estado = estado;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CAMPAIGNS.CP_CAMPANIA.INICIO_CAMPANIA
     *
     * @return the value of CAMPAIGNS.CP_CAMPANIA.INICIO_CAMPANIA
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public Date getInicioCampania() {
        return inicioCampania;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CAMPAIGNS.CP_CAMPANIA.INICIO_CAMPANIA
     *
     * @param inicioCampania the value for CAMPAIGNS.CP_CAMPANIA.INICIO_CAMPANIA
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public void setInicioCampania(Date inicioCampania) {
        this.inicioCampania = inicioCampania;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CAMPAIGNS.CP_CAMPANIA.FIN_CAMPANIA
     *
     * @return the value of CAMPAIGNS.CP_CAMPANIA.FIN_CAMPANIA
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public Date getFinCampania() {
        return finCampania;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CAMPAIGNS.CP_CAMPANIA.FIN_CAMPANIA
     *
     * @param finCampania the value for CAMPAIGNS.CP_CAMPANIA.FIN_CAMPANIA
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public void setFinCampania(Date finCampania) {
        this.finCampania = finCampania;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CAMPAIGNS.CP_CAMPANIA.INICIO_EVENTO
     *
     * @return the value of CAMPAIGNS.CP_CAMPANIA.INICIO_EVENTO
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public Date getInicioEvento() {
        return inicioEvento;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CAMPAIGNS.CP_CAMPANIA.INICIO_EVENTO
     *
     * @param inicioEvento the value for CAMPAIGNS.CP_CAMPANIA.INICIO_EVENTO
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public void setInicioEvento(Date inicioEvento) {
        this.inicioEvento = inicioEvento;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CAMPAIGNS.CP_CAMPANIA.FIN_EVENTO
     *
     * @return the value of CAMPAIGNS.CP_CAMPANIA.FIN_EVENTO
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public Date getFinEvento() {
        return finEvento;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CAMPAIGNS.CP_CAMPANIA.FIN_EVENTO
     *
     * @param finEvento the value for CAMPAIGNS.CP_CAMPANIA.FIN_EVENTO
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public void setFinEvento(Date finEvento) {
        this.finEvento = finEvento;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CAMPAIGNS.CP_CAMPANIA.ASUNTO
     *
     * @return the value of CAMPAIGNS.CP_CAMPANIA.ASUNTO
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public String getAsunto() {
        return asunto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CAMPAIGNS.CP_CAMPANIA.ASUNTO
     *
     * @param asunto the value for CAMPAIGNS.CP_CAMPANIA.ASUNTO
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public void setAsunto(String asunto) {
        this.asunto = asunto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CAMPAIGNS.CP_CAMPANIA.MENSAJE
     *
     * @return the value of CAMPAIGNS.CP_CAMPANIA.MENSAJE
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public String getMensaje() {
        return mensaje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CAMPAIGNS.CP_CAMPANIA.MENSAJE
     *
     * @param mensaje the value for CAMPAIGNS.CP_CAMPANIA.MENSAJE
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public void setMensaje(String mensaje) {
        this.mensaje = mensaje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CAMPAIGNS.CP_CAMPANIA.MARCACION_AUTOMATICA
     *
     * @return the value of CAMPAIGNS.CP_CAMPANIA.MARCACION_AUTOMATICA
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public String getMarcacionAutomatica() {
        return marcacionAutomatica;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CAMPAIGNS.CP_CAMPANIA.MARCACION_AUTOMATICA
     *
     * @param marcacionAutomatica the value for CAMPAIGNS.CP_CAMPANIA.MARCACION_AUTOMATICA
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public void setMarcacionAutomatica(String marcacionAutomatica) {
        this.marcacionAutomatica = marcacionAutomatica;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CAMPAIGNS.CP_CAMPANIA.APROBADOR
     *
     * @return the value of CAMPAIGNS.CP_CAMPANIA.APROBADOR
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public String getAprobador() {
        return aprobador;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CAMPAIGNS.CP_CAMPANIA.APROBADOR
     *
     * @param aprobador the value for CAMPAIGNS.CP_CAMPANIA.APROBADOR
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public void setAprobador(String aprobador) {
        this.aprobador = aprobador;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CAMPAIGNS.CP_CAMPANIA.CREADOR
     *
     * @return the value of CAMPAIGNS.CP_CAMPANIA.CREADOR
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public String getCreador() {
        return creador;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CAMPAIGNS.CP_CAMPANIA.CREADOR
     *
     * @param creador the value for CAMPAIGNS.CP_CAMPANIA.CREADOR
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public void setCreador(String creador) {
        this.creador = creador;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CAMPAIGNS.CP_CAMPANIA.NO_CIA
     *
     * @return the value of CAMPAIGNS.CP_CAMPANIA.NO_CIA
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public String getNoCia() {
        return noCia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CAMPAIGNS.CP_CAMPANIA.NO_CIA
     *
     * @param noCia the value for CAMPAIGNS.CP_CAMPANIA.NO_CIA
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public void setNoCia(String noCia) {
        this.noCia = noCia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CAMPAIGNS.CP_CAMPANIA.CENTRO
     *
     * @return the value of CAMPAIGNS.CP_CAMPANIA.CENTRO
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public String getCentro() {
        return centro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CAMPAIGNS.CP_CAMPANIA.CENTRO
     *
     * @param centro the value for CAMPAIGNS.CP_CAMPANIA.CENTRO
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public void setCentro(String centro) {
        this.centro = centro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CAMPAIGNS.CP_CAMPANIA.NO_CIA_UNID_NEG
     *
     * @return the value of CAMPAIGNS.CP_CAMPANIA.NO_CIA_UNID_NEG
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public String getNoCiaUnidNeg() {
        return noCiaUnidNeg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CAMPAIGNS.CP_CAMPANIA.NO_CIA_UNID_NEG
     *
     * @param noCiaUnidNeg the value for CAMPAIGNS.CP_CAMPANIA.NO_CIA_UNID_NEG
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public void setNoCiaUnidNeg(String noCiaUnidNeg) {
        this.noCiaUnidNeg = noCiaUnidNeg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CAMPAIGNS.CP_CAMPANIA.UNIDAD_NEGOCIO
     *
     * @return the value of CAMPAIGNS.CP_CAMPANIA.UNIDAD_NEGOCIO
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public String getUnidadNegocio() {
        return unidadNegocio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CAMPAIGNS.CP_CAMPANIA.UNIDAD_NEGOCIO
     *
     * @param unidadNegocio the value for CAMPAIGNS.CP_CAMPANIA.UNIDAD_NEGOCIO
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public void setUnidadNegocio(String unidadNegocio) {
        this.unidadNegocio = unidadNegocio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CAMPAIGNS.CP_CAMPANIA.DOMINIO
     *
     * @return the value of CAMPAIGNS.CP_CAMPANIA.DOMINIO
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public String getDominio() {
        return dominio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CAMPAIGNS.CP_CAMPANIA.DOMINIO
     *
     * @param dominio the value for CAMPAIGNS.CP_CAMPANIA.DOMINIO
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public void setDominio(String dominio) {
        this.dominio = dominio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CAMPAIGNS.CP_CAMPANIA.MARCA_CODIGO
     *
     * @return the value of CAMPAIGNS.CP_CAMPANIA.MARCA_CODIGO
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public String getMarcaCodigo() {
        return marcaCodigo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CAMPAIGNS.CP_CAMPANIA.MARCA_CODIGO
     *
     * @param marcaCodigo the value for CAMPAIGNS.CP_CAMPANIA.MARCA_CODIGO
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public void setMarcaCodigo(String marcaCodigo) {
        this.marcaCodigo = marcaCodigo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CAMPAIGNS.CP_CAMPANIA.NO_ARTI
     *
     * @return the value of CAMPAIGNS.CP_CAMPANIA.NO_ARTI
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public String getNoArti() {
        return noArti;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CAMPAIGNS.CP_CAMPANIA.NO_ARTI
     *
     * @param noArti the value for CAMPAIGNS.CP_CAMPANIA.NO_ARTI
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public void setNoArti(String noArti) {
        this.noArti = noArti;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CAMPAIGNS.CP_CAMPANIA.JAMES_ANTERIOR
     *
     * @return the value of CAMPAIGNS.CP_CAMPANIA.JAMES_ANTERIOR
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public Integer getJamesAnterior() {
        return jamesAnterior;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CAMPAIGNS.CP_CAMPANIA.JAMES_ANTERIOR
     *
     * @param jamesAnterior the value for CAMPAIGNS.CP_CAMPANIA.JAMES_ANTERIOR
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public void setJamesAnterior(Integer jamesAnterior) {
        this.jamesAnterior = jamesAnterior;
    }
}