package com.fi.crm.campaigns.persistence.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class CpClienteExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table CAMPAIGNS.CP_CLIENTE
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table CAMPAIGNS.CP_CLIENTE
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table CAMPAIGNS.CP_CLIENTE
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAMPAIGNS.CP_CLIENTE
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public CpClienteExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAMPAIGNS.CP_CLIENTE
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAMPAIGNS.CP_CLIENTE
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAMPAIGNS.CP_CLIENTE
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAMPAIGNS.CP_CLIENTE
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAMPAIGNS.CP_CLIENTE
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAMPAIGNS.CP_CLIENTE
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAMPAIGNS.CP_CLIENTE
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAMPAIGNS.CP_CLIENTE
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAMPAIGNS.CP_CLIENTE
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAMPAIGNS.CP_CLIENTE
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table CAMPAIGNS.CP_CLIENTE
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andClienteIdIsNull() {
            addCriterion("CLIENTE_ID is null");
            return (Criteria) this;
        }

        public Criteria andClienteIdIsNotNull() {
            addCriterion("CLIENTE_ID is not null");
            return (Criteria) this;
        }

        public Criteria andClienteIdEqualTo(Integer value) {
            addCriterion("CLIENTE_ID =", value, "clienteId");
            return (Criteria) this;
        }

        public Criteria andClienteIdNotEqualTo(Integer value) {
            addCriterion("CLIENTE_ID <>", value, "clienteId");
            return (Criteria) this;
        }

        public Criteria andClienteIdGreaterThan(Integer value) {
            addCriterion("CLIENTE_ID >", value, "clienteId");
            return (Criteria) this;
        }

        public Criteria andClienteIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("CLIENTE_ID >=", value, "clienteId");
            return (Criteria) this;
        }

        public Criteria andClienteIdLessThan(Integer value) {
            addCriterion("CLIENTE_ID <", value, "clienteId");
            return (Criteria) this;
        }

        public Criteria andClienteIdLessThanOrEqualTo(Integer value) {
            addCriterion("CLIENTE_ID <=", value, "clienteId");
            return (Criteria) this;
        }

        public Criteria andClienteIdIn(List<Integer> values) {
            addCriterion("CLIENTE_ID in", values, "clienteId");
            return (Criteria) this;
        }

        public Criteria andClienteIdNotIn(List<Integer> values) {
            addCriterion("CLIENTE_ID not in", values, "clienteId");
            return (Criteria) this;
        }

        public Criteria andClienteIdBetween(Integer value1, Integer value2) {
            addCriterion("CLIENTE_ID between", value1, value2, "clienteId");
            return (Criteria) this;
        }

        public Criteria andClienteIdNotBetween(Integer value1, Integer value2) {
            addCriterion("CLIENTE_ID not between", value1, value2, "clienteId");
            return (Criteria) this;
        }

        public Criteria andCampaniaIdIsNull() {
            addCriterion("CAMPANIA_ID is null");
            return (Criteria) this;
        }

        public Criteria andCampaniaIdIsNotNull() {
            addCriterion("CAMPANIA_ID is not null");
            return (Criteria) this;
        }

        public Criteria andCampaniaIdEqualTo(Integer value) {
            addCriterion("CAMPANIA_ID =", value, "campaniaId");
            return (Criteria) this;
        }

        public Criteria andCampaniaIdNotEqualTo(Integer value) {
            addCriterion("CAMPANIA_ID <>", value, "campaniaId");
            return (Criteria) this;
        }

        public Criteria andCampaniaIdGreaterThan(Integer value) {
            addCriterion("CAMPANIA_ID >", value, "campaniaId");
            return (Criteria) this;
        }

        public Criteria andCampaniaIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("CAMPANIA_ID >=", value, "campaniaId");
            return (Criteria) this;
        }

        public Criteria andCampaniaIdLessThan(Integer value) {
            addCriterion("CAMPANIA_ID <", value, "campaniaId");
            return (Criteria) this;
        }

        public Criteria andCampaniaIdLessThanOrEqualTo(Integer value) {
            addCriterion("CAMPANIA_ID <=", value, "campaniaId");
            return (Criteria) this;
        }

        public Criteria andCampaniaIdIn(List<Integer> values) {
            addCriterion("CAMPANIA_ID in", values, "campaniaId");
            return (Criteria) this;
        }

        public Criteria andCampaniaIdNotIn(List<Integer> values) {
            addCriterion("CAMPANIA_ID not in", values, "campaniaId");
            return (Criteria) this;
        }

        public Criteria andCampaniaIdBetween(Integer value1, Integer value2) {
            addCriterion("CAMPANIA_ID between", value1, value2, "campaniaId");
            return (Criteria) this;
        }

        public Criteria andCampaniaIdNotBetween(Integer value1, Integer value2) {
            addCriterion("CAMPANIA_ID not between", value1, value2, "campaniaId");
            return (Criteria) this;
        }

        public Criteria andTipoIdentificacionIsNull() {
            addCriterion("TIPO_IDENTIFICACION is null");
            return (Criteria) this;
        }

        public Criteria andTipoIdentificacionIsNotNull() {
            addCriterion("TIPO_IDENTIFICACION is not null");
            return (Criteria) this;
        }

        public Criteria andTipoIdentificacionEqualTo(String value) {
            addCriterion("TIPO_IDENTIFICACION =", value, "tipoIdentificacion");
            return (Criteria) this;
        }

        public Criteria andTipoIdentificacionNotEqualTo(String value) {
            addCriterion("TIPO_IDENTIFICACION <>", value, "tipoIdentificacion");
            return (Criteria) this;
        }

        public Criteria andTipoIdentificacionGreaterThan(String value) {
            addCriterion("TIPO_IDENTIFICACION >", value, "tipoIdentificacion");
            return (Criteria) this;
        }

        public Criteria andTipoIdentificacionGreaterThanOrEqualTo(String value) {
            addCriterion("TIPO_IDENTIFICACION >=", value, "tipoIdentificacion");
            return (Criteria) this;
        }

        public Criteria andTipoIdentificacionLessThan(String value) {
            addCriterion("TIPO_IDENTIFICACION <", value, "tipoIdentificacion");
            return (Criteria) this;
        }

        public Criteria andTipoIdentificacionLessThanOrEqualTo(String value) {
            addCriterion("TIPO_IDENTIFICACION <=", value, "tipoIdentificacion");
            return (Criteria) this;
        }

        public Criteria andTipoIdentificacionLike(String value) {
            addCriterion("TIPO_IDENTIFICACION like", value, "tipoIdentificacion");
            return (Criteria) this;
        }

        public Criteria andTipoIdentificacionNotLike(String value) {
            addCriterion("TIPO_IDENTIFICACION not like", value, "tipoIdentificacion");
            return (Criteria) this;
        }

        public Criteria andTipoIdentificacionIn(List<String> values) {
            addCriterion("TIPO_IDENTIFICACION in", values, "tipoIdentificacion");
            return (Criteria) this;
        }

        public Criteria andTipoIdentificacionNotIn(List<String> values) {
            addCriterion("TIPO_IDENTIFICACION not in", values, "tipoIdentificacion");
            return (Criteria) this;
        }

        public Criteria andTipoIdentificacionBetween(String value1, String value2) {
            addCriterion("TIPO_IDENTIFICACION between", value1, value2, "tipoIdentificacion");
            return (Criteria) this;
        }

        public Criteria andTipoIdentificacionNotBetween(String value1, String value2) {
            addCriterion("TIPO_IDENTIFICACION not between", value1, value2, "tipoIdentificacion");
            return (Criteria) this;
        }

        public Criteria andIdentificacionIsNull() {
            addCriterion("IDENTIFICACION is null");
            return (Criteria) this;
        }

        public Criteria andIdentificacionIsNotNull() {
            addCriterion("IDENTIFICACION is not null");
            return (Criteria) this;
        }

        public Criteria andIdentificacionEqualTo(String value) {
            addCriterion("IDENTIFICACION =", value, "identificacion");
            return (Criteria) this;
        }

        public Criteria andIdentificacionNotEqualTo(String value) {
            addCriterion("IDENTIFICACION <>", value, "identificacion");
            return (Criteria) this;
        }

        public Criteria andIdentificacionGreaterThan(String value) {
            addCriterion("IDENTIFICACION >", value, "identificacion");
            return (Criteria) this;
        }

        public Criteria andIdentificacionGreaterThanOrEqualTo(String value) {
            addCriterion("IDENTIFICACION >=", value, "identificacion");
            return (Criteria) this;
        }

        public Criteria andIdentificacionLessThan(String value) {
            addCriterion("IDENTIFICACION <", value, "identificacion");
            return (Criteria) this;
        }

        public Criteria andIdentificacionLessThanOrEqualTo(String value) {
            addCriterion("IDENTIFICACION <=", value, "identificacion");
            return (Criteria) this;
        }

        public Criteria andIdentificacionLike(String value) {
            addCriterion("IDENTIFICACION like", value, "identificacion");
            return (Criteria) this;
        }

        public Criteria andIdentificacionNotLike(String value) {
            addCriterion("IDENTIFICACION not like", value, "identificacion");
            return (Criteria) this;
        }

        public Criteria andIdentificacionIn(List<String> values) {
            addCriterion("IDENTIFICACION in", values, "identificacion");
            return (Criteria) this;
        }

        public Criteria andIdentificacionNotIn(List<String> values) {
            addCriterion("IDENTIFICACION not in", values, "identificacion");
            return (Criteria) this;
        }

        public Criteria andIdentificacionBetween(String value1, String value2) {
            addCriterion("IDENTIFICACION between", value1, value2, "identificacion");
            return (Criteria) this;
        }

        public Criteria andIdentificacionNotBetween(String value1, String value2) {
            addCriterion("IDENTIFICACION not between", value1, value2, "identificacion");
            return (Criteria) this;
        }

        public Criteria andNombresIsNull() {
            addCriterion("NOMBRES is null");
            return (Criteria) this;
        }

        public Criteria andNombresIsNotNull() {
            addCriterion("NOMBRES is not null");
            return (Criteria) this;
        }

        public Criteria andNombresEqualTo(String value) {
            addCriterion("NOMBRES =", value, "nombres");
            return (Criteria) this;
        }

        public Criteria andNombresNotEqualTo(String value) {
            addCriterion("NOMBRES <>", value, "nombres");
            return (Criteria) this;
        }

        public Criteria andNombresGreaterThan(String value) {
            addCriterion("NOMBRES >", value, "nombres");
            return (Criteria) this;
        }

        public Criteria andNombresGreaterThanOrEqualTo(String value) {
            addCriterion("NOMBRES >=", value, "nombres");
            return (Criteria) this;
        }

        public Criteria andNombresLessThan(String value) {
            addCriterion("NOMBRES <", value, "nombres");
            return (Criteria) this;
        }

        public Criteria andNombresLessThanOrEqualTo(String value) {
            addCriterion("NOMBRES <=", value, "nombres");
            return (Criteria) this;
        }

        public Criteria andNombresLike(String value) {
            addCriterion("NOMBRES like", value, "nombres");
            return (Criteria) this;
        }

        public Criteria andNombresNotLike(String value) {
            addCriterion("NOMBRES not like", value, "nombres");
            return (Criteria) this;
        }

        public Criteria andNombresIn(List<String> values) {
            addCriterion("NOMBRES in", values, "nombres");
            return (Criteria) this;
        }

        public Criteria andNombresNotIn(List<String> values) {
            addCriterion("NOMBRES not in", values, "nombres");
            return (Criteria) this;
        }

        public Criteria andNombresBetween(String value1, String value2) {
            addCriterion("NOMBRES between", value1, value2, "nombres");
            return (Criteria) this;
        }

        public Criteria andNombresNotBetween(String value1, String value2) {
            addCriterion("NOMBRES not between", value1, value2, "nombres");
            return (Criteria) this;
        }

        public Criteria andApellido1IsNull() {
            addCriterion("APELLIDO1 is null");
            return (Criteria) this;
        }

        public Criteria andApellido1IsNotNull() {
            addCriterion("APELLIDO1 is not null");
            return (Criteria) this;
        }

        public Criteria andApellido1EqualTo(String value) {
            addCriterion("APELLIDO1 =", value, "apellido1");
            return (Criteria) this;
        }

        public Criteria andApellido1NotEqualTo(String value) {
            addCriterion("APELLIDO1 <>", value, "apellido1");
            return (Criteria) this;
        }

        public Criteria andApellido1GreaterThan(String value) {
            addCriterion("APELLIDO1 >", value, "apellido1");
            return (Criteria) this;
        }

        public Criteria andApellido1GreaterThanOrEqualTo(String value) {
            addCriterion("APELLIDO1 >=", value, "apellido1");
            return (Criteria) this;
        }

        public Criteria andApellido1LessThan(String value) {
            addCriterion("APELLIDO1 <", value, "apellido1");
            return (Criteria) this;
        }

        public Criteria andApellido1LessThanOrEqualTo(String value) {
            addCriterion("APELLIDO1 <=", value, "apellido1");
            return (Criteria) this;
        }

        public Criteria andApellido1Like(String value) {
            addCriterion("APELLIDO1 like", value, "apellido1");
            return (Criteria) this;
        }

        public Criteria andApellido1NotLike(String value) {
            addCriterion("APELLIDO1 not like", value, "apellido1");
            return (Criteria) this;
        }

        public Criteria andApellido1In(List<String> values) {
            addCriterion("APELLIDO1 in", values, "apellido1");
            return (Criteria) this;
        }

        public Criteria andApellido1NotIn(List<String> values) {
            addCriterion("APELLIDO1 not in", values, "apellido1");
            return (Criteria) this;
        }

        public Criteria andApellido1Between(String value1, String value2) {
            addCriterion("APELLIDO1 between", value1, value2, "apellido1");
            return (Criteria) this;
        }

        public Criteria andApellido1NotBetween(String value1, String value2) {
            addCriterion("APELLIDO1 not between", value1, value2, "apellido1");
            return (Criteria) this;
        }

        public Criteria andApellido2IsNull() {
            addCriterion("APELLIDO2 is null");
            return (Criteria) this;
        }

        public Criteria andApellido2IsNotNull() {
            addCriterion("APELLIDO2 is not null");
            return (Criteria) this;
        }

        public Criteria andApellido2EqualTo(String value) {
            addCriterion("APELLIDO2 =", value, "apellido2");
            return (Criteria) this;
        }

        public Criteria andApellido2NotEqualTo(String value) {
            addCriterion("APELLIDO2 <>", value, "apellido2");
            return (Criteria) this;
        }

        public Criteria andApellido2GreaterThan(String value) {
            addCriterion("APELLIDO2 >", value, "apellido2");
            return (Criteria) this;
        }

        public Criteria andApellido2GreaterThanOrEqualTo(String value) {
            addCriterion("APELLIDO2 >=", value, "apellido2");
            return (Criteria) this;
        }

        public Criteria andApellido2LessThan(String value) {
            addCriterion("APELLIDO2 <", value, "apellido2");
            return (Criteria) this;
        }

        public Criteria andApellido2LessThanOrEqualTo(String value) {
            addCriterion("APELLIDO2 <=", value, "apellido2");
            return (Criteria) this;
        }

        public Criteria andApellido2Like(String value) {
            addCriterion("APELLIDO2 like", value, "apellido2");
            return (Criteria) this;
        }

        public Criteria andApellido2NotLike(String value) {
            addCriterion("APELLIDO2 not like", value, "apellido2");
            return (Criteria) this;
        }

        public Criteria andApellido2In(List<String> values) {
            addCriterion("APELLIDO2 in", values, "apellido2");
            return (Criteria) this;
        }

        public Criteria andApellido2NotIn(List<String> values) {
            addCriterion("APELLIDO2 not in", values, "apellido2");
            return (Criteria) this;
        }

        public Criteria andApellido2Between(String value1, String value2) {
            addCriterion("APELLIDO2 between", value1, value2, "apellido2");
            return (Criteria) this;
        }

        public Criteria andApellido2NotBetween(String value1, String value2) {
            addCriterion("APELLIDO2 not between", value1, value2, "apellido2");
            return (Criteria) this;
        }

        public Criteria andIndicativoIsNull() {
            addCriterion("INDICATIVO is null");
            return (Criteria) this;
        }

        public Criteria andIndicativoIsNotNull() {
            addCriterion("INDICATIVO is not null");
            return (Criteria) this;
        }

        public Criteria andIndicativoEqualTo(String value) {
            addCriterion("INDICATIVO =", value, "indicativo");
            return (Criteria) this;
        }

        public Criteria andIndicativoNotEqualTo(String value) {
            addCriterion("INDICATIVO <>", value, "indicativo");
            return (Criteria) this;
        }

        public Criteria andIndicativoGreaterThan(String value) {
            addCriterion("INDICATIVO >", value, "indicativo");
            return (Criteria) this;
        }

        public Criteria andIndicativoGreaterThanOrEqualTo(String value) {
            addCriterion("INDICATIVO >=", value, "indicativo");
            return (Criteria) this;
        }

        public Criteria andIndicativoLessThan(String value) {
            addCriterion("INDICATIVO <", value, "indicativo");
            return (Criteria) this;
        }

        public Criteria andIndicativoLessThanOrEqualTo(String value) {
            addCriterion("INDICATIVO <=", value, "indicativo");
            return (Criteria) this;
        }

        public Criteria andIndicativoLike(String value) {
            addCriterion("INDICATIVO like", value, "indicativo");
            return (Criteria) this;
        }

        public Criteria andIndicativoNotLike(String value) {
            addCriterion("INDICATIVO not like", value, "indicativo");
            return (Criteria) this;
        }

        public Criteria andIndicativoIn(List<String> values) {
            addCriterion("INDICATIVO in", values, "indicativo");
            return (Criteria) this;
        }

        public Criteria andIndicativoNotIn(List<String> values) {
            addCriterion("INDICATIVO not in", values, "indicativo");
            return (Criteria) this;
        }

        public Criteria andIndicativoBetween(String value1, String value2) {
            addCriterion("INDICATIVO between", value1, value2, "indicativo");
            return (Criteria) this;
        }

        public Criteria andIndicativoNotBetween(String value1, String value2) {
            addCriterion("INDICATIVO not between", value1, value2, "indicativo");
            return (Criteria) this;
        }

        public Criteria andTelefonoIsNull() {
            addCriterion("TELEFONO is null");
            return (Criteria) this;
        }

        public Criteria andTelefonoIsNotNull() {
            addCriterion("TELEFONO is not null");
            return (Criteria) this;
        }

        public Criteria andTelefonoEqualTo(String value) {
            addCriterion("TELEFONO =", value, "telefono");
            return (Criteria) this;
        }

        public Criteria andTelefonoNotEqualTo(String value) {
            addCriterion("TELEFONO <>", value, "telefono");
            return (Criteria) this;
        }

        public Criteria andTelefonoGreaterThan(String value) {
            addCriterion("TELEFONO >", value, "telefono");
            return (Criteria) this;
        }

        public Criteria andTelefonoGreaterThanOrEqualTo(String value) {
            addCriterion("TELEFONO >=", value, "telefono");
            return (Criteria) this;
        }

        public Criteria andTelefonoLessThan(String value) {
            addCriterion("TELEFONO <", value, "telefono");
            return (Criteria) this;
        }

        public Criteria andTelefonoLessThanOrEqualTo(String value) {
            addCriterion("TELEFONO <=", value, "telefono");
            return (Criteria) this;
        }

        public Criteria andTelefonoLike(String value) {
            addCriterion("TELEFONO like", value, "telefono");
            return (Criteria) this;
        }

        public Criteria andTelefonoNotLike(String value) {
            addCriterion("TELEFONO not like", value, "telefono");
            return (Criteria) this;
        }

        public Criteria andTelefonoIn(List<String> values) {
            addCriterion("TELEFONO in", values, "telefono");
            return (Criteria) this;
        }

        public Criteria andTelefonoNotIn(List<String> values) {
            addCriterion("TELEFONO not in", values, "telefono");
            return (Criteria) this;
        }

        public Criteria andTelefonoBetween(String value1, String value2) {
            addCriterion("TELEFONO between", value1, value2, "telefono");
            return (Criteria) this;
        }

        public Criteria andTelefonoNotBetween(String value1, String value2) {
            addCriterion("TELEFONO not between", value1, value2, "telefono");
            return (Criteria) this;
        }

        public Criteria andCelularIsNull() {
            addCriterion("CELULAR is null");
            return (Criteria) this;
        }

        public Criteria andCelularIsNotNull() {
            addCriterion("CELULAR is not null");
            return (Criteria) this;
        }

        public Criteria andCelularEqualTo(String value) {
            addCriterion("CELULAR =", value, "celular");
            return (Criteria) this;
        }

        public Criteria andCelularNotEqualTo(String value) {
            addCriterion("CELULAR <>", value, "celular");
            return (Criteria) this;
        }

        public Criteria andCelularGreaterThan(String value) {
            addCriterion("CELULAR >", value, "celular");
            return (Criteria) this;
        }

        public Criteria andCelularGreaterThanOrEqualTo(String value) {
            addCriterion("CELULAR >=", value, "celular");
            return (Criteria) this;
        }

        public Criteria andCelularLessThan(String value) {
            addCriterion("CELULAR <", value, "celular");
            return (Criteria) this;
        }

        public Criteria andCelularLessThanOrEqualTo(String value) {
            addCriterion("CELULAR <=", value, "celular");
            return (Criteria) this;
        }

        public Criteria andCelularLike(String value) {
            addCriterion("CELULAR like", value, "celular");
            return (Criteria) this;
        }

        public Criteria andCelularNotLike(String value) {
            addCriterion("CELULAR not like", value, "celular");
            return (Criteria) this;
        }

        public Criteria andCelularIn(List<String> values) {
            addCriterion("CELULAR in", values, "celular");
            return (Criteria) this;
        }

        public Criteria andCelularNotIn(List<String> values) {
            addCriterion("CELULAR not in", values, "celular");
            return (Criteria) this;
        }

        public Criteria andCelularBetween(String value1, String value2) {
            addCriterion("CELULAR between", value1, value2, "celular");
            return (Criteria) this;
        }

        public Criteria andCelularNotBetween(String value1, String value2) {
            addCriterion("CELULAR not between", value1, value2, "celular");
            return (Criteria) this;
        }

        public Criteria andGeneroIsNull() {
            addCriterion("GENERO is null");
            return (Criteria) this;
        }

        public Criteria andGeneroIsNotNull() {
            addCriterion("GENERO is not null");
            return (Criteria) this;
        }

        public Criteria andGeneroEqualTo(String value) {
            addCriterion("GENERO =", value, "genero");
            return (Criteria) this;
        }

        public Criteria andGeneroNotEqualTo(String value) {
            addCriterion("GENERO <>", value, "genero");
            return (Criteria) this;
        }

        public Criteria andGeneroGreaterThan(String value) {
            addCriterion("GENERO >", value, "genero");
            return (Criteria) this;
        }

        public Criteria andGeneroGreaterThanOrEqualTo(String value) {
            addCriterion("GENERO >=", value, "genero");
            return (Criteria) this;
        }

        public Criteria andGeneroLessThan(String value) {
            addCriterion("GENERO <", value, "genero");
            return (Criteria) this;
        }

        public Criteria andGeneroLessThanOrEqualTo(String value) {
            addCriterion("GENERO <=", value, "genero");
            return (Criteria) this;
        }

        public Criteria andGeneroLike(String value) {
            addCriterion("GENERO like", value, "genero");
            return (Criteria) this;
        }

        public Criteria andGeneroNotLike(String value) {
            addCriterion("GENERO not like", value, "genero");
            return (Criteria) this;
        }

        public Criteria andGeneroIn(List<String> values) {
            addCriterion("GENERO in", values, "genero");
            return (Criteria) this;
        }

        public Criteria andGeneroNotIn(List<String> values) {
            addCriterion("GENERO not in", values, "genero");
            return (Criteria) this;
        }

        public Criteria andGeneroBetween(String value1, String value2) {
            addCriterion("GENERO between", value1, value2, "genero");
            return (Criteria) this;
        }

        public Criteria andGeneroNotBetween(String value1, String value2) {
            addCriterion("GENERO not between", value1, value2, "genero");
            return (Criteria) this;
        }

        public Criteria andCorreoIsNull() {
            addCriterion("CORREO is null");
            return (Criteria) this;
        }

        public Criteria andCorreoIsNotNull() {
            addCriterion("CORREO is not null");
            return (Criteria) this;
        }

        public Criteria andCorreoEqualTo(String value) {
            addCriterion("CORREO =", value, "correo");
            return (Criteria) this;
        }

        public Criteria andCorreoNotEqualTo(String value) {
            addCriterion("CORREO <>", value, "correo");
            return (Criteria) this;
        }

        public Criteria andCorreoGreaterThan(String value) {
            addCriterion("CORREO >", value, "correo");
            return (Criteria) this;
        }

        public Criteria andCorreoGreaterThanOrEqualTo(String value) {
            addCriterion("CORREO >=", value, "correo");
            return (Criteria) this;
        }

        public Criteria andCorreoLessThan(String value) {
            addCriterion("CORREO <", value, "correo");
            return (Criteria) this;
        }

        public Criteria andCorreoLessThanOrEqualTo(String value) {
            addCriterion("CORREO <=", value, "correo");
            return (Criteria) this;
        }

        public Criteria andCorreoLike(String value) {
            addCriterion("CORREO like", value, "correo");
            return (Criteria) this;
        }

        public Criteria andCorreoNotLike(String value) {
            addCriterion("CORREO not like", value, "correo");
            return (Criteria) this;
        }

        public Criteria andCorreoIn(List<String> values) {
            addCriterion("CORREO in", values, "correo");
            return (Criteria) this;
        }

        public Criteria andCorreoNotIn(List<String> values) {
            addCriterion("CORREO not in", values, "correo");
            return (Criteria) this;
        }

        public Criteria andCorreoBetween(String value1, String value2) {
            addCriterion("CORREO between", value1, value2, "correo");
            return (Criteria) this;
        }

        public Criteria andCorreoNotBetween(String value1, String value2) {
            addCriterion("CORREO not between", value1, value2, "correo");
            return (Criteria) this;
        }

        public Criteria andExtraStrIsNull() {
            addCriterion("EXTRA_STR is null");
            return (Criteria) this;
        }

        public Criteria andExtraStrIsNotNull() {
            addCriterion("EXTRA_STR is not null");
            return (Criteria) this;
        }

        public Criteria andExtraStrEqualTo(String value) {
            addCriterion("EXTRA_STR =", value, "extraStr");
            return (Criteria) this;
        }

        public Criteria andExtraStrNotEqualTo(String value) {
            addCriterion("EXTRA_STR <>", value, "extraStr");
            return (Criteria) this;
        }

        public Criteria andExtraStrGreaterThan(String value) {
            addCriterion("EXTRA_STR >", value, "extraStr");
            return (Criteria) this;
        }

        public Criteria andExtraStrGreaterThanOrEqualTo(String value) {
            addCriterion("EXTRA_STR >=", value, "extraStr");
            return (Criteria) this;
        }

        public Criteria andExtraStrLessThan(String value) {
            addCriterion("EXTRA_STR <", value, "extraStr");
            return (Criteria) this;
        }

        public Criteria andExtraStrLessThanOrEqualTo(String value) {
            addCriterion("EXTRA_STR <=", value, "extraStr");
            return (Criteria) this;
        }

        public Criteria andExtraStrLike(String value) {
            addCriterion("EXTRA_STR like", value, "extraStr");
            return (Criteria) this;
        }

        public Criteria andExtraStrNotLike(String value) {
            addCriterion("EXTRA_STR not like", value, "extraStr");
            return (Criteria) this;
        }

        public Criteria andExtraStrIn(List<String> values) {
            addCriterion("EXTRA_STR in", values, "extraStr");
            return (Criteria) this;
        }

        public Criteria andExtraStrNotIn(List<String> values) {
            addCriterion("EXTRA_STR not in", values, "extraStr");
            return (Criteria) this;
        }

        public Criteria andExtraStrBetween(String value1, String value2) {
            addCriterion("EXTRA_STR between", value1, value2, "extraStr");
            return (Criteria) this;
        }

        public Criteria andExtraStrNotBetween(String value1, String value2) {
            addCriterion("EXTRA_STR not between", value1, value2, "extraStr");
            return (Criteria) this;
        }

        public Criteria andExtraNumIsNull() {
            addCriterion("EXTRA_NUM is null");
            return (Criteria) this;
        }

        public Criteria andExtraNumIsNotNull() {
            addCriterion("EXTRA_NUM is not null");
            return (Criteria) this;
        }

        public Criteria andExtraNumEqualTo(Integer value) {
            addCriterion("EXTRA_NUM =", value, "extraNum");
            return (Criteria) this;
        }

        public Criteria andExtraNumNotEqualTo(Integer value) {
            addCriterion("EXTRA_NUM <>", value, "extraNum");
            return (Criteria) this;
        }

        public Criteria andExtraNumGreaterThan(Integer value) {
            addCriterion("EXTRA_NUM >", value, "extraNum");
            return (Criteria) this;
        }

        public Criteria andExtraNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("EXTRA_NUM >=", value, "extraNum");
            return (Criteria) this;
        }

        public Criteria andExtraNumLessThan(Integer value) {
            addCriterion("EXTRA_NUM <", value, "extraNum");
            return (Criteria) this;
        }

        public Criteria andExtraNumLessThanOrEqualTo(Integer value) {
            addCriterion("EXTRA_NUM <=", value, "extraNum");
            return (Criteria) this;
        }

        public Criteria andExtraNumIn(List<Integer> values) {
            addCriterion("EXTRA_NUM in", values, "extraNum");
            return (Criteria) this;
        }

        public Criteria andExtraNumNotIn(List<Integer> values) {
            addCriterion("EXTRA_NUM not in", values, "extraNum");
            return (Criteria) this;
        }

        public Criteria andExtraNumBetween(Integer value1, Integer value2) {
            addCriterion("EXTRA_NUM between", value1, value2, "extraNum");
            return (Criteria) this;
        }

        public Criteria andExtraNumNotBetween(Integer value1, Integer value2) {
            addCriterion("EXTRA_NUM not between", value1, value2, "extraNum");
            return (Criteria) this;
        }

        public Criteria andExtraFechaIsNull() {
            addCriterion("EXTRA_FECHA is null");
            return (Criteria) this;
        }

        public Criteria andExtraFechaIsNotNull() {
            addCriterion("EXTRA_FECHA is not null");
            return (Criteria) this;
        }

        public Criteria andExtraFechaEqualTo(Date value) {
            addCriterion("EXTRA_FECHA =", value, "extraFecha");
            return (Criteria) this;
        }

        public Criteria andExtraFechaNotEqualTo(Date value) {
            addCriterion("EXTRA_FECHA <>", value, "extraFecha");
            return (Criteria) this;
        }

        public Criteria andExtraFechaGreaterThan(Date value) {
            addCriterion("EXTRA_FECHA >", value, "extraFecha");
            return (Criteria) this;
        }

        public Criteria andExtraFechaGreaterThanOrEqualTo(Date value) {
            addCriterion("EXTRA_FECHA >=", value, "extraFecha");
            return (Criteria) this;
        }

        public Criteria andExtraFechaLessThan(Date value) {
            addCriterion("EXTRA_FECHA <", value, "extraFecha");
            return (Criteria) this;
        }

        public Criteria andExtraFechaLessThanOrEqualTo(Date value) {
            addCriterion("EXTRA_FECHA <=", value, "extraFecha");
            return (Criteria) this;
        }

        public Criteria andExtraFechaIn(List<Date> values) {
            addCriterion("EXTRA_FECHA in", values, "extraFecha");
            return (Criteria) this;
        }

        public Criteria andExtraFechaNotIn(List<Date> values) {
            addCriterion("EXTRA_FECHA not in", values, "extraFecha");
            return (Criteria) this;
        }

        public Criteria andExtraFechaBetween(Date value1, Date value2) {
            addCriterion("EXTRA_FECHA between", value1, value2, "extraFecha");
            return (Criteria) this;
        }

        public Criteria andExtraFechaNotBetween(Date value1, Date value2) {
            addCriterion("EXTRA_FECHA not between", value1, value2, "extraFecha");
            return (Criteria) this;
        }

        public Criteria andCodClienteIsNull() {
            addCriterion("COD_CLIENTE is null");
            return (Criteria) this;
        }

        public Criteria andCodClienteIsNotNull() {
            addCriterion("COD_CLIENTE is not null");
            return (Criteria) this;
        }

        public Criteria andCodClienteEqualTo(String value) {
            addCriterion("COD_CLIENTE =", value, "codCliente");
            return (Criteria) this;
        }

        public Criteria andCodClienteNotEqualTo(String value) {
            addCriterion("COD_CLIENTE <>", value, "codCliente");
            return (Criteria) this;
        }

        public Criteria andCodClienteGreaterThan(String value) {
            addCriterion("COD_CLIENTE >", value, "codCliente");
            return (Criteria) this;
        }

        public Criteria andCodClienteGreaterThanOrEqualTo(String value) {
            addCriterion("COD_CLIENTE >=", value, "codCliente");
            return (Criteria) this;
        }

        public Criteria andCodClienteLessThan(String value) {
            addCriterion("COD_CLIENTE <", value, "codCliente");
            return (Criteria) this;
        }

        public Criteria andCodClienteLessThanOrEqualTo(String value) {
            addCriterion("COD_CLIENTE <=", value, "codCliente");
            return (Criteria) this;
        }

        public Criteria andCodClienteLike(String value) {
            addCriterion("COD_CLIENTE like", value, "codCliente");
            return (Criteria) this;
        }

        public Criteria andCodClienteNotLike(String value) {
            addCriterion("COD_CLIENTE not like", value, "codCliente");
            return (Criteria) this;
        }

        public Criteria andCodClienteIn(List<String> values) {
            addCriterion("COD_CLIENTE in", values, "codCliente");
            return (Criteria) this;
        }

        public Criteria andCodClienteNotIn(List<String> values) {
            addCriterion("COD_CLIENTE not in", values, "codCliente");
            return (Criteria) this;
        }

        public Criteria andCodClienteBetween(String value1, String value2) {
            addCriterion("COD_CLIENTE between", value1, value2, "codCliente");
            return (Criteria) this;
        }

        public Criteria andCodClienteNotBetween(String value1, String value2) {
            addCriterion("COD_CLIENTE not between", value1, value2, "codCliente");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table CAMPAIGNS.CP_CLIENTE
     *
     * @mbggenerated do_not_delete_during_merge Tue Apr 21 12:41:59 COT 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table CAMPAIGNS.CP_CLIENTE
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}