package com.fi.crm.campaigns.persistence.model;

public class CpConstante {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CAMPAIGNS.CP_CONSTANTE.CONSTANTE_ID
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    private String constanteId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CAMPAIGNS.CP_CONSTANTE.DESCRIPCION
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    private String descripcion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CAMPAIGNS.CP_CONSTANTE.VALOR
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    private String valor;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CAMPAIGNS.CP_CONSTANTE.CONSTANTE_ID
     *
     * @return the value of CAMPAIGNS.CP_CONSTANTE.CONSTANTE_ID
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public String getConstanteId() {
        return constanteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CAMPAIGNS.CP_CONSTANTE.CONSTANTE_ID
     *
     * @param constanteId the value for CAMPAIGNS.CP_CONSTANTE.CONSTANTE_ID
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public void setConstanteId(String constanteId) {
        this.constanteId = constanteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CAMPAIGNS.CP_CONSTANTE.DESCRIPCION
     *
     * @return the value of CAMPAIGNS.CP_CONSTANTE.DESCRIPCION
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public String getDescripcion() {
        return descripcion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CAMPAIGNS.CP_CONSTANTE.DESCRIPCION
     *
     * @param descripcion the value for CAMPAIGNS.CP_CONSTANTE.DESCRIPCION
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CAMPAIGNS.CP_CONSTANTE.VALOR
     *
     * @return the value of CAMPAIGNS.CP_CONSTANTE.VALOR
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public String getValor() {
        return valor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CAMPAIGNS.CP_CONSTANTE.VALOR
     *
     * @param valor the value for CAMPAIGNS.CP_CONSTANTE.VALOR
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public void setValor(String valor) {
        this.valor = valor;
    }
}