package com.fi.crm.campaigns.persistence.model;

public class CpPermisoPerfilKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CAMPAIGNS.CP_PERMISO_PERFIL.PERFIL_ID
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    private Integer perfilId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CAMPAIGNS.CP_PERMISO_PERFIL.ACCION
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    private String accion;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CAMPAIGNS.CP_PERMISO_PERFIL.PERFIL_ID
     *
     * @return the value of CAMPAIGNS.CP_PERMISO_PERFIL.PERFIL_ID
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public Integer getPerfilId() {
        return perfilId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CAMPAIGNS.CP_PERMISO_PERFIL.PERFIL_ID
     *
     * @param perfilId the value for CAMPAIGNS.CP_PERMISO_PERFIL.PERFIL_ID
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public void setPerfilId(Integer perfilId) {
        this.perfilId = perfilId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CAMPAIGNS.CP_PERMISO_PERFIL.ACCION
     *
     * @return the value of CAMPAIGNS.CP_PERMISO_PERFIL.ACCION
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public String getAccion() {
        return accion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CAMPAIGNS.CP_PERMISO_PERFIL.ACCION
     *
     * @param accion the value for CAMPAIGNS.CP_PERMISO_PERFIL.ACCION
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public void setAccion(String accion) {
        this.accion = accion;
    }
}