package com.fi.crm.campaigns.persistence.model;

import java.util.ArrayList;
import java.util.List;

public class CpPermisoPerfilExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table CAMPAIGNS.CP_PERMISO_PERFIL
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table CAMPAIGNS.CP_PERMISO_PERFIL
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table CAMPAIGNS.CP_PERMISO_PERFIL
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAMPAIGNS.CP_PERMISO_PERFIL
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public CpPermisoPerfilExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAMPAIGNS.CP_PERMISO_PERFIL
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAMPAIGNS.CP_PERMISO_PERFIL
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAMPAIGNS.CP_PERMISO_PERFIL
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAMPAIGNS.CP_PERMISO_PERFIL
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAMPAIGNS.CP_PERMISO_PERFIL
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAMPAIGNS.CP_PERMISO_PERFIL
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAMPAIGNS.CP_PERMISO_PERFIL
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAMPAIGNS.CP_PERMISO_PERFIL
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAMPAIGNS.CP_PERMISO_PERFIL
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAMPAIGNS.CP_PERMISO_PERFIL
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table CAMPAIGNS.CP_PERMISO_PERFIL
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPerfilIdIsNull() {
            addCriterion("PERFIL_ID is null");
            return (Criteria) this;
        }

        public Criteria andPerfilIdIsNotNull() {
            addCriterion("PERFIL_ID is not null");
            return (Criteria) this;
        }

        public Criteria andPerfilIdEqualTo(Integer value) {
            addCriterion("PERFIL_ID =", value, "perfilId");
            return (Criteria) this;
        }

        public Criteria andPerfilIdNotEqualTo(Integer value) {
            addCriterion("PERFIL_ID <>", value, "perfilId");
            return (Criteria) this;
        }

        public Criteria andPerfilIdGreaterThan(Integer value) {
            addCriterion("PERFIL_ID >", value, "perfilId");
            return (Criteria) this;
        }

        public Criteria andPerfilIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("PERFIL_ID >=", value, "perfilId");
            return (Criteria) this;
        }

        public Criteria andPerfilIdLessThan(Integer value) {
            addCriterion("PERFIL_ID <", value, "perfilId");
            return (Criteria) this;
        }

        public Criteria andPerfilIdLessThanOrEqualTo(Integer value) {
            addCriterion("PERFIL_ID <=", value, "perfilId");
            return (Criteria) this;
        }

        public Criteria andPerfilIdIn(List<Integer> values) {
            addCriterion("PERFIL_ID in", values, "perfilId");
            return (Criteria) this;
        }

        public Criteria andPerfilIdNotIn(List<Integer> values) {
            addCriterion("PERFIL_ID not in", values, "perfilId");
            return (Criteria) this;
        }

        public Criteria andPerfilIdBetween(Integer value1, Integer value2) {
            addCriterion("PERFIL_ID between", value1, value2, "perfilId");
            return (Criteria) this;
        }

        public Criteria andPerfilIdNotBetween(Integer value1, Integer value2) {
            addCriterion("PERFIL_ID not between", value1, value2, "perfilId");
            return (Criteria) this;
        }

        public Criteria andAccionIsNull() {
            addCriterion("ACCION is null");
            return (Criteria) this;
        }

        public Criteria andAccionIsNotNull() {
            addCriterion("ACCION is not null");
            return (Criteria) this;
        }

        public Criteria andAccionEqualTo(String value) {
            addCriterion("ACCION =", value, "accion");
            return (Criteria) this;
        }

        public Criteria andAccionNotEqualTo(String value) {
            addCriterion("ACCION <>", value, "accion");
            return (Criteria) this;
        }

        public Criteria andAccionGreaterThan(String value) {
            addCriterion("ACCION >", value, "accion");
            return (Criteria) this;
        }

        public Criteria andAccionGreaterThanOrEqualTo(String value) {
            addCriterion("ACCION >=", value, "accion");
            return (Criteria) this;
        }

        public Criteria andAccionLessThan(String value) {
            addCriterion("ACCION <", value, "accion");
            return (Criteria) this;
        }

        public Criteria andAccionLessThanOrEqualTo(String value) {
            addCriterion("ACCION <=", value, "accion");
            return (Criteria) this;
        }

        public Criteria andAccionLike(String value) {
            addCriterion("ACCION like", value, "accion");
            return (Criteria) this;
        }

        public Criteria andAccionNotLike(String value) {
            addCriterion("ACCION not like", value, "accion");
            return (Criteria) this;
        }

        public Criteria andAccionIn(List<String> values) {
            addCriterion("ACCION in", values, "accion");
            return (Criteria) this;
        }

        public Criteria andAccionNotIn(List<String> values) {
            addCriterion("ACCION not in", values, "accion");
            return (Criteria) this;
        }

        public Criteria andAccionBetween(String value1, String value2) {
            addCriterion("ACCION between", value1, value2, "accion");
            return (Criteria) this;
        }

        public Criteria andAccionNotBetween(String value1, String value2) {
            addCriterion("ACCION not between", value1, value2, "accion");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table CAMPAIGNS.CP_PERMISO_PERFIL
     *
     * @mbggenerated do_not_delete_during_merge Tue Apr 21 12:41:59 COT 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table CAMPAIGNS.CP_PERMISO_PERFIL
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}