package com.fi.crm.campaigns.persistence.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class CpSeguimientoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table CAMPAIGNS.CP_SEGUIMIENTO
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table CAMPAIGNS.CP_SEGUIMIENTO
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table CAMPAIGNS.CP_SEGUIMIENTO
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAMPAIGNS.CP_SEGUIMIENTO
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public CpSeguimientoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAMPAIGNS.CP_SEGUIMIENTO
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAMPAIGNS.CP_SEGUIMIENTO
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAMPAIGNS.CP_SEGUIMIENTO
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAMPAIGNS.CP_SEGUIMIENTO
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAMPAIGNS.CP_SEGUIMIENTO
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAMPAIGNS.CP_SEGUIMIENTO
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAMPAIGNS.CP_SEGUIMIENTO
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAMPAIGNS.CP_SEGUIMIENTO
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAMPAIGNS.CP_SEGUIMIENTO
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAMPAIGNS.CP_SEGUIMIENTO
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table CAMPAIGNS.CP_SEGUIMIENTO
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andSeguimientoIdIsNull() {
            addCriterion("SEGUIMIENTO_ID is null");
            return (Criteria) this;
        }

        public Criteria andSeguimientoIdIsNotNull() {
            addCriterion("SEGUIMIENTO_ID is not null");
            return (Criteria) this;
        }

        public Criteria andSeguimientoIdEqualTo(Integer value) {
            addCriterion("SEGUIMIENTO_ID =", value, "seguimientoId");
            return (Criteria) this;
        }

        public Criteria andSeguimientoIdNotEqualTo(Integer value) {
            addCriterion("SEGUIMIENTO_ID <>", value, "seguimientoId");
            return (Criteria) this;
        }

        public Criteria andSeguimientoIdGreaterThan(Integer value) {
            addCriterion("SEGUIMIENTO_ID >", value, "seguimientoId");
            return (Criteria) this;
        }

        public Criteria andSeguimientoIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("SEGUIMIENTO_ID >=", value, "seguimientoId");
            return (Criteria) this;
        }

        public Criteria andSeguimientoIdLessThan(Integer value) {
            addCriterion("SEGUIMIENTO_ID <", value, "seguimientoId");
            return (Criteria) this;
        }

        public Criteria andSeguimientoIdLessThanOrEqualTo(Integer value) {
            addCriterion("SEGUIMIENTO_ID <=", value, "seguimientoId");
            return (Criteria) this;
        }

        public Criteria andSeguimientoIdIn(List<Integer> values) {
            addCriterion("SEGUIMIENTO_ID in", values, "seguimientoId");
            return (Criteria) this;
        }

        public Criteria andSeguimientoIdNotIn(List<Integer> values) {
            addCriterion("SEGUIMIENTO_ID not in", values, "seguimientoId");
            return (Criteria) this;
        }

        public Criteria andSeguimientoIdBetween(Integer value1, Integer value2) {
            addCriterion("SEGUIMIENTO_ID between", value1, value2, "seguimientoId");
            return (Criteria) this;
        }

        public Criteria andSeguimientoIdNotBetween(Integer value1, Integer value2) {
            addCriterion("SEGUIMIENTO_ID not between", value1, value2, "seguimientoId");
            return (Criteria) this;
        }

        public Criteria andClienteIdIsNull() {
            addCriterion("CLIENTE_ID is null");
            return (Criteria) this;
        }

        public Criteria andClienteIdIsNotNull() {
            addCriterion("CLIENTE_ID is not null");
            return (Criteria) this;
        }

        public Criteria andClienteIdEqualTo(Integer value) {
            addCriterion("CLIENTE_ID =", value, "clienteId");
            return (Criteria) this;
        }

        public Criteria andClienteIdNotEqualTo(Integer value) {
            addCriterion("CLIENTE_ID <>", value, "clienteId");
            return (Criteria) this;
        }

        public Criteria andClienteIdGreaterThan(Integer value) {
            addCriterion("CLIENTE_ID >", value, "clienteId");
            return (Criteria) this;
        }

        public Criteria andClienteIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("CLIENTE_ID >=", value, "clienteId");
            return (Criteria) this;
        }

        public Criteria andClienteIdLessThan(Integer value) {
            addCriterion("CLIENTE_ID <", value, "clienteId");
            return (Criteria) this;
        }

        public Criteria andClienteIdLessThanOrEqualTo(Integer value) {
            addCriterion("CLIENTE_ID <=", value, "clienteId");
            return (Criteria) this;
        }

        public Criteria andClienteIdIn(List<Integer> values) {
            addCriterion("CLIENTE_ID in", values, "clienteId");
            return (Criteria) this;
        }

        public Criteria andClienteIdNotIn(List<Integer> values) {
            addCriterion("CLIENTE_ID not in", values, "clienteId");
            return (Criteria) this;
        }

        public Criteria andClienteIdBetween(Integer value1, Integer value2) {
            addCriterion("CLIENTE_ID between", value1, value2, "clienteId");
            return (Criteria) this;
        }

        public Criteria andClienteIdNotBetween(Integer value1, Integer value2) {
            addCriterion("CLIENTE_ID not between", value1, value2, "clienteId");
            return (Criteria) this;
        }

        public Criteria andCampaniaIdIsNull() {
            addCriterion("CAMPANIA_ID is null");
            return (Criteria) this;
        }

        public Criteria andCampaniaIdIsNotNull() {
            addCriterion("CAMPANIA_ID is not null");
            return (Criteria) this;
        }

        public Criteria andCampaniaIdEqualTo(Integer value) {
            addCriterion("CAMPANIA_ID =", value, "campaniaId");
            return (Criteria) this;
        }

        public Criteria andCampaniaIdNotEqualTo(Integer value) {
            addCriterion("CAMPANIA_ID <>", value, "campaniaId");
            return (Criteria) this;
        }

        public Criteria andCampaniaIdGreaterThan(Integer value) {
            addCriterion("CAMPANIA_ID >", value, "campaniaId");
            return (Criteria) this;
        }

        public Criteria andCampaniaIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("CAMPANIA_ID >=", value, "campaniaId");
            return (Criteria) this;
        }

        public Criteria andCampaniaIdLessThan(Integer value) {
            addCriterion("CAMPANIA_ID <", value, "campaniaId");
            return (Criteria) this;
        }

        public Criteria andCampaniaIdLessThanOrEqualTo(Integer value) {
            addCriterion("CAMPANIA_ID <=", value, "campaniaId");
            return (Criteria) this;
        }

        public Criteria andCampaniaIdIn(List<Integer> values) {
            addCriterion("CAMPANIA_ID in", values, "campaniaId");
            return (Criteria) this;
        }

        public Criteria andCampaniaIdNotIn(List<Integer> values) {
            addCriterion("CAMPANIA_ID not in", values, "campaniaId");
            return (Criteria) this;
        }

        public Criteria andCampaniaIdBetween(Integer value1, Integer value2) {
            addCriterion("CAMPANIA_ID between", value1, value2, "campaniaId");
            return (Criteria) this;
        }

        public Criteria andCampaniaIdNotBetween(Integer value1, Integer value2) {
            addCriterion("CAMPANIA_ID not between", value1, value2, "campaniaId");
            return (Criteria) this;
        }

        public Criteria andEstadoIsNull() {
            addCriterion("ESTADO is null");
            return (Criteria) this;
        }

        public Criteria andEstadoIsNotNull() {
            addCriterion("ESTADO is not null");
            return (Criteria) this;
        }

        public Criteria andEstadoEqualTo(String value) {
            addCriterion("ESTADO =", value, "estado");
            return (Criteria) this;
        }

        public Criteria andEstadoNotEqualTo(String value) {
            addCriterion("ESTADO <>", value, "estado");
            return (Criteria) this;
        }

        public Criteria andEstadoGreaterThan(String value) {
            addCriterion("ESTADO >", value, "estado");
            return (Criteria) this;
        }

        public Criteria andEstadoGreaterThanOrEqualTo(String value) {
            addCriterion("ESTADO >=", value, "estado");
            return (Criteria) this;
        }

        public Criteria andEstadoLessThan(String value) {
            addCriterion("ESTADO <", value, "estado");
            return (Criteria) this;
        }

        public Criteria andEstadoLessThanOrEqualTo(String value) {
            addCriterion("ESTADO <=", value, "estado");
            return (Criteria) this;
        }

        public Criteria andEstadoLike(String value) {
            addCriterion("ESTADO like", value, "estado");
            return (Criteria) this;
        }

        public Criteria andEstadoNotLike(String value) {
            addCriterion("ESTADO not like", value, "estado");
            return (Criteria) this;
        }

        public Criteria andEstadoIn(List<String> values) {
            addCriterion("ESTADO in", values, "estado");
            return (Criteria) this;
        }

        public Criteria andEstadoNotIn(List<String> values) {
            addCriterion("ESTADO not in", values, "estado");
            return (Criteria) this;
        }

        public Criteria andEstadoBetween(String value1, String value2) {
            addCriterion("ESTADO between", value1, value2, "estado");
            return (Criteria) this;
        }

        public Criteria andEstadoNotBetween(String value1, String value2) {
            addCriterion("ESTADO not between", value1, value2, "estado");
            return (Criteria) this;
        }

        public Criteria andSubestadoIsNull() {
            addCriterion("SUBESTADO is null");
            return (Criteria) this;
        }

        public Criteria andSubestadoIsNotNull() {
            addCriterion("SUBESTADO is not null");
            return (Criteria) this;
        }

        public Criteria andSubestadoEqualTo(Integer value) {
            addCriterion("SUBESTADO =", value, "subestado");
            return (Criteria) this;
        }

        public Criteria andSubestadoNotEqualTo(Integer value) {
            addCriterion("SUBESTADO <>", value, "subestado");
            return (Criteria) this;
        }

        public Criteria andSubestadoGreaterThan(Integer value) {
            addCriterion("SUBESTADO >", value, "subestado");
            return (Criteria) this;
        }

        public Criteria andSubestadoGreaterThanOrEqualTo(Integer value) {
            addCriterion("SUBESTADO >=", value, "subestado");
            return (Criteria) this;
        }

        public Criteria andSubestadoLessThan(Integer value) {
            addCriterion("SUBESTADO <", value, "subestado");
            return (Criteria) this;
        }

        public Criteria andSubestadoLessThanOrEqualTo(Integer value) {
            addCriterion("SUBESTADO <=", value, "subestado");
            return (Criteria) this;
        }

        public Criteria andSubestadoIn(List<Integer> values) {
            addCriterion("SUBESTADO in", values, "subestado");
            return (Criteria) this;
        }

        public Criteria andSubestadoNotIn(List<Integer> values) {
            addCriterion("SUBESTADO not in", values, "subestado");
            return (Criteria) this;
        }

        public Criteria andSubestadoBetween(Integer value1, Integer value2) {
            addCriterion("SUBESTADO between", value1, value2, "subestado");
            return (Criteria) this;
        }

        public Criteria andSubestadoNotBetween(Integer value1, Integer value2) {
            addCriterion("SUBESTADO not between", value1, value2, "subestado");
            return (Criteria) this;
        }

        public Criteria andFechaUltEstadoIsNull() {
            addCriterion("FECHA_ULT_ESTADO is null");
            return (Criteria) this;
        }

        public Criteria andFechaUltEstadoIsNotNull() {
            addCriterion("FECHA_ULT_ESTADO is not null");
            return (Criteria) this;
        }

        public Criteria andFechaUltEstadoEqualTo(Date value) {
            addCriterion("FECHA_ULT_ESTADO =", value, "fechaUltEstado");
            return (Criteria) this;
        }

        public Criteria andFechaUltEstadoNotEqualTo(Date value) {
            addCriterion("FECHA_ULT_ESTADO <>", value, "fechaUltEstado");
            return (Criteria) this;
        }

        public Criteria andFechaUltEstadoGreaterThan(Date value) {
            addCriterion("FECHA_ULT_ESTADO >", value, "fechaUltEstado");
            return (Criteria) this;
        }

        public Criteria andFechaUltEstadoGreaterThanOrEqualTo(Date value) {
            addCriterion("FECHA_ULT_ESTADO >=", value, "fechaUltEstado");
            return (Criteria) this;
        }

        public Criteria andFechaUltEstadoLessThan(Date value) {
            addCriterion("FECHA_ULT_ESTADO <", value, "fechaUltEstado");
            return (Criteria) this;
        }

        public Criteria andFechaUltEstadoLessThanOrEqualTo(Date value) {
            addCriterion("FECHA_ULT_ESTADO <=", value, "fechaUltEstado");
            return (Criteria) this;
        }

        public Criteria andFechaUltEstadoIn(List<Date> values) {
            addCriterion("FECHA_ULT_ESTADO in", values, "fechaUltEstado");
            return (Criteria) this;
        }

        public Criteria andFechaUltEstadoNotIn(List<Date> values) {
            addCriterion("FECHA_ULT_ESTADO not in", values, "fechaUltEstado");
            return (Criteria) this;
        }

        public Criteria andFechaUltEstadoBetween(Date value1, Date value2) {
            addCriterion("FECHA_ULT_ESTADO between", value1, value2, "fechaUltEstado");
            return (Criteria) this;
        }

        public Criteria andFechaUltEstadoNotBetween(Date value1, Date value2) {
            addCriterion("FECHA_ULT_ESTADO not between", value1, value2, "fechaUltEstado");
            return (Criteria) this;
        }

        public Criteria andUsuarioIsNull() {
            addCriterion("USUARIO is null");
            return (Criteria) this;
        }

        public Criteria andUsuarioIsNotNull() {
            addCriterion("USUARIO is not null");
            return (Criteria) this;
        }

        public Criteria andUsuarioEqualTo(String value) {
            addCriterion("USUARIO =", value, "usuario");
            return (Criteria) this;
        }

        public Criteria andUsuarioNotEqualTo(String value) {
            addCriterion("USUARIO <>", value, "usuario");
            return (Criteria) this;
        }

        public Criteria andUsuarioGreaterThan(String value) {
            addCriterion("USUARIO >", value, "usuario");
            return (Criteria) this;
        }

        public Criteria andUsuarioGreaterThanOrEqualTo(String value) {
            addCriterion("USUARIO >=", value, "usuario");
            return (Criteria) this;
        }

        public Criteria andUsuarioLessThan(String value) {
            addCriterion("USUARIO <", value, "usuario");
            return (Criteria) this;
        }

        public Criteria andUsuarioLessThanOrEqualTo(String value) {
            addCriterion("USUARIO <=", value, "usuario");
            return (Criteria) this;
        }

        public Criteria andUsuarioLike(String value) {
            addCriterion("USUARIO like", value, "usuario");
            return (Criteria) this;
        }

        public Criteria andUsuarioNotLike(String value) {
            addCriterion("USUARIO not like", value, "usuario");
            return (Criteria) this;
        }

        public Criteria andUsuarioIn(List<String> values) {
            addCriterion("USUARIO in", values, "usuario");
            return (Criteria) this;
        }

        public Criteria andUsuarioNotIn(List<String> values) {
            addCriterion("USUARIO not in", values, "usuario");
            return (Criteria) this;
        }

        public Criteria andUsuarioBetween(String value1, String value2) {
            addCriterion("USUARIO between", value1, value2, "usuario");
            return (Criteria) this;
        }

        public Criteria andUsuarioNotBetween(String value1, String value2) {
            addCriterion("USUARIO not between", value1, value2, "usuario");
            return (Criteria) this;
        }

        public Criteria andObservacionesIsNull() {
            addCriterion("OBSERVACIONES is null");
            return (Criteria) this;
        }

        public Criteria andObservacionesIsNotNull() {
            addCriterion("OBSERVACIONES is not null");
            return (Criteria) this;
        }

        public Criteria andObservacionesEqualTo(String value) {
            addCriterion("OBSERVACIONES =", value, "observaciones");
            return (Criteria) this;
        }

        public Criteria andObservacionesNotEqualTo(String value) {
            addCriterion("OBSERVACIONES <>", value, "observaciones");
            return (Criteria) this;
        }

        public Criteria andObservacionesGreaterThan(String value) {
            addCriterion("OBSERVACIONES >", value, "observaciones");
            return (Criteria) this;
        }

        public Criteria andObservacionesGreaterThanOrEqualTo(String value) {
            addCriterion("OBSERVACIONES >=", value, "observaciones");
            return (Criteria) this;
        }

        public Criteria andObservacionesLessThan(String value) {
            addCriterion("OBSERVACIONES <", value, "observaciones");
            return (Criteria) this;
        }

        public Criteria andObservacionesLessThanOrEqualTo(String value) {
            addCriterion("OBSERVACIONES <=", value, "observaciones");
            return (Criteria) this;
        }

        public Criteria andObservacionesLike(String value) {
            addCriterion("OBSERVACIONES like", value, "observaciones");
            return (Criteria) this;
        }

        public Criteria andObservacionesNotLike(String value) {
            addCriterion("OBSERVACIONES not like", value, "observaciones");
            return (Criteria) this;
        }

        public Criteria andObservacionesIn(List<String> values) {
            addCriterion("OBSERVACIONES in", values, "observaciones");
            return (Criteria) this;
        }

        public Criteria andObservacionesNotIn(List<String> values) {
            addCriterion("OBSERVACIONES not in", values, "observaciones");
            return (Criteria) this;
        }

        public Criteria andObservacionesBetween(String value1, String value2) {
            addCriterion("OBSERVACIONES between", value1, value2, "observaciones");
            return (Criteria) this;
        }

        public Criteria andObservacionesNotBetween(String value1, String value2) {
            addCriterion("OBSERVACIONES not between", value1, value2, "observaciones");
            return (Criteria) this;
        }

        public Criteria andDuracionIsNull() {
            addCriterion("DURACION is null");
            return (Criteria) this;
        }

        public Criteria andDuracionIsNotNull() {
            addCriterion("DURACION is not null");
            return (Criteria) this;
        }

        public Criteria andDuracionEqualTo(Integer value) {
            addCriterion("DURACION =", value, "duracion");
            return (Criteria) this;
        }

        public Criteria andDuracionNotEqualTo(Integer value) {
            addCriterion("DURACION <>", value, "duracion");
            return (Criteria) this;
        }

        public Criteria andDuracionGreaterThan(Integer value) {
            addCriterion("DURACION >", value, "duracion");
            return (Criteria) this;
        }

        public Criteria andDuracionGreaterThanOrEqualTo(Integer value) {
            addCriterion("DURACION >=", value, "duracion");
            return (Criteria) this;
        }

        public Criteria andDuracionLessThan(Integer value) {
            addCriterion("DURACION <", value, "duracion");
            return (Criteria) this;
        }

        public Criteria andDuracionLessThanOrEqualTo(Integer value) {
            addCriterion("DURACION <=", value, "duracion");
            return (Criteria) this;
        }

        public Criteria andDuracionIn(List<Integer> values) {
            addCriterion("DURACION in", values, "duracion");
            return (Criteria) this;
        }

        public Criteria andDuracionNotIn(List<Integer> values) {
            addCriterion("DURACION not in", values, "duracion");
            return (Criteria) this;
        }

        public Criteria andDuracionBetween(Integer value1, Integer value2) {
            addCriterion("DURACION between", value1, value2, "duracion");
            return (Criteria) this;
        }

        public Criteria andDuracionNotBetween(Integer value1, Integer value2) {
            addCriterion("DURACION not between", value1, value2, "duracion");
            return (Criteria) this;
        }

        public Criteria andLlamandoIsNull() {
            addCriterion("LLAMANDO is null");
            return (Criteria) this;
        }

        public Criteria andLlamandoIsNotNull() {
            addCriterion("LLAMANDO is not null");
            return (Criteria) this;
        }

        public Criteria andLlamandoEqualTo(String value) {
            addCriterion("LLAMANDO =", value, "llamando");
            return (Criteria) this;
        }

        public Criteria andLlamandoNotEqualTo(String value) {
            addCriterion("LLAMANDO <>", value, "llamando");
            return (Criteria) this;
        }

        public Criteria andLlamandoGreaterThan(String value) {
            addCriterion("LLAMANDO >", value, "llamando");
            return (Criteria) this;
        }

        public Criteria andLlamandoGreaterThanOrEqualTo(String value) {
            addCriterion("LLAMANDO >=", value, "llamando");
            return (Criteria) this;
        }

        public Criteria andLlamandoLessThan(String value) {
            addCriterion("LLAMANDO <", value, "llamando");
            return (Criteria) this;
        }

        public Criteria andLlamandoLessThanOrEqualTo(String value) {
            addCriterion("LLAMANDO <=", value, "llamando");
            return (Criteria) this;
        }

        public Criteria andLlamandoLike(String value) {
            addCriterion("LLAMANDO like", value, "llamando");
            return (Criteria) this;
        }

        public Criteria andLlamandoNotLike(String value) {
            addCriterion("LLAMANDO not like", value, "llamando");
            return (Criteria) this;
        }

        public Criteria andLlamandoIn(List<String> values) {
            addCriterion("LLAMANDO in", values, "llamando");
            return (Criteria) this;
        }

        public Criteria andLlamandoNotIn(List<String> values) {
            addCriterion("LLAMANDO not in", values, "llamando");
            return (Criteria) this;
        }

        public Criteria andLlamandoBetween(String value1, String value2) {
            addCriterion("LLAMANDO between", value1, value2, "llamando");
            return (Criteria) this;
        }

        public Criteria andLlamandoNotBetween(String value1, String value2) {
            addCriterion("LLAMANDO not between", value1, value2, "llamando");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table CAMPAIGNS.CP_SEGUIMIENTO
     *
     * @mbggenerated do_not_delete_during_merge Tue Apr 21 12:41:59 COT 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table CAMPAIGNS.CP_SEGUIMIENTO
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}