package com.fi.crm.campaigns.persistence.model;

import java.util.Date;

public class CpSeguimientoMensaje {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CAMPAIGNS.CP_SEGUIMIENTO_MENSAJE.SEG_MENSAJE_ID
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    private Integer segMensajeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CAMPAIGNS.CP_SEGUIMIENTO_MENSAJE.CLIENTE_ID
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    private Integer clienteId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CAMPAIGNS.CP_SEGUIMIENTO_MENSAJE.CAMPANIA_ID
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    private Integer campaniaId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CAMPAIGNS.CP_SEGUIMIENTO_MENSAJE.ESTADO
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    private String estado;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CAMPAIGNS.CP_SEGUIMIENTO_MENSAJE.FECHA_ULT_ESTAD
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    private Date fechaUltEstad;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CAMPAIGNS.CP_SEGUIMIENTO_MENSAJE.SEG_MENSAJE_ID
     *
     * @return the value of CAMPAIGNS.CP_SEGUIMIENTO_MENSAJE.SEG_MENSAJE_ID
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public Integer getSegMensajeId() {
        return segMensajeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CAMPAIGNS.CP_SEGUIMIENTO_MENSAJE.SEG_MENSAJE_ID
     *
     * @param segMensajeId the value for CAMPAIGNS.CP_SEGUIMIENTO_MENSAJE.SEG_MENSAJE_ID
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public void setSegMensajeId(Integer segMensajeId) {
        this.segMensajeId = segMensajeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CAMPAIGNS.CP_SEGUIMIENTO_MENSAJE.CLIENTE_ID
     *
     * @return the value of CAMPAIGNS.CP_SEGUIMIENTO_MENSAJE.CLIENTE_ID
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public Integer getClienteId() {
        return clienteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CAMPAIGNS.CP_SEGUIMIENTO_MENSAJE.CLIENTE_ID
     *
     * @param clienteId the value for CAMPAIGNS.CP_SEGUIMIENTO_MENSAJE.CLIENTE_ID
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public void setClienteId(Integer clienteId) {
        this.clienteId = clienteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CAMPAIGNS.CP_SEGUIMIENTO_MENSAJE.CAMPANIA_ID
     *
     * @return the value of CAMPAIGNS.CP_SEGUIMIENTO_MENSAJE.CAMPANIA_ID
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public Integer getCampaniaId() {
        return campaniaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CAMPAIGNS.CP_SEGUIMIENTO_MENSAJE.CAMPANIA_ID
     *
     * @param campaniaId the value for CAMPAIGNS.CP_SEGUIMIENTO_MENSAJE.CAMPANIA_ID
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public void setCampaniaId(Integer campaniaId) {
        this.campaniaId = campaniaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CAMPAIGNS.CP_SEGUIMIENTO_MENSAJE.ESTADO
     *
     * @return the value of CAMPAIGNS.CP_SEGUIMIENTO_MENSAJE.ESTADO
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public String getEstado() {
        return estado;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CAMPAIGNS.CP_SEGUIMIENTO_MENSAJE.ESTADO
     *
     * @param estado the value for CAMPAIGNS.CP_SEGUIMIENTO_MENSAJE.ESTADO
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public void setEstado(String estado) {
        this.estado = estado;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CAMPAIGNS.CP_SEGUIMIENTO_MENSAJE.FECHA_ULT_ESTAD
     *
     * @return the value of CAMPAIGNS.CP_SEGUIMIENTO_MENSAJE.FECHA_ULT_ESTAD
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public Date getFechaUltEstad() {
        return fechaUltEstad;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CAMPAIGNS.CP_SEGUIMIENTO_MENSAJE.FECHA_ULT_ESTAD
     *
     * @param fechaUltEstad the value for CAMPAIGNS.CP_SEGUIMIENTO_MENSAJE.FECHA_ULT_ESTAD
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public void setFechaUltEstad(Date fechaUltEstad) {
        this.fechaUltEstad = fechaUltEstad;
    }
}