package com.fi.crm.campaigns.persistence.model;

public class CpUsuarioPerfil {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CAMPAIGNS.CP_USUARIO_PERFIL.USU_PER_ID
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    private Integer usuPerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CAMPAIGNS.CP_USUARIO_PERFIL.PERFIL_ID
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    private Integer perfilId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CAMPAIGNS.CP_USUARIO_PERFIL.COD_USUARIO
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    private String codUsuario;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CAMPAIGNS.CP_USUARIO_PERFIL.USU_PER_ID
     *
     * @return the value of CAMPAIGNS.CP_USUARIO_PERFIL.USU_PER_ID
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public Integer getUsuPerId() {
        return usuPerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CAMPAIGNS.CP_USUARIO_PERFIL.USU_PER_ID
     *
     * @param usuPerId the value for CAMPAIGNS.CP_USUARIO_PERFIL.USU_PER_ID
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public void setUsuPerId(Integer usuPerId) {
        this.usuPerId = usuPerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CAMPAIGNS.CP_USUARIO_PERFIL.PERFIL_ID
     *
     * @return the value of CAMPAIGNS.CP_USUARIO_PERFIL.PERFIL_ID
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public Integer getPerfilId() {
        return perfilId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CAMPAIGNS.CP_USUARIO_PERFIL.PERFIL_ID
     *
     * @param perfilId the value for CAMPAIGNS.CP_USUARIO_PERFIL.PERFIL_ID
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public void setPerfilId(Integer perfilId) {
        this.perfilId = perfilId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CAMPAIGNS.CP_USUARIO_PERFIL.COD_USUARIO
     *
     * @return the value of CAMPAIGNS.CP_USUARIO_PERFIL.COD_USUARIO
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public String getCodUsuario() {
        return codUsuario;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CAMPAIGNS.CP_USUARIO_PERFIL.COD_USUARIO
     *
     * @param codUsuario the value for CAMPAIGNS.CP_USUARIO_PERFIL.COD_USUARIO
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public void setCodUsuario(String codUsuario) {
        this.codUsuario = codUsuario;
    }
}