package com.fi.crm.campaigns.persistence.model;

import java.util.Date;

public class Marcas extends MarcasKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NAF6.MARCAS.DESCRIPCION
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    private String descripcion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NAF6.MARCAS.TSTAMP
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    private Date tstamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NAF6.MARCAS.IND_DEMANDA
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    private String indDemanda;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NAF6.MARCAS.DESCRIPCION
     *
     * @return the value of NAF6.MARCAS.DESCRIPCION
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public String getDescripcion() {
        return descripcion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NAF6.MARCAS.DESCRIPCION
     *
     * @param descripcion the value for NAF6.MARCAS.DESCRIPCION
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NAF6.MARCAS.TSTAMP
     *
     * @return the value of NAF6.MARCAS.TSTAMP
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public Date getTstamp() {
        return tstamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NAF6.MARCAS.TSTAMP
     *
     * @param tstamp the value for NAF6.MARCAS.TSTAMP
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public void setTstamp(Date tstamp) {
        this.tstamp = tstamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NAF6.MARCAS.IND_DEMANDA
     *
     * @return the value of NAF6.MARCAS.IND_DEMANDA
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public String getIndDemanda() {
        return indDemanda;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NAF6.MARCAS.IND_DEMANDA
     *
     * @param indDemanda the value for NAF6.MARCAS.IND_DEMANDA
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public void setIndDemanda(String indDemanda) {
        this.indDemanda = indDemanda;
    }
}