package com.fi.crm.campaigns.persistence.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class PdUsuarioExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table NAF6.PD_USUARIO
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table NAF6.PD_USUARIO
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table NAF6.PD_USUARIO
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NAF6.PD_USUARIO
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public PdUsuarioExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NAF6.PD_USUARIO
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NAF6.PD_USUARIO
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NAF6.PD_USUARIO
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NAF6.PD_USUARIO
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NAF6.PD_USUARIO
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NAF6.PD_USUARIO
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NAF6.PD_USUARIO
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NAF6.PD_USUARIO
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NAF6.PD_USUARIO
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NAF6.PD_USUARIO
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table NAF6.PD_USUARIO
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCodUsuarioIsNull() {
            addCriterion("COD_USUARIO is null");
            return (Criteria) this;
        }

        public Criteria andCodUsuarioIsNotNull() {
            addCriterion("COD_USUARIO is not null");
            return (Criteria) this;
        }

        public Criteria andCodUsuarioEqualTo(String value) {
            addCriterion("COD_USUARIO =", value, "codUsuario");
            return (Criteria) this;
        }

        public Criteria andCodUsuarioNotEqualTo(String value) {
            addCriterion("COD_USUARIO <>", value, "codUsuario");
            return (Criteria) this;
        }

        public Criteria andCodUsuarioGreaterThan(String value) {
            addCriterion("COD_USUARIO >", value, "codUsuario");
            return (Criteria) this;
        }

        public Criteria andCodUsuarioGreaterThanOrEqualTo(String value) {
            addCriterion("COD_USUARIO >=", value, "codUsuario");
            return (Criteria) this;
        }

        public Criteria andCodUsuarioLessThan(String value) {
            addCriterion("COD_USUARIO <", value, "codUsuario");
            return (Criteria) this;
        }

        public Criteria andCodUsuarioLessThanOrEqualTo(String value) {
            addCriterion("COD_USUARIO <=", value, "codUsuario");
            return (Criteria) this;
        }

        public Criteria andCodUsuarioLike(String value) {
            addCriterion("COD_USUARIO like", value, "codUsuario");
            return (Criteria) this;
        }

        public Criteria andCodUsuarioNotLike(String value) {
            addCriterion("COD_USUARIO not like", value, "codUsuario");
            return (Criteria) this;
        }

        public Criteria andCodUsuarioIn(List<String> values) {
            addCriterion("COD_USUARIO in", values, "codUsuario");
            return (Criteria) this;
        }

        public Criteria andCodUsuarioNotIn(List<String> values) {
            addCriterion("COD_USUARIO not in", values, "codUsuario");
            return (Criteria) this;
        }

        public Criteria andCodUsuarioBetween(String value1, String value2) {
            addCriterion("COD_USUARIO between", value1, value2, "codUsuario");
            return (Criteria) this;
        }

        public Criteria andCodUsuarioNotBetween(String value1, String value2) {
            addCriterion("COD_USUARIO not between", value1, value2, "codUsuario");
            return (Criteria) this;
        }

        public Criteria andContrasenaIsNull() {
            addCriterion("CONTRASENA is null");
            return (Criteria) this;
        }

        public Criteria andContrasenaIsNotNull() {
            addCriterion("CONTRASENA is not null");
            return (Criteria) this;
        }

        public Criteria andContrasenaEqualTo(String value) {
            addCriterion("CONTRASENA =", value, "contrasena");
            return (Criteria) this;
        }

        public Criteria andContrasenaNotEqualTo(String value) {
            addCriterion("CONTRASENA <>", value, "contrasena");
            return (Criteria) this;
        }

        public Criteria andContrasenaGreaterThan(String value) {
            addCriterion("CONTRASENA >", value, "contrasena");
            return (Criteria) this;
        }

        public Criteria andContrasenaGreaterThanOrEqualTo(String value) {
            addCriterion("CONTRASENA >=", value, "contrasena");
            return (Criteria) this;
        }

        public Criteria andContrasenaLessThan(String value) {
            addCriterion("CONTRASENA <", value, "contrasena");
            return (Criteria) this;
        }

        public Criteria andContrasenaLessThanOrEqualTo(String value) {
            addCriterion("CONTRASENA <=", value, "contrasena");
            return (Criteria) this;
        }

        public Criteria andContrasenaLike(String value) {
            addCriterion("CONTRASENA like", value, "contrasena");
            return (Criteria) this;
        }

        public Criteria andContrasenaNotLike(String value) {
            addCriterion("CONTRASENA not like", value, "contrasena");
            return (Criteria) this;
        }

        public Criteria andContrasenaIn(List<String> values) {
            addCriterion("CONTRASENA in", values, "contrasena");
            return (Criteria) this;
        }

        public Criteria andContrasenaNotIn(List<String> values) {
            addCriterion("CONTRASENA not in", values, "contrasena");
            return (Criteria) this;
        }

        public Criteria andContrasenaBetween(String value1, String value2) {
            addCriterion("CONTRASENA between", value1, value2, "contrasena");
            return (Criteria) this;
        }

        public Criteria andContrasenaNotBetween(String value1, String value2) {
            addCriterion("CONTRASENA not between", value1, value2, "contrasena");
            return (Criteria) this;
        }

        public Criteria andRolIsNull() {
            addCriterion("ROL is null");
            return (Criteria) this;
        }

        public Criteria andRolIsNotNull() {
            addCriterion("ROL is not null");
            return (Criteria) this;
        }

        public Criteria andRolEqualTo(String value) {
            addCriterion("ROL =", value, "rol");
            return (Criteria) this;
        }

        public Criteria andRolNotEqualTo(String value) {
            addCriterion("ROL <>", value, "rol");
            return (Criteria) this;
        }

        public Criteria andRolGreaterThan(String value) {
            addCriterion("ROL >", value, "rol");
            return (Criteria) this;
        }

        public Criteria andRolGreaterThanOrEqualTo(String value) {
            addCriterion("ROL >=", value, "rol");
            return (Criteria) this;
        }

        public Criteria andRolLessThan(String value) {
            addCriterion("ROL <", value, "rol");
            return (Criteria) this;
        }

        public Criteria andRolLessThanOrEqualTo(String value) {
            addCriterion("ROL <=", value, "rol");
            return (Criteria) this;
        }

        public Criteria andRolLike(String value) {
            addCriterion("ROL like", value, "rol");
            return (Criteria) this;
        }

        public Criteria andRolNotLike(String value) {
            addCriterion("ROL not like", value, "rol");
            return (Criteria) this;
        }

        public Criteria andRolIn(List<String> values) {
            addCriterion("ROL in", values, "rol");
            return (Criteria) this;
        }

        public Criteria andRolNotIn(List<String> values) {
            addCriterion("ROL not in", values, "rol");
            return (Criteria) this;
        }

        public Criteria andRolBetween(String value1, String value2) {
            addCriterion("ROL between", value1, value2, "rol");
            return (Criteria) this;
        }

        public Criteria andRolNotBetween(String value1, String value2) {
            addCriterion("ROL not between", value1, value2, "rol");
            return (Criteria) this;
        }

        public Criteria andDescripcionIsNull() {
            addCriterion("DESCRIPCION is null");
            return (Criteria) this;
        }

        public Criteria andDescripcionIsNotNull() {
            addCriterion("DESCRIPCION is not null");
            return (Criteria) this;
        }

        public Criteria andDescripcionEqualTo(String value) {
            addCriterion("DESCRIPCION =", value, "descripcion");
            return (Criteria) this;
        }

        public Criteria andDescripcionNotEqualTo(String value) {
            addCriterion("DESCRIPCION <>", value, "descripcion");
            return (Criteria) this;
        }

        public Criteria andDescripcionGreaterThan(String value) {
            addCriterion("DESCRIPCION >", value, "descripcion");
            return (Criteria) this;
        }

        public Criteria andDescripcionGreaterThanOrEqualTo(String value) {
            addCriterion("DESCRIPCION >=", value, "descripcion");
            return (Criteria) this;
        }

        public Criteria andDescripcionLessThan(String value) {
            addCriterion("DESCRIPCION <", value, "descripcion");
            return (Criteria) this;
        }

        public Criteria andDescripcionLessThanOrEqualTo(String value) {
            addCriterion("DESCRIPCION <=", value, "descripcion");
            return (Criteria) this;
        }

        public Criteria andDescripcionLike(String value) {
            addCriterion("DESCRIPCION like", value, "descripcion");
            return (Criteria) this;
        }

        public Criteria andDescripcionNotLike(String value) {
            addCriterion("DESCRIPCION not like", value, "descripcion");
            return (Criteria) this;
        }

        public Criteria andDescripcionIn(List<String> values) {
            addCriterion("DESCRIPCION in", values, "descripcion");
            return (Criteria) this;
        }

        public Criteria andDescripcionNotIn(List<String> values) {
            addCriterion("DESCRIPCION not in", values, "descripcion");
            return (Criteria) this;
        }

        public Criteria andDescripcionBetween(String value1, String value2) {
            addCriterion("DESCRIPCION between", value1, value2, "descripcion");
            return (Criteria) this;
        }

        public Criteria andDescripcionNotBetween(String value1, String value2) {
            addCriterion("DESCRIPCION not between", value1, value2, "descripcion");
            return (Criteria) this;
        }

        public Criteria andNoGerenteIsNull() {
            addCriterion("NO_GERENTE is null");
            return (Criteria) this;
        }

        public Criteria andNoGerenteIsNotNull() {
            addCriterion("NO_GERENTE is not null");
            return (Criteria) this;
        }

        public Criteria andNoGerenteEqualTo(String value) {
            addCriterion("NO_GERENTE =", value, "noGerente");
            return (Criteria) this;
        }

        public Criteria andNoGerenteNotEqualTo(String value) {
            addCriterion("NO_GERENTE <>", value, "noGerente");
            return (Criteria) this;
        }

        public Criteria andNoGerenteGreaterThan(String value) {
            addCriterion("NO_GERENTE >", value, "noGerente");
            return (Criteria) this;
        }

        public Criteria andNoGerenteGreaterThanOrEqualTo(String value) {
            addCriterion("NO_GERENTE >=", value, "noGerente");
            return (Criteria) this;
        }

        public Criteria andNoGerenteLessThan(String value) {
            addCriterion("NO_GERENTE <", value, "noGerente");
            return (Criteria) this;
        }

        public Criteria andNoGerenteLessThanOrEqualTo(String value) {
            addCriterion("NO_GERENTE <=", value, "noGerente");
            return (Criteria) this;
        }

        public Criteria andNoGerenteLike(String value) {
            addCriterion("NO_GERENTE like", value, "noGerente");
            return (Criteria) this;
        }

        public Criteria andNoGerenteNotLike(String value) {
            addCriterion("NO_GERENTE not like", value, "noGerente");
            return (Criteria) this;
        }

        public Criteria andNoGerenteIn(List<String> values) {
            addCriterion("NO_GERENTE in", values, "noGerente");
            return (Criteria) this;
        }

        public Criteria andNoGerenteNotIn(List<String> values) {
            addCriterion("NO_GERENTE not in", values, "noGerente");
            return (Criteria) this;
        }

        public Criteria andNoGerenteBetween(String value1, String value2) {
            addCriterion("NO_GERENTE between", value1, value2, "noGerente");
            return (Criteria) this;
        }

        public Criteria andNoGerenteNotBetween(String value1, String value2) {
            addCriterion("NO_GERENTE not between", value1, value2, "noGerente");
            return (Criteria) this;
        }

        public Criteria andActivoIsNull() {
            addCriterion("ACTIVO is null");
            return (Criteria) this;
        }

        public Criteria andActivoIsNotNull() {
            addCriterion("ACTIVO is not null");
            return (Criteria) this;
        }

        public Criteria andActivoEqualTo(String value) {
            addCriterion("ACTIVO =", value, "activo");
            return (Criteria) this;
        }

        public Criteria andActivoNotEqualTo(String value) {
            addCriterion("ACTIVO <>", value, "activo");
            return (Criteria) this;
        }

        public Criteria andActivoGreaterThan(String value) {
            addCriterion("ACTIVO >", value, "activo");
            return (Criteria) this;
        }

        public Criteria andActivoGreaterThanOrEqualTo(String value) {
            addCriterion("ACTIVO >=", value, "activo");
            return (Criteria) this;
        }

        public Criteria andActivoLessThan(String value) {
            addCriterion("ACTIVO <", value, "activo");
            return (Criteria) this;
        }

        public Criteria andActivoLessThanOrEqualTo(String value) {
            addCriterion("ACTIVO <=", value, "activo");
            return (Criteria) this;
        }

        public Criteria andActivoLike(String value) {
            addCriterion("ACTIVO like", value, "activo");
            return (Criteria) this;
        }

        public Criteria andActivoNotLike(String value) {
            addCriterion("ACTIVO not like", value, "activo");
            return (Criteria) this;
        }

        public Criteria andActivoIn(List<String> values) {
            addCriterion("ACTIVO in", values, "activo");
            return (Criteria) this;
        }

        public Criteria andActivoNotIn(List<String> values) {
            addCriterion("ACTIVO not in", values, "activo");
            return (Criteria) this;
        }

        public Criteria andActivoBetween(String value1, String value2) {
            addCriterion("ACTIVO between", value1, value2, "activo");
            return (Criteria) this;
        }

        public Criteria andActivoNotBetween(String value1, String value2) {
            addCriterion("ACTIVO not between", value1, value2, "activo");
            return (Criteria) this;
        }

        public Criteria andCdPerfilPerUsuIsNull() {
            addCriterion("CD_PERFIL_PER_USU is null");
            return (Criteria) this;
        }

        public Criteria andCdPerfilPerUsuIsNotNull() {
            addCriterion("CD_PERFIL_PER_USU is not null");
            return (Criteria) this;
        }

        public Criteria andCdPerfilPerUsuEqualTo(BigDecimal value) {
            addCriterion("CD_PERFIL_PER_USU =", value, "cdPerfilPerUsu");
            return (Criteria) this;
        }

        public Criteria andCdPerfilPerUsuNotEqualTo(BigDecimal value) {
            addCriterion("CD_PERFIL_PER_USU <>", value, "cdPerfilPerUsu");
            return (Criteria) this;
        }

        public Criteria andCdPerfilPerUsuGreaterThan(BigDecimal value) {
            addCriterion("CD_PERFIL_PER_USU >", value, "cdPerfilPerUsu");
            return (Criteria) this;
        }

        public Criteria andCdPerfilPerUsuGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("CD_PERFIL_PER_USU >=", value, "cdPerfilPerUsu");
            return (Criteria) this;
        }

        public Criteria andCdPerfilPerUsuLessThan(BigDecimal value) {
            addCriterion("CD_PERFIL_PER_USU <", value, "cdPerfilPerUsu");
            return (Criteria) this;
        }

        public Criteria andCdPerfilPerUsuLessThanOrEqualTo(BigDecimal value) {
            addCriterion("CD_PERFIL_PER_USU <=", value, "cdPerfilPerUsu");
            return (Criteria) this;
        }

        public Criteria andCdPerfilPerUsuIn(List<BigDecimal> values) {
            addCriterion("CD_PERFIL_PER_USU in", values, "cdPerfilPerUsu");
            return (Criteria) this;
        }

        public Criteria andCdPerfilPerUsuNotIn(List<BigDecimal> values) {
            addCriterion("CD_PERFIL_PER_USU not in", values, "cdPerfilPerUsu");
            return (Criteria) this;
        }

        public Criteria andCdPerfilPerUsuBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("CD_PERFIL_PER_USU between", value1, value2, "cdPerfilPerUsu");
            return (Criteria) this;
        }

        public Criteria andCdPerfilPerUsuNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("CD_PERFIL_PER_USU not between", value1, value2, "cdPerfilPerUsu");
            return (Criteria) this;
        }

        public Criteria andTxCorreoUsuIsNull() {
            addCriterion("TX_CORREO_USU is null");
            return (Criteria) this;
        }

        public Criteria andTxCorreoUsuIsNotNull() {
            addCriterion("TX_CORREO_USU is not null");
            return (Criteria) this;
        }

        public Criteria andTxCorreoUsuEqualTo(String value) {
            addCriterion("TX_CORREO_USU =", value, "txCorreoUsu");
            return (Criteria) this;
        }

        public Criteria andTxCorreoUsuNotEqualTo(String value) {
            addCriterion("TX_CORREO_USU <>", value, "txCorreoUsu");
            return (Criteria) this;
        }

        public Criteria andTxCorreoUsuGreaterThan(String value) {
            addCriterion("TX_CORREO_USU >", value, "txCorreoUsu");
            return (Criteria) this;
        }

        public Criteria andTxCorreoUsuGreaterThanOrEqualTo(String value) {
            addCriterion("TX_CORREO_USU >=", value, "txCorreoUsu");
            return (Criteria) this;
        }

        public Criteria andTxCorreoUsuLessThan(String value) {
            addCriterion("TX_CORREO_USU <", value, "txCorreoUsu");
            return (Criteria) this;
        }

        public Criteria andTxCorreoUsuLessThanOrEqualTo(String value) {
            addCriterion("TX_CORREO_USU <=", value, "txCorreoUsu");
            return (Criteria) this;
        }

        public Criteria andTxCorreoUsuLike(String value) {
            addCriterion("TX_CORREO_USU like", value, "txCorreoUsu");
            return (Criteria) this;
        }

        public Criteria andTxCorreoUsuNotLike(String value) {
            addCriterion("TX_CORREO_USU not like", value, "txCorreoUsu");
            return (Criteria) this;
        }

        public Criteria andTxCorreoUsuIn(List<String> values) {
            addCriterion("TX_CORREO_USU in", values, "txCorreoUsu");
            return (Criteria) this;
        }

        public Criteria andTxCorreoUsuNotIn(List<String> values) {
            addCriterion("TX_CORREO_USU not in", values, "txCorreoUsu");
            return (Criteria) this;
        }

        public Criteria andTxCorreoUsuBetween(String value1, String value2) {
            addCriterion("TX_CORREO_USU between", value1, value2, "txCorreoUsu");
            return (Criteria) this;
        }

        public Criteria andTxCorreoUsuNotBetween(String value1, String value2) {
            addCriterion("TX_CORREO_USU not between", value1, value2, "txCorreoUsu");
            return (Criteria) this;
        }

        public Criteria andNoCiaIsNull() {
            addCriterion("NO_CIA is null");
            return (Criteria) this;
        }

        public Criteria andNoCiaIsNotNull() {
            addCriterion("NO_CIA is not null");
            return (Criteria) this;
        }

        public Criteria andNoCiaEqualTo(String value) {
            addCriterion("NO_CIA =", value, "noCia");
            return (Criteria) this;
        }

        public Criteria andNoCiaNotEqualTo(String value) {
            addCriterion("NO_CIA <>", value, "noCia");
            return (Criteria) this;
        }

        public Criteria andNoCiaGreaterThan(String value) {
            addCriterion("NO_CIA >", value, "noCia");
            return (Criteria) this;
        }

        public Criteria andNoCiaGreaterThanOrEqualTo(String value) {
            addCriterion("NO_CIA >=", value, "noCia");
            return (Criteria) this;
        }

        public Criteria andNoCiaLessThan(String value) {
            addCriterion("NO_CIA <", value, "noCia");
            return (Criteria) this;
        }

        public Criteria andNoCiaLessThanOrEqualTo(String value) {
            addCriterion("NO_CIA <=", value, "noCia");
            return (Criteria) this;
        }

        public Criteria andNoCiaLike(String value) {
            addCriterion("NO_CIA like", value, "noCia");
            return (Criteria) this;
        }

        public Criteria andNoCiaNotLike(String value) {
            addCriterion("NO_CIA not like", value, "noCia");
            return (Criteria) this;
        }

        public Criteria andNoCiaIn(List<String> values) {
            addCriterion("NO_CIA in", values, "noCia");
            return (Criteria) this;
        }

        public Criteria andNoCiaNotIn(List<String> values) {
            addCriterion("NO_CIA not in", values, "noCia");
            return (Criteria) this;
        }

        public Criteria andNoCiaBetween(String value1, String value2) {
            addCriterion("NO_CIA between", value1, value2, "noCia");
            return (Criteria) this;
        }

        public Criteria andNoCiaNotBetween(String value1, String value2) {
            addCriterion("NO_CIA not between", value1, value2, "noCia");
            return (Criteria) this;
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("ID like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("ID not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table NAF6.PD_USUARIO
     *
     * @mbggenerated do_not_delete_during_merge Tue Apr 21 12:41:59 COT 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table NAF6.PD_USUARIO
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}