package com.fi.crm.campaigns.persistence.model;

public class PvclientesKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NAF6.PVCLIENTES.NO_CIA
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    private String noCia;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NAF6.PVCLIENTES.COD_CLIENTE
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    private String codCliente;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NAF6.PVCLIENTES.NO_CIA
     *
     * @return the value of NAF6.PVCLIENTES.NO_CIA
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public String getNoCia() {
        return noCia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NAF6.PVCLIENTES.NO_CIA
     *
     * @param noCia the value for NAF6.PVCLIENTES.NO_CIA
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public void setNoCia(String noCia) {
        this.noCia = noCia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NAF6.PVCLIENTES.COD_CLIENTE
     *
     * @return the value of NAF6.PVCLIENTES.COD_CLIENTE
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public String getCodCliente() {
        return codCliente;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NAF6.PVCLIENTES.COD_CLIENTE
     *
     * @param codCliente the value for NAF6.PVCLIENTES.COD_CLIENTE
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public void setCodCliente(String codCliente) {
        this.codCliente = codCliente;
    }
}