package com.fi.crm.campaigns.persistence.model;

public class Pvtiendassvy {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PVTIENDASSVY.CENTRO
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    private String centro;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PVTIENDASSVY.NOMBRE
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    private String nombre;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PVTIENDASSVY.NO_CIA
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    private String noCia;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PVTIENDASSVY.COD_NEGOCIO
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    private String codNegocio;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PVTIENDASSVY.DIRECCION
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    private String direccion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PVTIENDASSVY.TELEFONO
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    private String telefono;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PVTIENDASSVY.CENTRO
     *
     * @return the value of PVTIENDASSVY.CENTRO
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public String getCentro() {
        return centro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PVTIENDASSVY.CENTRO
     *
     * @param centro the value for PVTIENDASSVY.CENTRO
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public void setCentro(String centro) {
        this.centro = centro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PVTIENDASSVY.NOMBRE
     *
     * @return the value of PVTIENDASSVY.NOMBRE
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public String getNombre() {
        return nombre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PVTIENDASSVY.NOMBRE
     *
     * @param nombre the value for PVTIENDASSVY.NOMBRE
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PVTIENDASSVY.NO_CIA
     *
     * @return the value of PVTIENDASSVY.NO_CIA
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public String getNoCia() {
        return noCia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PVTIENDASSVY.NO_CIA
     *
     * @param noCia the value for PVTIENDASSVY.NO_CIA
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public void setNoCia(String noCia) {
        this.noCia = noCia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PVTIENDASSVY.COD_NEGOCIO
     *
     * @return the value of PVTIENDASSVY.COD_NEGOCIO
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public String getCodNegocio() {
        return codNegocio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PVTIENDASSVY.COD_NEGOCIO
     *
     * @param codNegocio the value for PVTIENDASSVY.COD_NEGOCIO
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public void setCodNegocio(String codNegocio) {
        this.codNegocio = codNegocio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PVTIENDASSVY.DIRECCION
     *
     * @return the value of PVTIENDASSVY.DIRECCION
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public String getDireccion() {
        return direccion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PVTIENDASSVY.DIRECCION
     *
     * @param direccion the value for PVTIENDASSVY.DIRECCION
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PVTIENDASSVY.TELEFONO
     *
     * @return the value of PVTIENDASSVY.TELEFONO
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public String getTelefono() {
        return telefono;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PVTIENDASSVY.TELEFONO
     *
     * @param telefono the value for PVTIENDASSVY.TELEFONO
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
}