package com.fi.crm.campaigns.persistence.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class PvusuariosExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table NAF6.PVUSUARIOS
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table NAF6.PVUSUARIOS
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table NAF6.PVUSUARIOS
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NAF6.PVUSUARIOS
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public PvusuariosExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NAF6.PVUSUARIOS
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NAF6.PVUSUARIOS
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NAF6.PVUSUARIOS
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NAF6.PVUSUARIOS
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NAF6.PVUSUARIOS
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NAF6.PVUSUARIOS
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NAF6.PVUSUARIOS
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NAF6.PVUSUARIOS
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NAF6.PVUSUARIOS
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NAF6.PVUSUARIOS
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table NAF6.PVUSUARIOS
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCodUsuarioIsNull() {
            addCriterion("COD_USUARIO is null");
            return (Criteria) this;
        }

        public Criteria andCodUsuarioIsNotNull() {
            addCriterion("COD_USUARIO is not null");
            return (Criteria) this;
        }

        public Criteria andCodUsuarioEqualTo(String value) {
            addCriterion("COD_USUARIO =", value, "codUsuario");
            return (Criteria) this;
        }

        public Criteria andCodUsuarioNotEqualTo(String value) {
            addCriterion("COD_USUARIO <>", value, "codUsuario");
            return (Criteria) this;
        }

        public Criteria andCodUsuarioGreaterThan(String value) {
            addCriterion("COD_USUARIO >", value, "codUsuario");
            return (Criteria) this;
        }

        public Criteria andCodUsuarioGreaterThanOrEqualTo(String value) {
            addCriterion("COD_USUARIO >=", value, "codUsuario");
            return (Criteria) this;
        }

        public Criteria andCodUsuarioLessThan(String value) {
            addCriterion("COD_USUARIO <", value, "codUsuario");
            return (Criteria) this;
        }

        public Criteria andCodUsuarioLessThanOrEqualTo(String value) {
            addCriterion("COD_USUARIO <=", value, "codUsuario");
            return (Criteria) this;
        }

        public Criteria andCodUsuarioLike(String value) {
            addCriterion("COD_USUARIO like", value, "codUsuario");
            return (Criteria) this;
        }

        public Criteria andCodUsuarioNotLike(String value) {
            addCriterion("COD_USUARIO not like", value, "codUsuario");
            return (Criteria) this;
        }

        public Criteria andCodUsuarioIn(List<String> values) {
            addCriterion("COD_USUARIO in", values, "codUsuario");
            return (Criteria) this;
        }

        public Criteria andCodUsuarioNotIn(List<String> values) {
            addCriterion("COD_USUARIO not in", values, "codUsuario");
            return (Criteria) this;
        }

        public Criteria andCodUsuarioBetween(String value1, String value2) {
            addCriterion("COD_USUARIO between", value1, value2, "codUsuario");
            return (Criteria) this;
        }

        public Criteria andCodUsuarioNotBetween(String value1, String value2) {
            addCriterion("COD_USUARIO not between", value1, value2, "codUsuario");
            return (Criteria) this;
        }

        public Criteria andNombreIsNull() {
            addCriterion("NOMBRE is null");
            return (Criteria) this;
        }

        public Criteria andNombreIsNotNull() {
            addCriterion("NOMBRE is not null");
            return (Criteria) this;
        }

        public Criteria andNombreEqualTo(String value) {
            addCriterion("NOMBRE =", value, "nombre");
            return (Criteria) this;
        }

        public Criteria andNombreNotEqualTo(String value) {
            addCriterion("NOMBRE <>", value, "nombre");
            return (Criteria) this;
        }

        public Criteria andNombreGreaterThan(String value) {
            addCriterion("NOMBRE >", value, "nombre");
            return (Criteria) this;
        }

        public Criteria andNombreGreaterThanOrEqualTo(String value) {
            addCriterion("NOMBRE >=", value, "nombre");
            return (Criteria) this;
        }

        public Criteria andNombreLessThan(String value) {
            addCriterion("NOMBRE <", value, "nombre");
            return (Criteria) this;
        }

        public Criteria andNombreLessThanOrEqualTo(String value) {
            addCriterion("NOMBRE <=", value, "nombre");
            return (Criteria) this;
        }

        public Criteria andNombreLike(String value) {
            addCriterion("NOMBRE like", value, "nombre");
            return (Criteria) this;
        }

        public Criteria andNombreNotLike(String value) {
            addCriterion("NOMBRE not like", value, "nombre");
            return (Criteria) this;
        }

        public Criteria andNombreIn(List<String> values) {
            addCriterion("NOMBRE in", values, "nombre");
            return (Criteria) this;
        }

        public Criteria andNombreNotIn(List<String> values) {
            addCriterion("NOMBRE not in", values, "nombre");
            return (Criteria) this;
        }

        public Criteria andNombreBetween(String value1, String value2) {
            addCriterion("NOMBRE between", value1, value2, "nombre");
            return (Criteria) this;
        }

        public Criteria andNombreNotBetween(String value1, String value2) {
            addCriterion("NOMBRE not between", value1, value2, "nombre");
            return (Criteria) this;
        }

        public Criteria andRolIsNull() {
            addCriterion("ROL is null");
            return (Criteria) this;
        }

        public Criteria andRolIsNotNull() {
            addCriterion("ROL is not null");
            return (Criteria) this;
        }

        public Criteria andRolEqualTo(String value) {
            addCriterion("ROL =", value, "rol");
            return (Criteria) this;
        }

        public Criteria andRolNotEqualTo(String value) {
            addCriterion("ROL <>", value, "rol");
            return (Criteria) this;
        }

        public Criteria andRolGreaterThan(String value) {
            addCriterion("ROL >", value, "rol");
            return (Criteria) this;
        }

        public Criteria andRolGreaterThanOrEqualTo(String value) {
            addCriterion("ROL >=", value, "rol");
            return (Criteria) this;
        }

        public Criteria andRolLessThan(String value) {
            addCriterion("ROL <", value, "rol");
            return (Criteria) this;
        }

        public Criteria andRolLessThanOrEqualTo(String value) {
            addCriterion("ROL <=", value, "rol");
            return (Criteria) this;
        }

        public Criteria andRolLike(String value) {
            addCriterion("ROL like", value, "rol");
            return (Criteria) this;
        }

        public Criteria andRolNotLike(String value) {
            addCriterion("ROL not like", value, "rol");
            return (Criteria) this;
        }

        public Criteria andRolIn(List<String> values) {
            addCriterion("ROL in", values, "rol");
            return (Criteria) this;
        }

        public Criteria andRolNotIn(List<String> values) {
            addCriterion("ROL not in", values, "rol");
            return (Criteria) this;
        }

        public Criteria andRolBetween(String value1, String value2) {
            addCriterion("ROL between", value1, value2, "rol");
            return (Criteria) this;
        }

        public Criteria andRolNotBetween(String value1, String value2) {
            addCriterion("ROL not between", value1, value2, "rol");
            return (Criteria) this;
        }

        public Criteria andPinIsNull() {
            addCriterion("PIN is null");
            return (Criteria) this;
        }

        public Criteria andPinIsNotNull() {
            addCriterion("PIN is not null");
            return (Criteria) this;
        }

        public Criteria andPinEqualTo(String value) {
            addCriterion("PIN =", value, "pin");
            return (Criteria) this;
        }

        public Criteria andPinNotEqualTo(String value) {
            addCriterion("PIN <>", value, "pin");
            return (Criteria) this;
        }

        public Criteria andPinGreaterThan(String value) {
            addCriterion("PIN >", value, "pin");
            return (Criteria) this;
        }

        public Criteria andPinGreaterThanOrEqualTo(String value) {
            addCriterion("PIN >=", value, "pin");
            return (Criteria) this;
        }

        public Criteria andPinLessThan(String value) {
            addCriterion("PIN <", value, "pin");
            return (Criteria) this;
        }

        public Criteria andPinLessThanOrEqualTo(String value) {
            addCriterion("PIN <=", value, "pin");
            return (Criteria) this;
        }

        public Criteria andPinLike(String value) {
            addCriterion("PIN like", value, "pin");
            return (Criteria) this;
        }

        public Criteria andPinNotLike(String value) {
            addCriterion("PIN not like", value, "pin");
            return (Criteria) this;
        }

        public Criteria andPinIn(List<String> values) {
            addCriterion("PIN in", values, "pin");
            return (Criteria) this;
        }

        public Criteria andPinNotIn(List<String> values) {
            addCriterion("PIN not in", values, "pin");
            return (Criteria) this;
        }

        public Criteria andPinBetween(String value1, String value2) {
            addCriterion("PIN between", value1, value2, "pin");
            return (Criteria) this;
        }

        public Criteria andPinNotBetween(String value1, String value2) {
            addCriterion("PIN not between", value1, value2, "pin");
            return (Criteria) this;
        }

        public Criteria andClaveAccesoIsNull() {
            addCriterion("CLAVE_ACCESO is null");
            return (Criteria) this;
        }

        public Criteria andClaveAccesoIsNotNull() {
            addCriterion("CLAVE_ACCESO is not null");
            return (Criteria) this;
        }

        public Criteria andClaveAccesoEqualTo(String value) {
            addCriterion("CLAVE_ACCESO =", value, "claveAcceso");
            return (Criteria) this;
        }

        public Criteria andClaveAccesoNotEqualTo(String value) {
            addCriterion("CLAVE_ACCESO <>", value, "claveAcceso");
            return (Criteria) this;
        }

        public Criteria andClaveAccesoGreaterThan(String value) {
            addCriterion("CLAVE_ACCESO >", value, "claveAcceso");
            return (Criteria) this;
        }

        public Criteria andClaveAccesoGreaterThanOrEqualTo(String value) {
            addCriterion("CLAVE_ACCESO >=", value, "claveAcceso");
            return (Criteria) this;
        }

        public Criteria andClaveAccesoLessThan(String value) {
            addCriterion("CLAVE_ACCESO <", value, "claveAcceso");
            return (Criteria) this;
        }

        public Criteria andClaveAccesoLessThanOrEqualTo(String value) {
            addCriterion("CLAVE_ACCESO <=", value, "claveAcceso");
            return (Criteria) this;
        }

        public Criteria andClaveAccesoLike(String value) {
            addCriterion("CLAVE_ACCESO like", value, "claveAcceso");
            return (Criteria) this;
        }

        public Criteria andClaveAccesoNotLike(String value) {
            addCriterion("CLAVE_ACCESO not like", value, "claveAcceso");
            return (Criteria) this;
        }

        public Criteria andClaveAccesoIn(List<String> values) {
            addCriterion("CLAVE_ACCESO in", values, "claveAcceso");
            return (Criteria) this;
        }

        public Criteria andClaveAccesoNotIn(List<String> values) {
            addCriterion("CLAVE_ACCESO not in", values, "claveAcceso");
            return (Criteria) this;
        }

        public Criteria andClaveAccesoBetween(String value1, String value2) {
            addCriterion("CLAVE_ACCESO between", value1, value2, "claveAcceso");
            return (Criteria) this;
        }

        public Criteria andClaveAccesoNotBetween(String value1, String value2) {
            addCriterion("CLAVE_ACCESO not between", value1, value2, "claveAcceso");
            return (Criteria) this;
        }

        public Criteria andCodCarnetIsNull() {
            addCriterion("COD_CARNET is null");
            return (Criteria) this;
        }

        public Criteria andCodCarnetIsNotNull() {
            addCriterion("COD_CARNET is not null");
            return (Criteria) this;
        }

        public Criteria andCodCarnetEqualTo(String value) {
            addCriterion("COD_CARNET =", value, "codCarnet");
            return (Criteria) this;
        }

        public Criteria andCodCarnetNotEqualTo(String value) {
            addCriterion("COD_CARNET <>", value, "codCarnet");
            return (Criteria) this;
        }

        public Criteria andCodCarnetGreaterThan(String value) {
            addCriterion("COD_CARNET >", value, "codCarnet");
            return (Criteria) this;
        }

        public Criteria andCodCarnetGreaterThanOrEqualTo(String value) {
            addCriterion("COD_CARNET >=", value, "codCarnet");
            return (Criteria) this;
        }

        public Criteria andCodCarnetLessThan(String value) {
            addCriterion("COD_CARNET <", value, "codCarnet");
            return (Criteria) this;
        }

        public Criteria andCodCarnetLessThanOrEqualTo(String value) {
            addCriterion("COD_CARNET <=", value, "codCarnet");
            return (Criteria) this;
        }

        public Criteria andCodCarnetLike(String value) {
            addCriterion("COD_CARNET like", value, "codCarnet");
            return (Criteria) this;
        }

        public Criteria andCodCarnetNotLike(String value) {
            addCriterion("COD_CARNET not like", value, "codCarnet");
            return (Criteria) this;
        }

        public Criteria andCodCarnetIn(List<String> values) {
            addCriterion("COD_CARNET in", values, "codCarnet");
            return (Criteria) this;
        }

        public Criteria andCodCarnetNotIn(List<String> values) {
            addCriterion("COD_CARNET not in", values, "codCarnet");
            return (Criteria) this;
        }

        public Criteria andCodCarnetBetween(String value1, String value2) {
            addCriterion("COD_CARNET between", value1, value2, "codCarnet");
            return (Criteria) this;
        }

        public Criteria andCodCarnetNotBetween(String value1, String value2) {
            addCriterion("COD_CARNET not between", value1, value2, "codCarnet");
            return (Criteria) this;
        }

        public Criteria andClaveAutorizacionIsNull() {
            addCriterion("CLAVE_AUTORIZACION is null");
            return (Criteria) this;
        }

        public Criteria andClaveAutorizacionIsNotNull() {
            addCriterion("CLAVE_AUTORIZACION is not null");
            return (Criteria) this;
        }

        public Criteria andClaveAutorizacionEqualTo(String value) {
            addCriterion("CLAVE_AUTORIZACION =", value, "claveAutorizacion");
            return (Criteria) this;
        }

        public Criteria andClaveAutorizacionNotEqualTo(String value) {
            addCriterion("CLAVE_AUTORIZACION <>", value, "claveAutorizacion");
            return (Criteria) this;
        }

        public Criteria andClaveAutorizacionGreaterThan(String value) {
            addCriterion("CLAVE_AUTORIZACION >", value, "claveAutorizacion");
            return (Criteria) this;
        }

        public Criteria andClaveAutorizacionGreaterThanOrEqualTo(String value) {
            addCriterion("CLAVE_AUTORIZACION >=", value, "claveAutorizacion");
            return (Criteria) this;
        }

        public Criteria andClaveAutorizacionLessThan(String value) {
            addCriterion("CLAVE_AUTORIZACION <", value, "claveAutorizacion");
            return (Criteria) this;
        }

        public Criteria andClaveAutorizacionLessThanOrEqualTo(String value) {
            addCriterion("CLAVE_AUTORIZACION <=", value, "claveAutorizacion");
            return (Criteria) this;
        }

        public Criteria andClaveAutorizacionLike(String value) {
            addCriterion("CLAVE_AUTORIZACION like", value, "claveAutorizacion");
            return (Criteria) this;
        }

        public Criteria andClaveAutorizacionNotLike(String value) {
            addCriterion("CLAVE_AUTORIZACION not like", value, "claveAutorizacion");
            return (Criteria) this;
        }

        public Criteria andClaveAutorizacionIn(List<String> values) {
            addCriterion("CLAVE_AUTORIZACION in", values, "claveAutorizacion");
            return (Criteria) this;
        }

        public Criteria andClaveAutorizacionNotIn(List<String> values) {
            addCriterion("CLAVE_AUTORIZACION not in", values, "claveAutorizacion");
            return (Criteria) this;
        }

        public Criteria andClaveAutorizacionBetween(String value1, String value2) {
            addCriterion("CLAVE_AUTORIZACION between", value1, value2, "claveAutorizacion");
            return (Criteria) this;
        }

        public Criteria andClaveAutorizacionNotBetween(String value1, String value2) {
            addCriterion("CLAVE_AUTORIZACION not between", value1, value2, "claveAutorizacion");
            return (Criteria) this;
        }

        public Criteria andFClaveExpiraIsNull() {
            addCriterion("F_CLAVE_EXPIRA is null");
            return (Criteria) this;
        }

        public Criteria andFClaveExpiraIsNotNull() {
            addCriterion("F_CLAVE_EXPIRA is not null");
            return (Criteria) this;
        }

        public Criteria andFClaveExpiraEqualTo(Date value) {
            addCriterion("F_CLAVE_EXPIRA =", value, "fClaveExpira");
            return (Criteria) this;
        }

        public Criteria andFClaveExpiraNotEqualTo(Date value) {
            addCriterion("F_CLAVE_EXPIRA <>", value, "fClaveExpira");
            return (Criteria) this;
        }

        public Criteria andFClaveExpiraGreaterThan(Date value) {
            addCriterion("F_CLAVE_EXPIRA >", value, "fClaveExpira");
            return (Criteria) this;
        }

        public Criteria andFClaveExpiraGreaterThanOrEqualTo(Date value) {
            addCriterion("F_CLAVE_EXPIRA >=", value, "fClaveExpira");
            return (Criteria) this;
        }

        public Criteria andFClaveExpiraLessThan(Date value) {
            addCriterion("F_CLAVE_EXPIRA <", value, "fClaveExpira");
            return (Criteria) this;
        }

        public Criteria andFClaveExpiraLessThanOrEqualTo(Date value) {
            addCriterion("F_CLAVE_EXPIRA <=", value, "fClaveExpira");
            return (Criteria) this;
        }

        public Criteria andFClaveExpiraIn(List<Date> values) {
            addCriterion("F_CLAVE_EXPIRA in", values, "fClaveExpira");
            return (Criteria) this;
        }

        public Criteria andFClaveExpiraNotIn(List<Date> values) {
            addCriterion("F_CLAVE_EXPIRA not in", values, "fClaveExpira");
            return (Criteria) this;
        }

        public Criteria andFClaveExpiraBetween(Date value1, Date value2) {
            addCriterion("F_CLAVE_EXPIRA between", value1, value2, "fClaveExpira");
            return (Criteria) this;
        }

        public Criteria andFClaveExpiraNotBetween(Date value1, Date value2) {
            addCriterion("F_CLAVE_EXPIRA not between", value1, value2, "fClaveExpira");
            return (Criteria) this;
        }

        public Criteria andFrecuenciaCambioClaveIsNull() {
            addCriterion("FRECUENCIA_CAMBIO_CLAVE is null");
            return (Criteria) this;
        }

        public Criteria andFrecuenciaCambioClaveIsNotNull() {
            addCriterion("FRECUENCIA_CAMBIO_CLAVE is not null");
            return (Criteria) this;
        }

        public Criteria andFrecuenciaCambioClaveEqualTo(String value) {
            addCriterion("FRECUENCIA_CAMBIO_CLAVE =", value, "frecuenciaCambioClave");
            return (Criteria) this;
        }

        public Criteria andFrecuenciaCambioClaveNotEqualTo(String value) {
            addCriterion("FRECUENCIA_CAMBIO_CLAVE <>", value, "frecuenciaCambioClave");
            return (Criteria) this;
        }

        public Criteria andFrecuenciaCambioClaveGreaterThan(String value) {
            addCriterion("FRECUENCIA_CAMBIO_CLAVE >", value, "frecuenciaCambioClave");
            return (Criteria) this;
        }

        public Criteria andFrecuenciaCambioClaveGreaterThanOrEqualTo(String value) {
            addCriterion("FRECUENCIA_CAMBIO_CLAVE >=", value, "frecuenciaCambioClave");
            return (Criteria) this;
        }

        public Criteria andFrecuenciaCambioClaveLessThan(String value) {
            addCriterion("FRECUENCIA_CAMBIO_CLAVE <", value, "frecuenciaCambioClave");
            return (Criteria) this;
        }

        public Criteria andFrecuenciaCambioClaveLessThanOrEqualTo(String value) {
            addCriterion("FRECUENCIA_CAMBIO_CLAVE <=", value, "frecuenciaCambioClave");
            return (Criteria) this;
        }

        public Criteria andFrecuenciaCambioClaveLike(String value) {
            addCriterion("FRECUENCIA_CAMBIO_CLAVE like", value, "frecuenciaCambioClave");
            return (Criteria) this;
        }

        public Criteria andFrecuenciaCambioClaveNotLike(String value) {
            addCriterion("FRECUENCIA_CAMBIO_CLAVE not like", value, "frecuenciaCambioClave");
            return (Criteria) this;
        }

        public Criteria andFrecuenciaCambioClaveIn(List<String> values) {
            addCriterion("FRECUENCIA_CAMBIO_CLAVE in", values, "frecuenciaCambioClave");
            return (Criteria) this;
        }

        public Criteria andFrecuenciaCambioClaveNotIn(List<String> values) {
            addCriterion("FRECUENCIA_CAMBIO_CLAVE not in", values, "frecuenciaCambioClave");
            return (Criteria) this;
        }

        public Criteria andFrecuenciaCambioClaveBetween(String value1, String value2) {
            addCriterion("FRECUENCIA_CAMBIO_CLAVE between", value1, value2, "frecuenciaCambioClave");
            return (Criteria) this;
        }

        public Criteria andFrecuenciaCambioClaveNotBetween(String value1, String value2) {
            addCriterion("FRECUENCIA_CAMBIO_CLAVE not between", value1, value2, "frecuenciaCambioClave");
            return (Criteria) this;
        }

        public Criteria andTiempoCambioIsNull() {
            addCriterion("TIEMPO_CAMBIO is null");
            return (Criteria) this;
        }

        public Criteria andTiempoCambioIsNotNull() {
            addCriterion("TIEMPO_CAMBIO is not null");
            return (Criteria) this;
        }

        public Criteria andTiempoCambioEqualTo(Short value) {
            addCriterion("TIEMPO_CAMBIO =", value, "tiempoCambio");
            return (Criteria) this;
        }

        public Criteria andTiempoCambioNotEqualTo(Short value) {
            addCriterion("TIEMPO_CAMBIO <>", value, "tiempoCambio");
            return (Criteria) this;
        }

        public Criteria andTiempoCambioGreaterThan(Short value) {
            addCriterion("TIEMPO_CAMBIO >", value, "tiempoCambio");
            return (Criteria) this;
        }

        public Criteria andTiempoCambioGreaterThanOrEqualTo(Short value) {
            addCriterion("TIEMPO_CAMBIO >=", value, "tiempoCambio");
            return (Criteria) this;
        }

        public Criteria andTiempoCambioLessThan(Short value) {
            addCriterion("TIEMPO_CAMBIO <", value, "tiempoCambio");
            return (Criteria) this;
        }

        public Criteria andTiempoCambioLessThanOrEqualTo(Short value) {
            addCriterion("TIEMPO_CAMBIO <=", value, "tiempoCambio");
            return (Criteria) this;
        }

        public Criteria andTiempoCambioIn(List<Short> values) {
            addCriterion("TIEMPO_CAMBIO in", values, "tiempoCambio");
            return (Criteria) this;
        }

        public Criteria andTiempoCambioNotIn(List<Short> values) {
            addCriterion("TIEMPO_CAMBIO not in", values, "tiempoCambio");
            return (Criteria) this;
        }

        public Criteria andTiempoCambioBetween(Short value1, Short value2) {
            addCriterion("TIEMPO_CAMBIO between", value1, value2, "tiempoCambio");
            return (Criteria) this;
        }

        public Criteria andTiempoCambioNotBetween(Short value1, Short value2) {
            addCriterion("TIEMPO_CAMBIO not between", value1, value2, "tiempoCambio");
            return (Criteria) this;
        }

        public Criteria andDiasGraciaIsNull() {
            addCriterion("DIAS_GRACIA is null");
            return (Criteria) this;
        }

        public Criteria andDiasGraciaIsNotNull() {
            addCriterion("DIAS_GRACIA is not null");
            return (Criteria) this;
        }

        public Criteria andDiasGraciaEqualTo(Short value) {
            addCriterion("DIAS_GRACIA =", value, "diasGracia");
            return (Criteria) this;
        }

        public Criteria andDiasGraciaNotEqualTo(Short value) {
            addCriterion("DIAS_GRACIA <>", value, "diasGracia");
            return (Criteria) this;
        }

        public Criteria andDiasGraciaGreaterThan(Short value) {
            addCriterion("DIAS_GRACIA >", value, "diasGracia");
            return (Criteria) this;
        }

        public Criteria andDiasGraciaGreaterThanOrEqualTo(Short value) {
            addCriterion("DIAS_GRACIA >=", value, "diasGracia");
            return (Criteria) this;
        }

        public Criteria andDiasGraciaLessThan(Short value) {
            addCriterion("DIAS_GRACIA <", value, "diasGracia");
            return (Criteria) this;
        }

        public Criteria andDiasGraciaLessThanOrEqualTo(Short value) {
            addCriterion("DIAS_GRACIA <=", value, "diasGracia");
            return (Criteria) this;
        }

        public Criteria andDiasGraciaIn(List<Short> values) {
            addCriterion("DIAS_GRACIA in", values, "diasGracia");
            return (Criteria) this;
        }

        public Criteria andDiasGraciaNotIn(List<Short> values) {
            addCriterion("DIAS_GRACIA not in", values, "diasGracia");
            return (Criteria) this;
        }

        public Criteria andDiasGraciaBetween(Short value1, Short value2) {
            addCriterion("DIAS_GRACIA between", value1, value2, "diasGracia");
            return (Criteria) this;
        }

        public Criteria andDiasGraciaNotBetween(Short value1, Short value2) {
            addCriterion("DIAS_GRACIA not between", value1, value2, "diasGracia");
            return (Criteria) this;
        }

        public Criteria andTstampIsNull() {
            addCriterion("TSTAMP is null");
            return (Criteria) this;
        }

        public Criteria andTstampIsNotNull() {
            addCriterion("TSTAMP is not null");
            return (Criteria) this;
        }

        public Criteria andTstampEqualTo(Date value) {
            addCriterion("TSTAMP =", value, "tstamp");
            return (Criteria) this;
        }

        public Criteria andTstampNotEqualTo(Date value) {
            addCriterion("TSTAMP <>", value, "tstamp");
            return (Criteria) this;
        }

        public Criteria andTstampGreaterThan(Date value) {
            addCriterion("TSTAMP >", value, "tstamp");
            return (Criteria) this;
        }

        public Criteria andTstampGreaterThanOrEqualTo(Date value) {
            addCriterion("TSTAMP >=", value, "tstamp");
            return (Criteria) this;
        }

        public Criteria andTstampLessThan(Date value) {
            addCriterion("TSTAMP <", value, "tstamp");
            return (Criteria) this;
        }

        public Criteria andTstampLessThanOrEqualTo(Date value) {
            addCriterion("TSTAMP <=", value, "tstamp");
            return (Criteria) this;
        }

        public Criteria andTstampIn(List<Date> values) {
            addCriterion("TSTAMP in", values, "tstamp");
            return (Criteria) this;
        }

        public Criteria andTstampNotIn(List<Date> values) {
            addCriterion("TSTAMP not in", values, "tstamp");
            return (Criteria) this;
        }

        public Criteria andTstampBetween(Date value1, Date value2) {
            addCriterion("TSTAMP between", value1, value2, "tstamp");
            return (Criteria) this;
        }

        public Criteria andTstampNotBetween(Date value1, Date value2) {
            addCriterion("TSTAMP not between", value1, value2, "tstamp");
            return (Criteria) this;
        }

        public Criteria andNomUsuarioIsNull() {
            addCriterion("NOM_USUARIO is null");
            return (Criteria) this;
        }

        public Criteria andNomUsuarioIsNotNull() {
            addCriterion("NOM_USUARIO is not null");
            return (Criteria) this;
        }

        public Criteria andNomUsuarioEqualTo(String value) {
            addCriterion("NOM_USUARIO =", value, "nomUsuario");
            return (Criteria) this;
        }

        public Criteria andNomUsuarioNotEqualTo(String value) {
            addCriterion("NOM_USUARIO <>", value, "nomUsuario");
            return (Criteria) this;
        }

        public Criteria andNomUsuarioGreaterThan(String value) {
            addCriterion("NOM_USUARIO >", value, "nomUsuario");
            return (Criteria) this;
        }

        public Criteria andNomUsuarioGreaterThanOrEqualTo(String value) {
            addCriterion("NOM_USUARIO >=", value, "nomUsuario");
            return (Criteria) this;
        }

        public Criteria andNomUsuarioLessThan(String value) {
            addCriterion("NOM_USUARIO <", value, "nomUsuario");
            return (Criteria) this;
        }

        public Criteria andNomUsuarioLessThanOrEqualTo(String value) {
            addCriterion("NOM_USUARIO <=", value, "nomUsuario");
            return (Criteria) this;
        }

        public Criteria andNomUsuarioLike(String value) {
            addCriterion("NOM_USUARIO like", value, "nomUsuario");
            return (Criteria) this;
        }

        public Criteria andNomUsuarioNotLike(String value) {
            addCriterion("NOM_USUARIO not like", value, "nomUsuario");
            return (Criteria) this;
        }

        public Criteria andNomUsuarioIn(List<String> values) {
            addCriterion("NOM_USUARIO in", values, "nomUsuario");
            return (Criteria) this;
        }

        public Criteria andNomUsuarioNotIn(List<String> values) {
            addCriterion("NOM_USUARIO not in", values, "nomUsuario");
            return (Criteria) this;
        }

        public Criteria andNomUsuarioBetween(String value1, String value2) {
            addCriterion("NOM_USUARIO between", value1, value2, "nomUsuario");
            return (Criteria) this;
        }

        public Criteria andNomUsuarioNotBetween(String value1, String value2) {
            addCriterion("NOM_USUARIO not between", value1, value2, "nomUsuario");
            return (Criteria) this;
        }

        public Criteria andApeUsuarioIsNull() {
            addCriterion("APE_USUARIO is null");
            return (Criteria) this;
        }

        public Criteria andApeUsuarioIsNotNull() {
            addCriterion("APE_USUARIO is not null");
            return (Criteria) this;
        }

        public Criteria andApeUsuarioEqualTo(String value) {
            addCriterion("APE_USUARIO =", value, "apeUsuario");
            return (Criteria) this;
        }

        public Criteria andApeUsuarioNotEqualTo(String value) {
            addCriterion("APE_USUARIO <>", value, "apeUsuario");
            return (Criteria) this;
        }

        public Criteria andApeUsuarioGreaterThan(String value) {
            addCriterion("APE_USUARIO >", value, "apeUsuario");
            return (Criteria) this;
        }

        public Criteria andApeUsuarioGreaterThanOrEqualTo(String value) {
            addCriterion("APE_USUARIO >=", value, "apeUsuario");
            return (Criteria) this;
        }

        public Criteria andApeUsuarioLessThan(String value) {
            addCriterion("APE_USUARIO <", value, "apeUsuario");
            return (Criteria) this;
        }

        public Criteria andApeUsuarioLessThanOrEqualTo(String value) {
            addCriterion("APE_USUARIO <=", value, "apeUsuario");
            return (Criteria) this;
        }

        public Criteria andApeUsuarioLike(String value) {
            addCriterion("APE_USUARIO like", value, "apeUsuario");
            return (Criteria) this;
        }

        public Criteria andApeUsuarioNotLike(String value) {
            addCriterion("APE_USUARIO not like", value, "apeUsuario");
            return (Criteria) this;
        }

        public Criteria andApeUsuarioIn(List<String> values) {
            addCriterion("APE_USUARIO in", values, "apeUsuario");
            return (Criteria) this;
        }

        public Criteria andApeUsuarioNotIn(List<String> values) {
            addCriterion("APE_USUARIO not in", values, "apeUsuario");
            return (Criteria) this;
        }

        public Criteria andApeUsuarioBetween(String value1, String value2) {
            addCriterion("APE_USUARIO between", value1, value2, "apeUsuario");
            return (Criteria) this;
        }

        public Criteria andApeUsuarioNotBetween(String value1, String value2) {
            addCriterion("APE_USUARIO not between", value1, value2, "apeUsuario");
            return (Criteria) this;
        }

        public Criteria andIndCierrePendienteIsNull() {
            addCriterion("IND_CIERRE_PENDIENTE is null");
            return (Criteria) this;
        }

        public Criteria andIndCierrePendienteIsNotNull() {
            addCriterion("IND_CIERRE_PENDIENTE is not null");
            return (Criteria) this;
        }

        public Criteria andIndCierrePendienteEqualTo(String value) {
            addCriterion("IND_CIERRE_PENDIENTE =", value, "indCierrePendiente");
            return (Criteria) this;
        }

        public Criteria andIndCierrePendienteNotEqualTo(String value) {
            addCriterion("IND_CIERRE_PENDIENTE <>", value, "indCierrePendiente");
            return (Criteria) this;
        }

        public Criteria andIndCierrePendienteGreaterThan(String value) {
            addCriterion("IND_CIERRE_PENDIENTE >", value, "indCierrePendiente");
            return (Criteria) this;
        }

        public Criteria andIndCierrePendienteGreaterThanOrEqualTo(String value) {
            addCriterion("IND_CIERRE_PENDIENTE >=", value, "indCierrePendiente");
            return (Criteria) this;
        }

        public Criteria andIndCierrePendienteLessThan(String value) {
            addCriterion("IND_CIERRE_PENDIENTE <", value, "indCierrePendiente");
            return (Criteria) this;
        }

        public Criteria andIndCierrePendienteLessThanOrEqualTo(String value) {
            addCriterion("IND_CIERRE_PENDIENTE <=", value, "indCierrePendiente");
            return (Criteria) this;
        }

        public Criteria andIndCierrePendienteLike(String value) {
            addCriterion("IND_CIERRE_PENDIENTE like", value, "indCierrePendiente");
            return (Criteria) this;
        }

        public Criteria andIndCierrePendienteNotLike(String value) {
            addCriterion("IND_CIERRE_PENDIENTE not like", value, "indCierrePendiente");
            return (Criteria) this;
        }

        public Criteria andIndCierrePendienteIn(List<String> values) {
            addCriterion("IND_CIERRE_PENDIENTE in", values, "indCierrePendiente");
            return (Criteria) this;
        }

        public Criteria andIndCierrePendienteNotIn(List<String> values) {
            addCriterion("IND_CIERRE_PENDIENTE not in", values, "indCierrePendiente");
            return (Criteria) this;
        }

        public Criteria andIndCierrePendienteBetween(String value1, String value2) {
            addCriterion("IND_CIERRE_PENDIENTE between", value1, value2, "indCierrePendiente");
            return (Criteria) this;
        }

        public Criteria andIndCierrePendienteNotBetween(String value1, String value2) {
            addCriterion("IND_CIERRE_PENDIENTE not between", value1, value2, "indCierrePendiente");
            return (Criteria) this;
        }

        public Criteria andAlertaCkCustodiaIsNull() {
            addCriterion("ALERTA_CK_CUSTODIA is null");
            return (Criteria) this;
        }

        public Criteria andAlertaCkCustodiaIsNotNull() {
            addCriterion("ALERTA_CK_CUSTODIA is not null");
            return (Criteria) this;
        }

        public Criteria andAlertaCkCustodiaEqualTo(String value) {
            addCriterion("ALERTA_CK_CUSTODIA =", value, "alertaCkCustodia");
            return (Criteria) this;
        }

        public Criteria andAlertaCkCustodiaNotEqualTo(String value) {
            addCriterion("ALERTA_CK_CUSTODIA <>", value, "alertaCkCustodia");
            return (Criteria) this;
        }

        public Criteria andAlertaCkCustodiaGreaterThan(String value) {
            addCriterion("ALERTA_CK_CUSTODIA >", value, "alertaCkCustodia");
            return (Criteria) this;
        }

        public Criteria andAlertaCkCustodiaGreaterThanOrEqualTo(String value) {
            addCriterion("ALERTA_CK_CUSTODIA >=", value, "alertaCkCustodia");
            return (Criteria) this;
        }

        public Criteria andAlertaCkCustodiaLessThan(String value) {
            addCriterion("ALERTA_CK_CUSTODIA <", value, "alertaCkCustodia");
            return (Criteria) this;
        }

        public Criteria andAlertaCkCustodiaLessThanOrEqualTo(String value) {
            addCriterion("ALERTA_CK_CUSTODIA <=", value, "alertaCkCustodia");
            return (Criteria) this;
        }

        public Criteria andAlertaCkCustodiaLike(String value) {
            addCriterion("ALERTA_CK_CUSTODIA like", value, "alertaCkCustodia");
            return (Criteria) this;
        }

        public Criteria andAlertaCkCustodiaNotLike(String value) {
            addCriterion("ALERTA_CK_CUSTODIA not like", value, "alertaCkCustodia");
            return (Criteria) this;
        }

        public Criteria andAlertaCkCustodiaIn(List<String> values) {
            addCriterion("ALERTA_CK_CUSTODIA in", values, "alertaCkCustodia");
            return (Criteria) this;
        }

        public Criteria andAlertaCkCustodiaNotIn(List<String> values) {
            addCriterion("ALERTA_CK_CUSTODIA not in", values, "alertaCkCustodia");
            return (Criteria) this;
        }

        public Criteria andAlertaCkCustodiaBetween(String value1, String value2) {
            addCriterion("ALERTA_CK_CUSTODIA between", value1, value2, "alertaCkCustodia");
            return (Criteria) this;
        }

        public Criteria andAlertaCkCustodiaNotBetween(String value1, String value2) {
            addCriterion("ALERTA_CK_CUSTODIA not between", value1, value2, "alertaCkCustodia");
            return (Criteria) this;
        }

        public Criteria andAlertaCrRapidosIsNull() {
            addCriterion("ALERTA_CR_RAPIDOS is null");
            return (Criteria) this;
        }

        public Criteria andAlertaCrRapidosIsNotNull() {
            addCriterion("ALERTA_CR_RAPIDOS is not null");
            return (Criteria) this;
        }

        public Criteria andAlertaCrRapidosEqualTo(String value) {
            addCriterion("ALERTA_CR_RAPIDOS =", value, "alertaCrRapidos");
            return (Criteria) this;
        }

        public Criteria andAlertaCrRapidosNotEqualTo(String value) {
            addCriterion("ALERTA_CR_RAPIDOS <>", value, "alertaCrRapidos");
            return (Criteria) this;
        }

        public Criteria andAlertaCrRapidosGreaterThan(String value) {
            addCriterion("ALERTA_CR_RAPIDOS >", value, "alertaCrRapidos");
            return (Criteria) this;
        }

        public Criteria andAlertaCrRapidosGreaterThanOrEqualTo(String value) {
            addCriterion("ALERTA_CR_RAPIDOS >=", value, "alertaCrRapidos");
            return (Criteria) this;
        }

        public Criteria andAlertaCrRapidosLessThan(String value) {
            addCriterion("ALERTA_CR_RAPIDOS <", value, "alertaCrRapidos");
            return (Criteria) this;
        }

        public Criteria andAlertaCrRapidosLessThanOrEqualTo(String value) {
            addCriterion("ALERTA_CR_RAPIDOS <=", value, "alertaCrRapidos");
            return (Criteria) this;
        }

        public Criteria andAlertaCrRapidosLike(String value) {
            addCriterion("ALERTA_CR_RAPIDOS like", value, "alertaCrRapidos");
            return (Criteria) this;
        }

        public Criteria andAlertaCrRapidosNotLike(String value) {
            addCriterion("ALERTA_CR_RAPIDOS not like", value, "alertaCrRapidos");
            return (Criteria) this;
        }

        public Criteria andAlertaCrRapidosIn(List<String> values) {
            addCriterion("ALERTA_CR_RAPIDOS in", values, "alertaCrRapidos");
            return (Criteria) this;
        }

        public Criteria andAlertaCrRapidosNotIn(List<String> values) {
            addCriterion("ALERTA_CR_RAPIDOS not in", values, "alertaCrRapidos");
            return (Criteria) this;
        }

        public Criteria andAlertaCrRapidosBetween(String value1, String value2) {
            addCriterion("ALERTA_CR_RAPIDOS between", value1, value2, "alertaCrRapidos");
            return (Criteria) this;
        }

        public Criteria andAlertaCrRapidosNotBetween(String value1, String value2) {
            addCriterion("ALERTA_CR_RAPIDOS not between", value1, value2, "alertaCrRapidos");
            return (Criteria) this;
        }

        public Criteria andIndActualizaFmIsNull() {
            addCriterion("IND_ACTUALIZA_FM is null");
            return (Criteria) this;
        }

        public Criteria andIndActualizaFmIsNotNull() {
            addCriterion("IND_ACTUALIZA_FM is not null");
            return (Criteria) this;
        }

        public Criteria andIndActualizaFmEqualTo(String value) {
            addCriterion("IND_ACTUALIZA_FM =", value, "indActualizaFm");
            return (Criteria) this;
        }

        public Criteria andIndActualizaFmNotEqualTo(String value) {
            addCriterion("IND_ACTUALIZA_FM <>", value, "indActualizaFm");
            return (Criteria) this;
        }

        public Criteria andIndActualizaFmGreaterThan(String value) {
            addCriterion("IND_ACTUALIZA_FM >", value, "indActualizaFm");
            return (Criteria) this;
        }

        public Criteria andIndActualizaFmGreaterThanOrEqualTo(String value) {
            addCriterion("IND_ACTUALIZA_FM >=", value, "indActualizaFm");
            return (Criteria) this;
        }

        public Criteria andIndActualizaFmLessThan(String value) {
            addCriterion("IND_ACTUALIZA_FM <", value, "indActualizaFm");
            return (Criteria) this;
        }

        public Criteria andIndActualizaFmLessThanOrEqualTo(String value) {
            addCriterion("IND_ACTUALIZA_FM <=", value, "indActualizaFm");
            return (Criteria) this;
        }

        public Criteria andIndActualizaFmLike(String value) {
            addCriterion("IND_ACTUALIZA_FM like", value, "indActualizaFm");
            return (Criteria) this;
        }

        public Criteria andIndActualizaFmNotLike(String value) {
            addCriterion("IND_ACTUALIZA_FM not like", value, "indActualizaFm");
            return (Criteria) this;
        }

        public Criteria andIndActualizaFmIn(List<String> values) {
            addCriterion("IND_ACTUALIZA_FM in", values, "indActualizaFm");
            return (Criteria) this;
        }

        public Criteria andIndActualizaFmNotIn(List<String> values) {
            addCriterion("IND_ACTUALIZA_FM not in", values, "indActualizaFm");
            return (Criteria) this;
        }

        public Criteria andIndActualizaFmBetween(String value1, String value2) {
            addCriterion("IND_ACTUALIZA_FM between", value1, value2, "indActualizaFm");
            return (Criteria) this;
        }

        public Criteria andIndActualizaFmNotBetween(String value1, String value2) {
            addCriterion("IND_ACTUALIZA_FM not between", value1, value2, "indActualizaFm");
            return (Criteria) this;
        }

        public Criteria andCdPerfilPerIsNull() {
            addCriterion("CD_PERFIL_PER is null");
            return (Criteria) this;
        }

        public Criteria andCdPerfilPerIsNotNull() {
            addCriterion("CD_PERFIL_PER is not null");
            return (Criteria) this;
        }

        public Criteria andCdPerfilPerEqualTo(BigDecimal value) {
            addCriterion("CD_PERFIL_PER =", value, "cdPerfilPer");
            return (Criteria) this;
        }

        public Criteria andCdPerfilPerNotEqualTo(BigDecimal value) {
            addCriterion("CD_PERFIL_PER <>", value, "cdPerfilPer");
            return (Criteria) this;
        }

        public Criteria andCdPerfilPerGreaterThan(BigDecimal value) {
            addCriterion("CD_PERFIL_PER >", value, "cdPerfilPer");
            return (Criteria) this;
        }

        public Criteria andCdPerfilPerGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("CD_PERFIL_PER >=", value, "cdPerfilPer");
            return (Criteria) this;
        }

        public Criteria andCdPerfilPerLessThan(BigDecimal value) {
            addCriterion("CD_PERFIL_PER <", value, "cdPerfilPer");
            return (Criteria) this;
        }

        public Criteria andCdPerfilPerLessThanOrEqualTo(BigDecimal value) {
            addCriterion("CD_PERFIL_PER <=", value, "cdPerfilPer");
            return (Criteria) this;
        }

        public Criteria andCdPerfilPerIn(List<BigDecimal> values) {
            addCriterion("CD_PERFIL_PER in", values, "cdPerfilPer");
            return (Criteria) this;
        }

        public Criteria andCdPerfilPerNotIn(List<BigDecimal> values) {
            addCriterion("CD_PERFIL_PER not in", values, "cdPerfilPer");
            return (Criteria) this;
        }

        public Criteria andCdPerfilPerBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("CD_PERFIL_PER between", value1, value2, "cdPerfilPer");
            return (Criteria) this;
        }

        public Criteria andCdPerfilPerNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("CD_PERFIL_PER not between", value1, value2, "cdPerfilPer");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table NAF6.PVUSUARIOS
     *
     * @mbggenerated do_not_delete_during_merge Tue Apr 21 12:41:59 COT 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table NAF6.PVUSUARIOS
     *
     * @mbggenerated Tue Apr 21 12:41:59 COT 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}