//inserta perfiles

INSERT INTO CAMPAIGNS.CP_PERFIL(PERFIL_ID, NOMBRE) 
    VALUES(SECUENCIA_CP_PERFIL.nextval, 'ADMINISTRADOR')
GO

INSERT INTO CAMPAIGNS.CP_PERFIL(PERFIL_ID, NOMBRE) 
    VALUES(SECUENCIA_CP_PERFIL.nextval, 'GERENTE')
GO

INSERT INTO CAMPAIGNS.CP_PERFIL(PERFIL_ID, NOMBRE) 
    VALUES(SECUENCIA_CP_PERFIL.nextval, 'COMERCIAL')
GO




// permisos por perfil

INSERT INTO CP_PERMISO_PERFIL VALUES (1, 'CAMPAIGN_ADMIN_INSERT')
GO
INSERT INTO CP_PERMISO_PERFIL VALUES (1, 'CAMPAIGN_ADMIN_UPDATE')
GO
INSERT INTO CP_PERMISO_PERFIL VALUES (1, 'CAMPAIGN_ADMIN_SEARCH')
GO
INSERT INTO CP_PERMISO_PERFIL VALUES (1, 'CAMPAIGN_ADMIN_VIEW')
GO
INSERT INTO CP_PERMISO_PERFIL VALUES (1, 'CAMPAIGN_VIEW')
GO
INSERT INTO CP_PERMISO_PERFIL VALUES (1, 'CAMPAIGN_START')
GO
INSERT INTO CP_PERMISO_PERFIL VALUES (1, 'CAMPAIGN_REPORT_VIEW')
GO
INSERT INTO CP_PERMISO_PERFIL VALUES (1, 'AUTHORS_ADMIN_INSERT')
GO
INSERT INTO CP_PERMISO_PERFIL VALUES (1, 'AUTHORS_ADMIN_UPDATE')
GO
INSERT INTO CP_PERMISO_PERFIL VALUES (1, 'AUTHORS_ADMIN_DELETE')
GO
INSERT INTO CP_PERMISO_PERFIL VALUES (1, 'AUTHORS_ADMIN_VIEW')
GO
INSERT INTO CP_PERMISO_PERFIL VALUES (1, 'MY_CAMPAIGN_VIEW')
GO
INSERT INTO CP_PERMISO_PERFIL VALUES (1, 'CAMPAIGN_ADMIN_DELETE')
GO
INSERT INTO CP_PERMISO_PERFIL VALUES (1, 'CAMPAIGN_ADMIN_APROVE')
GO
INSERT INTO CP_PERMISO_PERFIL VALUES (3, 'CAMPAIGN_ADMIN_INSERT')
GO
INSERT INTO CP_PERMISO_PERFIL VALUES (3, 'CAMPAIGN_ADMIN_UPDATE')
GO
INSERT INTO CP_PERMISO_PERFIL VALUES (3, 'CAMPAIGN_ADMIN_SEARCH')
GO
INSERT INTO CP_PERMISO_PERFIL VALUES (3, 'CAMPAIGN_ADMIN_VIEW')
GO
INSERT INTO CP_PERMISO_PERFIL VALUES (3, 'CAMPAIGN_VIEW')
GO
INSERT INTO CP_PERMISO_PERFIL VALUES (3, 'CAMPAIGN_START')
GO
INSERT INTO CP_PERMISO_PERFIL VALUES (3, 'CAMPAIGN_REPORT_VIEW')
GO
INSERT INTO CP_PERMISO_PERFIL VALUES (3, 'AUTHORS_ADMIN_INSERT')
GO
INSERT INTO CP_PERMISO_PERFIL VALUES (3, 'AUTHORS_ADMIN_UPDATE')
GO
INSERT INTO CP_PERMISO_PERFIL VALUES (3, 'AUTHORS_ADMIN_DELETE')
GO
INSERT INTO CP_PERMISO_PERFIL VALUES (3, 'AUTHORS_ADMIN_VIEW')
GO
INSERT INTO CP_PERMISO_PERFIL VALUES (3, 'MY_CAMPAIGN_VIEW')
GO
INSERT INTO CP_PERMISO_PERFIL VALUES (2, 'CAMPAIGN_ADMIN_UPDATE')
GO
INSERT INTO CP_PERMISO_PERFIL VALUES (2, 'CAMPAIGN_ADMIN_DELETE')
GO
INSERT INTO CP_PERMISO_PERFIL VALUES (2, 'CAMPAIGN_ADMIN_APROVE')
GO
INSERT INTO CP_PERMISO_PERFIL VALUES (2, 'CAMPAIGN_ADMIN_SEARCH')
GO
INSERT INTO CP_PERMISO_PERFIL VALUES (2, 'CAMPAIGN_ADMIN_VIEW')
GO
INSERT INTO CP_PERMISO_PERFIL VALUES (2, 'CAMPAIGN_REPORT_VIEW')

//INSERT USUARIO GENERICO C051
GO
INSERT INTO CAMPAIGNS.CP_USUARIO_PERFIL(USU_PER_ID, PERFIL_ID, COD_USUARIO) 
    VALUES(SECUENCIA_CP_USUARIO_PERFIL.nextval, 1, 'C051')
