CREATE SEQUENCE SECUENCIA_CP_CAMPANIAS
INCREMENT BY 1
START WITH 1

CREATE SEQUENCE SECUENCIA_CP_SEGUIMIENTO
INCREMENT BY 1
START WITH 1

CREATE SEQUENCE SECUENCIA_CP_CLIENTE
START WITH 1

CREATE SEQUENCE SECUENCIA_CP_ESTADO_SEGUIMIENT
INCREMENT BY 1
START WITH 1

CREATE SEQUENCE SECUENCIA_CP_INFO_AUDIT
INCREMENT BY 1
START WITH 1

CREATE SEQUENCE SECUENCIA_CP_DETALLE_AUDIT
INCREMENT BY 1
START WITH 1

CREATE SEQUENCE SECUENCIA_CP_AUTOR
INCREMENT BY 1
START WITH 1

CREATE SEQUENCE SECUENCIA_CP_PERFIL
INCREMENT BY 1
START WITH 1


CREATE SEQUENCE SECUENCIA_CP_USUARIO_PERFIL
INCREMENT BY 1
START WITH 1

CREATE SEQUENCE SECUENCIA_CP_SEGUIMIENTO_MSJ
INCREMENT BY 1
START WITH 1


