package com.fi.crm.campaigns.web.components;

import com.fi.crm.campaigns.web.util.Messages;
import com.fi.crm.campaigns.web.validators.DateRangeValidator;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.shared.ui.MarginInfo;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.DateField;
import com.vaadin.ui.HorizontalLayout;

public class DateRangeComponent extends CustomComponent {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	@AutoGenerated
	private HorizontalLayout mainLayout;
	private DateField startDate;
	private DateField endDate;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public DateRangeComponent() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
	}

	@AutoGenerated
	private void buildMainLayout() {
		// the main layout and components will be created here
		mainLayout = new HorizontalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setSpacing(true);
		mainLayout.setWidth("100%");
		// mainLayout.setHeight("120px");
		mainLayout.setMargin(new MarginInfo(false, false, false, true));
		mainLayout.setStyleName("titleSec");

		startDate = new DateField();
		startDate.setDateFormat("dd/MM/yyyy");
		startDate.setCaption(Messages.getString("DateRangeComponent.start.date"));
		
		endDate = new DateField();
		endDate.setDateFormat("dd/MM/yyyy");
		endDate.setCaption(Messages.getString("DateRangeComponent.end.date"));
		endDate.setImmediate(true);
		endDate.addValidator(new DateRangeValidator(startDate.getValue(), endDate.getValue(), Messages.getString("DateRangeComponent.error")));
		
		mainLayout.addComponent(startDate);
		mainLayout.addComponent(endDate);
		// top-level component properties
		setWidth("100.0%");
	}

}
